import type { Kanji } from "./types";

export const N1_KANJI: Kanji[] = [
  {
    id: "n1-000",
    character: "亜",
    level: "N1",
    setIndex: 0,
    positionInSet: 0,
    onyomi: ["ア"],
    kunyomi: ["つ.ぐ"],
    meanings: ["Asia", "rank next", "come after", "sub-"],
    strokeCount: 7,
    exampleWords: [
      { word: "亜熱帯", reading: "あねったい", meaning: "subtropical zone" },
      { word: "東亜", reading: "とうあ", meaning: "East Asia" },
    ],
  },
  {
    id: "n1-001",
    character: "哀",
    level: "N1",
    setIndex: 0,
    positionInSet: 1,
    onyomi: ["アイ"],
    kunyomi: ["あわ.れ", "あわ.れむ", "かな.しい"],
    meanings: ["sorrow", "grief", "pathos", "pity"],
    strokeCount: 9,
    exampleWords: [
      { word: "哀愁", reading: "あいしゅう", meaning: "sorrow, grief" },
      { word: "悲哀", reading: "ひあい", meaning: "sorrow, sadness" },
      { word: "哀れ", reading: "あわれ", meaning: "pity, compassion" },
    ],
  },
  {
    id: "n1-002",
    character: "握",
    level: "N1",
    setIndex: 0,
    positionInSet: 2,
    onyomi: ["アク"],
    kunyomi: ["にぎ.る"],
    meanings: ["grip", "hold", "clutch"],
    strokeCount: 12,
    exampleWords: [
      { word: "握力", reading: "あくりょく", meaning: "grip strength" },
      { word: "握手", reading: "あくしゅ", meaning: "handshake" },
    ],
  },
  {
    id: "n1-003",
    character: "斡",
    level: "N1",
    setIndex: 0,
    positionInSet: 3,
    onyomi: ["アツ", "アン"],
    kunyomi: [],
    meanings: ["mediate", "arrange", "supervise"],
    strokeCount: 14,
    exampleWords: [
      { word: "斡旋", reading: "あっせん", meaning: "mediation, good offices" },
    ],
  },
  {
    id: "n1-004",
    character: "蔑",
    level: "N1",
    setIndex: 0,
    positionInSet: 4,
    onyomi: ["ベツ"],
    kunyomi: ["さげす.む"],
    meanings: ["despise", "scorn", "look down on"],
    strokeCount: 14,
    exampleWords: [
      { word: "蔑視", reading: "べっし", meaning: "contempt, disdain" },
      { word: "侮蔑", reading: "ぶべつ", meaning: "contempt, scorn" },
    ],
  },
  {
    id: "n1-005",
    character: "壱",
    level: "N1",
    setIndex: 0,
    positionInSet: 5,
    onyomi: ["イチ"],
    kunyomi: [],
    meanings: ["one (formal writing)", "first"],
    strokeCount: 7,
    exampleWords: [
      { word: "壱万円", reading: "いちまんえん", meaning: "ten thousand yen (formal)" },
    ],
  },
  {
    id: "n1-006",
    character: "逸",
    level: "N1",
    setIndex: 0,
    positionInSet: 6,
    onyomi: ["イツ"],
    kunyomi: ["そ.れる", "そ.らす"],
    meanings: ["deviate", "excel", "slip away", "outstanding"],
    strokeCount: 11,
    exampleWords: [
      { word: "逸材", reading: "いつざい", meaning: "exceptional talent" },
      { word: "逸話", reading: "いつわ", meaning: "anecdote, episode" },
      { word: "秀逸", reading: "しゅういつ", meaning: "excellent, outstanding" },
    ],
  },
  {
    id: "n1-007",
    character: "姻",
    level: "N1",
    setIndex: 0,
    positionInSet: 7,
    onyomi: ["イン"],
    kunyomi: [],
    meanings: ["matrimony", "marry into", "marriage"],
    strokeCount: 9,
    exampleWords: [
      { word: "婚姻", reading: "こんいん", meaning: "marriage, matrimony" },
      { word: "姻族", reading: "いんぞく", meaning: "relatives by marriage" },
    ],
  },
  {
    id: "n1-008",
    character: "隠",
    level: "N1",
    setIndex: 0,
    positionInSet: 8,
    onyomi: ["イン", "オン"],
    kunyomi: ["かく.す", "かく.れる", "かく.し"],
    meanings: ["conceal", "hide", "secret"],
    strokeCount: 14,
    exampleWords: [
      { word: "隠れる", reading: "かくれる", meaning: "to hide, to be hidden" },
      { word: "隠す", reading: "かくす", meaning: "to hide, to conceal" },
      { word: "隠蔽", reading: "いんぺい", meaning: "concealment, cover-up" },
    ],
  },
  {
    id: "n1-009",
    character: "韻",
    level: "N1",
    setIndex: 0,
    positionInSet: 9,
    onyomi: ["イン"],
    kunyomi: [],
    meanings: ["rhyme", "elegance", "tone"],
    strokeCount: 19,
    exampleWords: [
      { word: "韻律", reading: "いんりつ", meaning: "rhythm, meter" },
      { word: "押韻", reading: "おういん", meaning: "rhyme" },
      { word: "余韻", reading: "よいん", meaning: "lingering sound, aftertaste" },
    ],
  },
  {
    id: "n1-010",
    character: "渦",
    level: "N1",
    setIndex: 0,
    positionInSet: 10,
    onyomi: ["カ"],
    kunyomi: ["うず"],
    meanings: ["whirlpool", "eddy", "vortex"],
    strokeCount: 12,
    exampleWords: [
      { word: "渦巻く", reading: "うずまく", meaning: "to whirl, to swirl" },
      { word: "渦中", reading: "かちゅう", meaning: "in the middle of a whirlpool" },
      { word: "渦", reading: "うず", meaning: "whirlpool, vortex" },
    ],
  },
  {
    id: "n1-011",
    character: "浦",
    level: "N1",
    setIndex: 0,
    positionInSet: 11,
    onyomi: ["ホ"],
    kunyomi: ["うら"],
    meanings: ["bay", "inlet", "creek", "coastal village"],
    strokeCount: 10,
    exampleWords: [
      { word: "浦", reading: "うら", meaning: "bay, inlet" },
      { word: "浦辺", reading: "うらべ", meaning: "coastal area" },
    ],
  },
  {
    id: "n1-012",
    character: "鋭",
    level: "N1",
    setIndex: 0,
    positionInSet: 12,
    onyomi: ["エイ"],
    kunyomi: ["するど.い"],
    meanings: ["sharp", "keen", "acute", "pointed"],
    strokeCount: 15,
    exampleWords: [
      { word: "鋭い", reading: "するどい", meaning: "sharp, keen, acute" },
      { word: "鋭利", reading: "えいり", meaning: "sharpness, keenness" },
      { word: "精鋭", reading: "せいえい", meaning: "elite, the best" },
    ],
  },
  {
    id: "n1-013",
    character: "悦",
    level: "N1",
    setIndex: 0,
    positionInSet: 13,
    onyomi: ["エツ"],
    kunyomi: ["よろこ.ぶ"],
    meanings: ["joy", "pleased", "delight"],
    strokeCount: 10,
    exampleWords: [
      { word: "悦楽", reading: "えつらく", meaning: "pleasure, enjoyment" },
      { word: "満悦", reading: "まんえつ", meaning: "great satisfaction" },
      { word: "喜悦", reading: "きえつ", meaning: "joy, delight" },
    ],
  },
  {
    id: "n1-014",
    character: "謁",
    level: "N1",
    setIndex: 0,
    positionInSet: 14,
    onyomi: ["エツ"],
    kunyomi: [],
    meanings: ["audience", "have audience with"],
    strokeCount: 15,
    exampleWords: [
      { word: "謁見", reading: "えっけん", meaning: "audience, interview" },
    ],
  },
  {
    id: "n1-015",
    character: "艶",
    level: "N1",
    setIndex: 0,
    positionInSet: 15,
    onyomi: ["エン"],
    kunyomi: ["つや", "なま.めかしい"],
    meanings: ["luster", "gloss", "glamour", "allure"],
    strokeCount: 19,
    exampleWords: [
      { word: "艶やか", reading: "つややか", meaning: "lustrous, glossy" },
      { word: "艶", reading: "つや", meaning: "luster, gloss, charm" },
    ],
  },
  {
    id: "n1-016",
    character: "凹",
    level: "N1",
    setIndex: 0,
    positionInSet: 16,
    onyomi: ["オウ"],
    kunyomi: ["くぼ.む", "へこ.む"],
    meanings: ["concave", "hollow", "dent"],
    strokeCount: 5,
    exampleWords: [
      { word: "凹む", reading: "へこむ", meaning: "to dent, to cave in" },
      { word: "凹凸", reading: "おうとつ", meaning: "unevenness, irregularity" },
      { word: "凹面", reading: "おうめん", meaning: "concave surface" },
    ],
  },
  {
    id: "n1-017",
    character: "臆",
    level: "N1",
    setIndex: 0,
    positionInSet: 17,
    onyomi: ["オク"],
    kunyomi: ["おく.する"],
    meanings: ["timid", "shrink from", "be hesitant"],
    strokeCount: 17,
    exampleWords: [
      { word: "臆病", reading: "おくびょう", meaning: "cowardice, timidity" },
      { word: "臆測", reading: "おくそく", meaning: "conjecture, speculation" },
    ],
  },
  {
    id: "n1-018",
    character: "卸",
    level: "N1",
    setIndex: 0,
    positionInSet: 18,
    onyomi: ["シャ"],
    kunyomi: ["おろ.す", "おろし"],
    meanings: ["wholesale", "unload"],
    strokeCount: 9,
    exampleWords: [
      { word: "卸売り", reading: "おろしうり", meaning: "wholesale" },
      { word: "卸業者", reading: "おろしぎょうしゃ", meaning: "wholesaler" },
    ],
  },
  {
    id: "n1-019",
    character: "穏",
    level: "N1",
    setIndex: 0,
    positionInSet: 19,
    onyomi: ["オン"],
    kunyomi: ["おだ.やか"],
    meanings: ["calm", "quiet", "gentle", "mild"],
    strokeCount: 16,
    exampleWords: [
      { word: "穏やか", reading: "おだやか", meaning: "calm, gentle, mild" },
      { word: "穏健", reading: "おんけん", meaning: "moderate, temperate" },
      { word: "平穏", reading: "へいおん", meaning: "tranquility, peace" },
    ],
  },
  {
    id: "n1-020",
    character: "佳",
    level: "N1",
    setIndex: 1,
    positionInSet: 0,
    onyomi: ["カ"],
    kunyomi: [],
    meanings: ["beautiful", "good", "excellent"],
    strokeCount: 8,
    exampleWords: [
      { word: "佳作", reading: "かさく", meaning: "good work, honorable mention" },
      { word: "佳境", reading: "かきょう", meaning: "the best part, climax" },
    ],
  },
  {
    id: "n1-021",
    character: "嫁",
    level: "N1",
    setIndex: 1,
    positionInSet: 1,
    onyomi: ["カ"],
    kunyomi: ["よめ", "とつ.ぐ"],
    meanings: ["marry into family", "bride", "daughter-in-law"],
    strokeCount: 13,
    exampleWords: [
      { word: "嫁", reading: "よめ", meaning: "bride, daughter-in-law" },
      { word: "嫁ぐ", reading: "とつぐ", meaning: "to marry (of a woman)" },
      { word: "花嫁", reading: "はなよめ", meaning: "bride" },
    ],
  },
  {
    id: "n1-022",
    character: "寡",
    level: "N1",
    setIndex: 1,
    positionInSet: 2,
    onyomi: ["カ"],
    kunyomi: [],
    meanings: ["widow", "few", "alone"],
    strokeCount: 14,
    exampleWords: [
      { word: "寡黙", reading: "かもく", meaning: "taciturn, silent" },
      { word: "寡婦", reading: "かふ", meaning: "widow" },
    ],
  },
  {
    id: "n1-023",
    character: "架",
    level: "N1",
    setIndex: 1,
    positionInSet: 3,
    onyomi: ["カ"],
    kunyomi: ["か.ける", "か.かる"],
    meanings: ["erect", "build span", "mount on", "shelf"],
    strokeCount: 9,
    exampleWords: [
      { word: "架け橋", reading: "かけはし", meaning: "bridge, go-between" },
      { word: "架空", reading: "かくう", meaning: "fictitious, imaginary" },
      { word: "十字架", reading: "じゅうじか", meaning: "cross, crucifix" },
    ],
  },
  {
    id: "n1-024",
    character: "箇",
    level: "N1",
    setIndex: 1,
    positionInSet: 4,
    onyomi: ["カ", "コ"],
    kunyomi: [],
    meanings: ["item", "counter for objects"],
    strokeCount: 14,
    exampleWords: [
      { word: "箇所", reading: "かしょ", meaning: "place, point, part" },
      { word: "数箇所", reading: "すうかしょ", meaning: "several places" },
    ],
  },
  {
    id: "n1-025",
    character: "雅",
    level: "N1",
    setIndex: 1,
    positionInSet: 5,
    onyomi: ["ガ"],
    kunyomi: ["みや.び"],
    meanings: ["graceful", "elegant", "refined", "correct"],
    strokeCount: 13,
    exampleWords: [
      { word: "優雅", reading: "ゆうが", meaning: "elegant, graceful" },
      { word: "雅楽", reading: "ががく", meaning: "gagaku (court music)" },
      { word: "風雅", reading: "ふうが", meaning: "elegance, refinement" },
    ],
  },
  {
    id: "n1-026",
    character: "蚊",
    level: "N1",
    setIndex: 1,
    positionInSet: 6,
    onyomi: ["ブン"],
    kunyomi: ["か"],
    meanings: ["mosquito"],
    strokeCount: 10,
    exampleWords: [
      { word: "蚊", reading: "か", meaning: "mosquito" },
      { word: "蚊帳", reading: "かや", meaning: "mosquito net" },
    ],
  },
  {
    id: "n1-027",
    character: "戒",
    level: "N1",
    setIndex: 1,
    positionInSet: 7,
    onyomi: ["カイ"],
    kunyomi: ["いまし.める"],
    meanings: ["commandments", "precept", "warn", "prohibit"],
    strokeCount: 7,
    exampleWords: [
      { word: "警戒", reading: "けいかい", meaning: "caution, vigilance" },
      { word: "戒める", reading: "いましめる", meaning: "to caution, to warn" },
      { word: "戒律", reading: "かいりつ", meaning: "commandments, rules" },
    ],
  },
  {
    id: "n1-028",
    character: "塊",
    level: "N1",
    setIndex: 1,
    positionInSet: 8,
    onyomi: ["カイ"],
    kunyomi: ["かたまり", "かた.まる"],
    meanings: ["clod", "lump", "chunk", "clump"],
    strokeCount: 13,
    exampleWords: [
      { word: "塊", reading: "かたまり", meaning: "lump, chunk, clump" },
      { word: "岩塊", reading: "がんかい", meaning: "rock mass, boulder" },
    ],
  },
  {
    id: "n1-029",
    character: "懐",
    level: "N1",
    setIndex: 1,
    positionInSet: 9,
    onyomi: ["カイ"],
    kunyomi: ["ふところ", "なつ.かしい", "なつ.かしむ", "なつ.く"],
    meanings: ["pocket", "bosom", "feel nostalgic", "miss"],
    strokeCount: 16,
    exampleWords: [
      { word: "懐かしい", reading: "なつかしい", meaning: "dear, missed, nostalgic" },
      { word: "懐中", reading: "かいちゅう", meaning: "in one's pocket, inside" },
      { word: "懐疑", reading: "かいぎ", meaning: "doubt, skepticism" },
    ],
  },
  {
    id: "n1-030",
    character: "較",
    level: "N1",
    setIndex: 1,
    positionInSet: 10,
    onyomi: ["カク"],
    kunyomi: [],
    meanings: ["contrast", "compare"],
    strokeCount: 13,
    exampleWords: [
      { word: "比較", reading: "ひかく", meaning: "comparison, contrast" },
      { word: "比較的", reading: "ひかくてき", meaning: "comparatively" },
    ],
  },
  {
    id: "n1-031",
    character: "刈",
    level: "N1",
    setIndex: 1,
    positionInSet: 11,
    onyomi: ["カイ"],
    kunyomi: ["か.る"],
    meanings: ["cut", "clip", "trim", "mow"],
    strokeCount: 4,
    exampleWords: [
      { word: "草刈り", reading: "くさかり", meaning: "grass cutting, mowing" },
      { word: "収刈", reading: "しゅうかい", meaning: "harvest" },
    ],
  },
  {
    id: "n1-032",
    character: "渇",
    level: "N1",
    setIndex: 1,
    positionInSet: 12,
    onyomi: ["カツ"],
    kunyomi: ["かわ.く"],
    meanings: ["thirst", "dry up", "parched"],
    strokeCount: 11,
    exampleWords: [
      { word: "渇く", reading: "かわく", meaning: "to be thirsty, to dry up" },
      { word: "渇望", reading: "かつぼう", meaning: "eager desire, craving" },
      { word: "枯渇", reading: "こかつ", meaning: "exhaustion, running dry" },
    ],
  },
  {
    id: "n1-033",
    character: "喝",
    level: "N1",
    setIndex: 1,
    positionInSet: 13,
    onyomi: ["カツ"],
    kunyomi: [],
    meanings: ["scold", "shout at", "reprimand"],
    strokeCount: 12,
    exampleWords: [
      { word: "喝破", reading: "かっぱ", meaning: "rebuttal, denouncing" },
      { word: "一喝", reading: "いっかつ", meaning: "sharp scolding" },
    ],
  },
  {
    id: "n1-034",
    character: "滑",
    level: "N1",
    setIndex: 1,
    positionInSet: 14,
    onyomi: ["カツ", "コツ"],
    kunyomi: ["すべ.る", "なめ.らか"],
    meanings: ["slippery", "slide", "slip", "smooth"],
    strokeCount: 13,
    exampleWords: [
      { word: "滑る", reading: "すべる", meaning: "to slide, to slip" },
      { word: "滑らか", reading: "なめらか", meaning: "smooth, fluent" },
      { word: "潤滑", reading: "じゅんかつ", meaning: "lubrication" },
    ],
  },
  {
    id: "n1-035",
    character: "冠",
    level: "N1",
    setIndex: 1,
    positionInSet: 15,
    onyomi: ["カン"],
    kunyomi: ["かんむり", "かむ.る"],
    meanings: ["crown", "cap", "put on head"],
    strokeCount: 9,
    exampleWords: [
      { word: "王冠", reading: "おうかん", meaning: "crown" },
      { word: "冠詞", reading: "かんし", meaning: "article (grammar)" },
      { word: "三冠", reading: "さんかん", meaning: "triple crown" },
    ],
  },
  {
    id: "n1-036",
    character: "憾",
    level: "N1",
    setIndex: 1,
    positionInSet: 16,
    onyomi: ["カン"],
    kunyomi: ["うら.む"],
    meanings: ["regret", "resentment", "a matter of regret"],
    strokeCount: 16,
    exampleWords: [
      { word: "遺憾", reading: "いかん", meaning: "regret, deplorable" },
      { word: "痛憾", reading: "つうかん", meaning: "deep regret" },
    ],
  },
  {
    id: "n1-037",
    character: "潟",
    level: "N1",
    setIndex: 1,
    positionInSet: 17,
    onyomi: ["セキ"],
    kunyomi: ["かた"],
    meanings: ["lagoon", "inlet", "tideland"],
    strokeCount: 15,
    exampleWords: [
      { word: "新潟", reading: "にいがた", meaning: "Niigata (prefecture)" },
      { word: "干潟", reading: "ひがた", meaning: "tidal flat, tideland" },
    ],
  },
  {
    id: "n1-038",
    character: "頑",
    level: "N1",
    setIndex: 1,
    positionInSet: 18,
    onyomi: ["ガン"],
    kunyomi: [],
    meanings: ["stubborn", "headstrong", "obstinate"],
    strokeCount: 13,
    exampleWords: [
      { word: "頑固", reading: "がんこ", meaning: "stubbornness, obstinacy" },
      { word: "頑強", reading: "がんきょう", meaning: "tenacious, unyielding" },
    ],
  },
  {
    id: "n1-039",
    character: "既",
    level: "N1",
    setIndex: 1,
    positionInSet: 19,
    onyomi: ["キ"],
    kunyomi: ["すで.に"],
    meanings: ["previously", "already done", "yet"],
    strokeCount: 10,
    exampleWords: [
      { word: "既に", reading: "すでに", meaning: "already, previously" },
      { word: "既存", reading: "きそん", meaning: "existing, established" },
      { word: "既成", reading: "きせい", meaning: "established, existing" },
    ],
  },
  {
    id: "n1-040",
    character: "幾",
    level: "N1",
    setIndex: 2,
    positionInSet: 0,
    onyomi: ["キ"],
    kunyomi: ["いく-", "いく.つ", "いく.ら"],
    meanings: ["how many", "some", "how much"],
    strokeCount: 12,
    exampleWords: [
      { word: "幾つ", reading: "いくつ", meaning: "how many, how old" },
      { word: "幾ら", reading: "いくら", meaning: "how much" },
      { word: "幾何学", reading: "きかがく", meaning: "geometry" },
    ],
  },
  {
    id: "n1-041",
    character: "棄",
    level: "N1",
    setIndex: 2,
    positionInSet: 1,
    onyomi: ["キ"],
    kunyomi: ["す.てる"],
    meanings: ["abandon", "give up", "throw away"],
    strokeCount: 13,
    exampleWords: [
      { word: "廃棄", reading: "はいき", meaning: "disposal, abandonment" },
      { word: "棄権", reading: "きけん", meaning: "abstaining from voting" },
      { word: "放棄", reading: "ほうき", meaning: "abandonment, relinquishment" },
    ],
  },
  {
    id: "n1-042",
    character: "祈",
    level: "N1",
    setIndex: 2,
    positionInSet: 2,
    onyomi: ["キ"],
    kunyomi: ["いの.る"],
    meanings: ["pray", "wish", "hope"],
    strokeCount: 8,
    exampleWords: [
      { word: "祈る", reading: "いのる", meaning: "to pray, to wish" },
      { word: "祈願", reading: "きがん", meaning: "prayer, entreaty" },
      { word: "祈り", reading: "いのり", meaning: "prayer, wish" },
    ],
  },
  {
    id: "n1-043",
    character: "輝",
    level: "N1",
    setIndex: 2,
    positionInSet: 3,
    onyomi: ["キ"],
    kunyomi: ["かがや.く"],
    meanings: ["radiance", "shine", "brilliant", "sparkle"],
    strokeCount: 15,
    exampleWords: [
      { word: "輝く", reading: "かがやく", meaning: "to shine, to gleam" },
      { word: "輝かしい", reading: "かがやかしい", meaning: "brilliant, glorious" },
      { word: "光輝", reading: "こうき", meaning: "brilliance, radiance" },
    ],
  },
  {
    id: "n1-044",
    character: "騎",
    level: "N1",
    setIndex: 2,
    positionInSet: 4,
    onyomi: ["キ"],
    kunyomi: [],
    meanings: ["equestrian", "horseback", "cavalry"],
    strokeCount: 18,
    exampleWords: [
      { word: "騎士", reading: "きし", meaning: "knight, cavalryman" },
      { word: "騎馬", reading: "きば", meaning: "horseback riding" },
      { word: "騎手", reading: "きしゅ", meaning: "jockey, rider" },
    ],
  },
  {
    id: "n1-045",
    character: "虐",
    level: "N1",
    setIndex: 2,
    positionInSet: 5,
    onyomi: ["ギャク"],
    kunyomi: ["しいた.げる"],
    meanings: ["tyrannize", "oppress", "abuse", "cruel"],
    strokeCount: 9,
    exampleWords: [
      { word: "虐待", reading: "ぎゃくたい", meaning: "abuse, mistreatment" },
      { word: "虐殺", reading: "ぎゃくさつ", meaning: "massacre, slaughter" },
    ],
  },
  {
    id: "n1-046",
    character: "矯",
    level: "N1",
    setIndex: 2,
    positionInSet: 6,
    onyomi: ["キョウ"],
    kunyomi: ["た.める"],
    meanings: ["rectify", "correct", "pretend"],
    strokeCount: 17,
    exampleWords: [
      { word: "矯正", reading: "きょうせい", meaning: "correction, reform" },
      { word: "矯める", reading: "ためる", meaning: "to straighten, to correct" },
    ],
  },
  {
    id: "n1-047",
    character: "凝",
    level: "N1",
    setIndex: 2,
    positionInSet: 7,
    onyomi: ["ギョウ"],
    kunyomi: ["こ.る", "こ.らす"],
    meanings: ["congeal", "freeze", "stiff", "obsess"],
    strokeCount: 16,
    exampleWords: [
      { word: "凝る", reading: "こる", meaning: "to be stiff, to be absorbed in" },
      { word: "凝縮", reading: "ぎょうしゅく", meaning: "condensation" },
      { word: "凝視", reading: "ぎょうし", meaning: "staring, gazing" },
    ],
  },
  {
    id: "n1-048",
    character: "駆",
    level: "N1",
    setIndex: 2,
    positionInSet: 8,
    onyomi: ["ク"],
    kunyomi: ["か.ける", "か.る"],
    meanings: ["drive", "run", "gallop"],
    strokeCount: 14,
    exampleWords: [
      { word: "先駆け", reading: "さきがけ", meaning: "pioneer, frontrunner" },
      { word: "駆除", reading: "くじょ", meaning: "extermination, eradication" },
      { word: "疾駆", reading: "しっく", meaning: "dashing, galloping" },
    ],
  },
  {
    id: "n1-049",
    character: "隅",
    level: "N1",
    setIndex: 2,
    positionInSet: 9,
    onyomi: ["グウ"],
    kunyomi: ["すみ"],
    meanings: ["corner", "nook", "recess"],
    strokeCount: 12,
    exampleWords: [
      { word: "隅", reading: "すみ", meaning: "corner, nook" },
      { word: "片隅", reading: "かたすみ", meaning: "corner, nook" },
      { word: "隅々", reading: "すみずみ", meaning: "every nook and corner" },
    ],
  },
  {
    id: "n1-050",
    character: "薫",
    level: "N1",
    setIndex: 2,
    positionInSet: 10,
    onyomi: ["クン"],
    kunyomi: ["かお.る"],
    meanings: ["fragrant", "sweet smelling", "incense"],
    strokeCount: 16,
    exampleWords: [
      { word: "薫る", reading: "かおる", meaning: "to be fragrant, to smell sweet" },
      { word: "薫風", reading: "くんぷう", meaning: "balmy breeze" },
    ],
  },
  {
    id: "n1-051",
    character: "傑",
    level: "N1",
    setIndex: 2,
    positionInSet: 11,
    onyomi: ["ケツ"],
    kunyomi: [],
    meanings: ["outstanding", "excellent", "hero", "greatness"],
    strokeCount: 12,
    exampleWords: [
      { word: "傑作", reading: "けっさく", meaning: "masterpiece, outstanding work" },
      { word: "豪傑", reading: "ごうけつ", meaning: "hero, great man" },
      { word: "傑出", reading: "けっしゅつ", meaning: "outstanding, eminent" },
    ],
  },
  {
    id: "n1-052",
    character: "懸",
    level: "N1",
    setIndex: 2,
    positionInSet: 12,
    onyomi: ["ケン", "ケ"],
    kunyomi: ["か.ける", "か.かる"],
    meanings: ["hang", "suspend", "depend on", "gamble on"],
    strokeCount: 20,
    exampleWords: [
      { word: "懸念", reading: "けねん", meaning: "concern, anxiety" },
      { word: "懸賞", reading: "けんしょう", meaning: "prize, reward" },
      { word: "懸命", reading: "けんめい", meaning: "desperate, earnest" },
    ],
  },
  {
    id: "n1-053",
    character: "稿",
    level: "N1",
    setIndex: 2,
    positionInSet: 13,
    onyomi: ["コウ"],
    kunyomi: ["わら"],
    meanings: ["draft", "manuscript", "straw"],
    strokeCount: 15,
    exampleWords: [
      { word: "原稿", reading: "げんこう", meaning: "manuscript, draft" },
      { word: "投稿", reading: "とうこう", meaning: "submission, contribution" },
      { word: "草稿", reading: "そうこう", meaning: "rough draft" },
    ],
  },
  {
    id: "n1-054",
    character: "拷",
    level: "N1",
    setIndex: 2,
    positionInSet: 14,
    onyomi: ["ゴウ"],
    kunyomi: [],
    meanings: ["torture", "beat", "cudgel"],
    strokeCount: 9,
    exampleWords: [
      { word: "拷問", reading: "ごうもん", meaning: "torture, third degree" },
    ],
  },
  {
    id: "n1-055",
    character: "昏",
    level: "N1",
    setIndex: 2,
    positionInSet: 15,
    onyomi: ["コン"],
    kunyomi: ["くら.い", "たそが.れ"],
    meanings: ["dark", "dusk", "confused"],
    strokeCount: 8,
    exampleWords: [
      { word: "昏睡", reading: "こんすい", meaning: "coma, deep sleep" },
      { word: "昏倒", reading: "こんとう", meaning: "fainting, collapse" },
    ],
  },
  {
    id: "n1-056",
    character: "痕",
    level: "N1",
    setIndex: 2,
    positionInSet: 16,
    onyomi: ["コン"],
    kunyomi: ["あと"],
    meanings: ["scar", "mark", "trace", "remains"],
    strokeCount: 11,
    exampleWords: [
      { word: "痕跡", reading: "こんせき", meaning: "trace, vestige, scar" },
      { word: "傷痕", reading: "きずあと", meaning: "scar, wound mark" },
    ],
  },
  {
    id: "n1-057",
    character: "裾",
    level: "N1",
    setIndex: 2,
    positionInSet: 17,
    onyomi: ["キョ"],
    kunyomi: ["すそ"],
    meanings: ["hem", "skirt", "foot of mountain"],
    strokeCount: 13,
    exampleWords: [
      { word: "裾", reading: "すそ", meaning: "hem, skirt" },
      { word: "山裾", reading: "やまのすそ", meaning: "foot of a mountain" },
    ],
  },
  {
    id: "n1-058",
    character: "債",
    level: "N1",
    setIndex: 2,
    positionInSet: 18,
    onyomi: ["サイ"],
    kunyomi: [],
    meanings: ["debt", "loan", "bonds"],
    strokeCount: 13,
    exampleWords: [
      { word: "負債", reading: "ふさい", meaning: "debt, liabilities" },
      { word: "債権", reading: "さいけん", meaning: "bond, claim" },
      { word: "国債", reading: "こくさい", meaning: "national debt, government bond" },
    ],
  },
  {
    id: "n1-059",
    character: "詐",
    level: "N1",
    setIndex: 2,
    positionInSet: 19,
    onyomi: ["サ"],
    kunyomi: ["いつわ.る"],
    meanings: ["lie", "falsehood", "fraud", "deceive"],
    strokeCount: 12,
    exampleWords: [
      { word: "詐欺", reading: "さぎ", meaning: "fraud, swindle, deception" },
      { word: "詐称", reading: "さしょう", meaning: "false claim, misrepresentation" },
    ],
  },
  {
    id: "n1-060",
    character: "叱",
    level: "N1",
    setIndex: 3,
    positionInSet: 0,
    onyomi: ["シツ"],
    kunyomi: ["しか.る"],
    meanings: ["scold", "rebuke", "reprimand"],
    strokeCount: 5,
    exampleWords: [
      { word: "叱る", reading: "しかる", meaning: "to scold, to chide" },
      { word: "叱責", reading: "しっせき", meaning: "reprimand, rebuke" },
    ],
  },
  {
    id: "n1-061",
    character: "嫉",
    level: "N1",
    setIndex: 3,
    positionInSet: 1,
    onyomi: ["シツ"],
    kunyomi: ["ねた.む", "そね.む"],
    meanings: ["jealousy", "envy", "be jealous of"],
    strokeCount: 13,
    exampleWords: [
      { word: "嫉妬", reading: "しっと", meaning: "jealousy, envy" },
    ],
  },
  {
    id: "n1-062",
    character: "執",
    level: "N1",
    setIndex: 3,
    positionInSet: 2,
    onyomi: ["シツ", "シュウ"],
    kunyomi: ["と.る"],
    meanings: ["tenacious", "insist on", "grasp", "execute"],
    strokeCount: 11,
    exampleWords: [
      { word: "執着", reading: "しゅうちゃく", meaning: "attachment, persistence" },
      { word: "執筆", reading: "しっぴつ", meaning: "writing, authorship" },
      { word: "執行", reading: "しっこう", meaning: "execution, enforcement" },
    ],
  },
  {
    id: "n1-063",
    character: "湿",
    level: "N1",
    setIndex: 3,
    positionInSet: 3,
    onyomi: ["シツ"],
    kunyomi: ["しめ.る", "しめ.す", "うるお.う"],
    meanings: ["damp", "wet", "moist"],
    strokeCount: 12,
    exampleWords: [
      { word: "湿気", reading: "しっけ", meaning: "moisture, dampness" },
      { word: "湿度", reading: "しつど", meaning: "humidity" },
      { word: "湿る", reading: "しめる", meaning: "to become damp, moist" },
    ],
  },
  {
    id: "n1-064",
    character: "縦",
    level: "N1",
    setIndex: 3,
    positionInSet: 4,
    onyomi: ["ジュウ"],
    kunyomi: ["たて"],
    meanings: ["vertical", "length", "up and down", "column"],
    strokeCount: 16,
    exampleWords: [
      { word: "縦", reading: "たて", meaning: "vertical, length, column" },
      { word: "縦横", reading: "じゅうおう", meaning: "length and breadth" },
      { word: "操縦", reading: "そうじゅう", meaning: "piloting, handling" },
    ],
  },
  {
    id: "n1-065",
    character: "需",
    level: "N1",
    setIndex: 3,
    positionInSet: 5,
    onyomi: ["ジュ"],
    kunyomi: [],
    meanings: ["demand", "need", "request"],
    strokeCount: 14,
    exampleWords: [
      { word: "需要", reading: "じゅよう", meaning: "demand, needs" },
      { word: "必需品", reading: "ひつじゅひん", meaning: "necessities" },
    ],
  },
  {
    id: "n1-066",
    character: "呪",
    level: "N1",
    setIndex: 3,
    positionInSet: 6,
    onyomi: ["ジュ", "シュ"],
    kunyomi: ["のろ.う", "まじな.う"],
    meanings: ["curse", "spell", "incantation"],
    strokeCount: 8,
    exampleWords: [
      { word: "呪い", reading: "のろい", meaning: "curse, hex" },
      { word: "呪縛", reading: "じゅばく", meaning: "spell, binding" },
    ],
  },
  {
    id: "n1-067",
    character: "淑",
    level: "N1",
    setIndex: 3,
    positionInSet: 7,
    onyomi: ["シュク"],
    kunyomi: ["しと.やか"],
    meanings: ["graceful", "gentle", "refined", "elegant (woman)"],
    strokeCount: 11,
    exampleWords: [
      { word: "淑女", reading: "しゅくじょ", meaning: "lady, gentlewoman" },
      { word: "貞淑", reading: "ていしゅく", meaning: "chastity, virtue" },
    ],
  },
  {
    id: "n1-068",
    character: "竣",
    level: "N1",
    setIndex: 3,
    positionInSet: 8,
    onyomi: ["シュン"],
    kunyomi: [],
    meanings: ["complete", "finish construction"],
    strokeCount: 12,
    exampleWords: [
      { word: "竣工", reading: "しゅんこう", meaning: "completion of construction" },
      { word: "竣成", reading: "しゅんせい", meaning: "completion" },
    ],
  },
  {
    id: "n1-069",
    character: "准",
    level: "N1",
    setIndex: 3,
    positionInSet: 9,
    onyomi: ["ジュン"],
    kunyomi: [],
    meanings: ["quasi-", "semi-", "associate"],
    strokeCount: 10,
    exampleWords: [
      { word: "准看護師", reading: "じゅんかんごし", meaning: "licensed practical nurse" },
      { word: "准教授", reading: "じゅんきょうじゅ", meaning: "associate professor" },
    ],
  },
  {
    id: "n1-070",
    character: "循",
    level: "N1",
    setIndex: 3,
    positionInSet: 10,
    onyomi: ["ジュン"],
    kunyomi: [],
    meanings: ["sequential", "follow", "circulate"],
    strokeCount: 12,
    exampleWords: [
      { word: "循環", reading: "じゅんかん", meaning: "circulation, cycle" },
      { word: "悪循環", reading: "あくじゅんかん", meaning: "vicious cycle" },
    ],
  },
  {
    id: "n1-071",
    character: "旬",
    level: "N1",
    setIndex: 3,
    positionInSet: 11,
    onyomi: ["ジュン"],
    kunyomi: [],
    meanings: ["season (for fresh food)", "decade"],
    strokeCount: 6,
    exampleWords: [
      { word: "旬", reading: "しゅん", meaning: "season (of a food)" },
      { word: "旬の食材", reading: "しゅんのしょくざい", meaning: "seasonal ingredients" },
    ],
  },
  {
    id: "n1-072",
    character: "遵",
    level: "N1",
    setIndex: 3,
    positionInSet: 12,
    onyomi: ["ジュン"],
    kunyomi: [],
    meanings: ["obey", "comply", "follow"],
    strokeCount: 15,
    exampleWords: [
      { word: "遵守", reading: "じゅんしゅ", meaning: "compliance, observance" },
      { word: "遵法", reading: "じゅんぽう", meaning: "law observance" },
    ],
  },
  {
    id: "n1-073",
    character: "如",
    level: "N1",
    setIndex: 3,
    positionInSet: 13,
    onyomi: ["ジョ", "ニョ"],
    kunyomi: ["ごと.し"],
    meanings: ["likeness", "like", "if", "as if"],
    strokeCount: 6,
    exampleWords: [
      { word: "如何", reading: "いかが", meaning: "how, in what way" },
      { word: "突如", reading: "とつじょ", meaning: "suddenly, unexpectedly" },
    ],
  },
  {
    id: "n1-074",
    character: "徐",
    level: "N1",
    setIndex: 3,
    positionInSet: 14,
    onyomi: ["ジョ"],
    kunyomi: ["おもむ.ろに"],
    meanings: ["gradually", "slowly", "leisurely"],
    strokeCount: 10,
    exampleWords: [
      { word: "徐々に", reading: "じょじょに", meaning: "gradually, little by little" },
      { word: "徐行", reading: "じょこう", meaning: "slow speed, slow down" },
    ],
  },
  {
    id: "n1-075",
    character: "庶",
    level: "N1",
    setIndex: 3,
    positionInSet: 15,
    onyomi: ["ショ"],
    kunyomi: [],
    meanings: ["the masses", "common people", "illegitimate child"],
    strokeCount: 11,
    exampleWords: [
      { word: "庶民", reading: "しょみん", meaning: "the masses, common people" },
      { word: "庶務", reading: "しょむ", meaning: "general affairs" },
    ],
  },
  {
    id: "n1-076",
    character: "辱",
    level: "N1",
    setIndex: 3,
    positionInSet: 16,
    onyomi: ["ジョク"],
    kunyomi: ["はずかし.める"],
    meanings: ["embarrass", "humiliate", "shame", "disgrace"],
    strokeCount: 10,
    exampleWords: [
      { word: "屈辱", reading: "くつじょく", meaning: "humiliation, disgrace" },
      { word: "侮辱", reading: "ぶじょく", meaning: "insult, contempt" },
    ],
  },
  {
    id: "n1-077",
    character: "慎",
    level: "N1",
    setIndex: 3,
    positionInSet: 17,
    onyomi: ["シン"],
    kunyomi: ["つつし.む"],
    meanings: ["humility", "be careful", "discreet", "prudent"],
    strokeCount: 13,
    exampleWords: [
      { word: "慎む", reading: "つつしむ", meaning: "to be careful, to behave modestly" },
      { word: "慎重", reading: "しんちょう", meaning: "careful, cautious" },
      { word: "謹慎", reading: "きんしん", meaning: "confinement, house arrest" },
    ],
  },
  {
    id: "n1-078",
    character: "逝",
    level: "N1",
    setIndex: 3,
    positionInSet: 18,
    onyomi: ["セイ"],
    kunyomi: ["い.く", "ゆ.く"],
    meanings: ["pass away", "die", "leave"],
    strokeCount: 10,
    exampleWords: [
      { word: "逝去", reading: "せいきょ", meaning: "death, passing away" },
      { word: "急逝", reading: "きゅうせい", meaning: "sudden death" },
    ],
  },
  {
    id: "n1-079",
    character: "誓",
    level: "N1",
    setIndex: 3,
    positionInSet: 19,
    onyomi: ["セイ"],
    kunyomi: ["ちか.う"],
    meanings: ["swear", "vow", "pledge"],
    strokeCount: 14,
    exampleWords: [
      { word: "誓う", reading: "ちかう", meaning: "to vow, to swear" },
      { word: "宣誓", reading: "せんせい", meaning: "oath, pledge" },
      { word: "誓約", reading: "せいやく", meaning: "pledge, oath" },
    ],
  },
  {
    id: "n1-080",
    character: "析",
    level: "N1",
    setIndex: 4,
    positionInSet: 0,
    onyomi: ["セキ"],
    kunyomi: [],
    meanings: ["divide", "separate", "analyze"],
    strokeCount: 8,
    exampleWords: [
      { word: "分析", reading: "ぶんせき", meaning: "analysis" },
      { word: "解析", reading: "かいせき", meaning: "analysis, parsing" },
    ],
  },
  {
    id: "n1-081",
    character: "拙",
    level: "N1",
    setIndex: 4,
    positionInSet: 1,
    onyomi: ["セツ"],
    kunyomi: ["つた.ない"],
    meanings: ["unskillful", "clumsy", "poor", "awkward"],
    strokeCount: 8,
    exampleWords: [
      { word: "拙い", reading: "つたない", meaning: "poor, unskillful" },
      { word: "拙速", reading: "せっそく", meaning: "speed over quality, hasty" },
      { word: "稚拙", reading: "ちせつ", meaning: "childish, immature" },
    ],
  },
  {
    id: "n1-082",
    character: "絶",
    level: "N1",
    setIndex: 4,
    positionInSet: 2,
    onyomi: ["ゼツ"],
    kunyomi: ["た.える", "た.やす", "た.つ"],
    meanings: ["discontinue", "cut off", "sever", "extinct"],
    strokeCount: 12,
    exampleWords: [
      { word: "絶対", reading: "ぜったい", meaning: "absolute, unconditional" },
      { word: "絶える", reading: "たえる", meaning: "to cease, to die out" },
      { word: "絶望", reading: "ぜつぼう", meaning: "despair, hopelessness" },
    ],
  },
  {
    id: "n1-083",
    character: "僧",
    level: "N1",
    setIndex: 4,
    positionInSet: 3,
    onyomi: ["ソウ"],
    kunyomi: [],
    meanings: ["Buddhist priest", "monk"],
    strokeCount: 13,
    exampleWords: [
      { word: "僧侶", reading: "そうりょ", meaning: "Buddhist priest, monk" },
      { word: "高僧", reading: "こうそう", meaning: "high priest" },
      { word: "僧院", reading: "そういん", meaning: "monastery" },
    ],
  },
  {
    id: "n1-084",
    character: "促",
    level: "N1",
    setIndex: 4,
    positionInSet: 4,
    onyomi: ["ソク"],
    kunyomi: ["うなが.す"],
    meanings: ["urge", "promote", "spur on"],
    strokeCount: 9,
    exampleWords: [
      { word: "促進", reading: "そくしん", meaning: "promotion, acceleration" },
      { word: "催促", reading: "さいそく", meaning: "urging, reminder" },
      { word: "促す", reading: "うながす", meaning: "to urge, to spur on" },
    ],
  },
  {
    id: "n1-085",
    character: "濁",
    level: "N1",
    setIndex: 4,
    positionInSet: 5,
    onyomi: ["ダク"],
    kunyomi: ["にご.る", "にご.す"],
    meanings: ["muddy", "be turbid", "murky"],
    strokeCount: 16,
    exampleWords: [
      { word: "濁る", reading: "にごる", meaning: "to become muddy, turbid" },
      { word: "汚濁", reading: "おだく", meaning: "pollution, contamination" },
      { word: "濁音", reading: "だくおん", meaning: "voiced consonant" },
    ],
  },
  {
    id: "n1-086",
    character: "嘆",
    level: "N1",
    setIndex: 4,
    positionInSet: 6,
    onyomi: ["タン"],
    kunyomi: ["なげ.く", "なげ.かわしい"],
    meanings: ["sigh", "lament", "moan", "grieve"],
    strokeCount: 13,
    exampleWords: [
      { word: "嘆く", reading: "なげく", meaning: "to lament, to grieve" },
      { word: "悲嘆", reading: "ひたん", meaning: "grief, lamentation" },
      { word: "嘆願", reading: "たんがん", meaning: "petition, appeal" },
    ],
  },
  {
    id: "n1-087",
    character: "緻",
    level: "N1",
    setIndex: 4,
    positionInSet: 7,
    onyomi: ["チ"],
    kunyomi: [],
    meanings: ["fine", "dense", "minute", "precise"],
    strokeCount: 16,
    exampleWords: [
      { word: "精緻", reading: "せいち", meaning: "exquisite, elaborate" },
      { word: "緻密", reading: "ちみつ", meaning: "precise, detailed, careful" },
    ],
  },
  {
    id: "n1-088",
    character: "窒",
    level: "N1",
    setIndex: 4,
    positionInSet: 8,
    onyomi: ["チツ"],
    kunyomi: [],
    meanings: ["plug up", "suffocate", "nitrogen"],
    strokeCount: 11,
    exampleWords: [
      { word: "窒素", reading: "ちっそ", meaning: "nitrogen" },
      { word: "窒息", reading: "ちっそく", meaning: "suffocation, asphyxia" },
    ],
  },
  {
    id: "n1-089",
    character: "仲",
    level: "N1",
    setIndex: 4,
    positionInSet: 9,
    onyomi: ["チュウ"],
    kunyomi: ["なか"],
    meanings: ["go-between", "relationship", "mediate"],
    strokeCount: 6,
    exampleWords: [
      { word: "仲間", reading: "なかま", meaning: "companion, fellow, group" },
      { word: "仲良し", reading: "なかよし", meaning: "good friends, close friends" },
      { word: "仲介", reading: "ちゅうかい", meaning: "mediation, intermediation" },
    ],
  },
  {
    id: "n1-090",
    character: "弔",
    level: "N1",
    setIndex: 4,
    positionInSet: 10,
    onyomi: ["チョウ"],
    kunyomi: ["とむら.う"],
    meanings: ["condolence", "mourn", "grieve"],
    strokeCount: 4,
    exampleWords: [
      { word: "弔問", reading: "ちょうもん", meaning: "condolence visit" },
      { word: "弔い", reading: "とむらい", meaning: "condolences, mourning" },
    ],
  },
  {
    id: "n1-091",
    character: "彫",
    level: "N1",
    setIndex: 4,
    positionInSet: 11,
    onyomi: ["チョウ"],
    kunyomi: ["ほ.る"],
    meanings: ["carve", "engrave", "sculpt"],
    strokeCount: 11,
    exampleWords: [
      { word: "彫刻", reading: "ちょうこく", meaning: "carving, engraving, sculpture" },
      { word: "彫る", reading: "ほる", meaning: "to carve, to engrave" },
      { word: "木彫り", reading: "きぼり", meaning: "woodcarving" },
    ],
  },
  {
    id: "n1-092",
    character: "跳",
    level: "N1",
    setIndex: 4,
    positionInSet: 12,
    onyomi: ["チョウ"],
    kunyomi: ["と.ぶ", "は.ねる"],
    meanings: ["leap", "jump", "spring", "bounce"],
    strokeCount: 13,
    exampleWords: [
      { word: "跳ぶ", reading: "とぶ", meaning: "to jump, to leap" },
      { word: "跳ね", reading: "はね", meaning: "jump, leap" },
      { word: "跳躍", reading: "ちょうやく", meaning: "leap, jump" },
    ],
  },
  {
    id: "n1-093",
    character: "勅",
    level: "N1",
    setIndex: 4,
    positionInSet: 13,
    onyomi: ["チョク"],
    kunyomi: [],
    meanings: ["imperial edict", "imperial decree"],
    strokeCount: 9,
    exampleWords: [
      { word: "勅語", reading: "ちょくご", meaning: "imperial rescript" },
      { word: "勅命", reading: "ちょくめい", meaning: "imperial order" },
    ],
  },
  {
    id: "n1-094",
    character: "鎮",
    level: "N1",
    setIndex: 4,
    positionInSet: 14,
    onyomi: ["チン"],
    kunyomi: ["しず.める", "しず.まる", "おさ.える"],
    meanings: ["tranquilize", "subdue", "suppress", "calm"],
    strokeCount: 18,
    exampleWords: [
      { word: "鎮静", reading: "ちんせい", meaning: "calming, sedation" },
      { word: "鎮圧", reading: "ちんあつ", meaning: "suppression, quelling" },
      { word: "鎮める", reading: "しずめる", meaning: "to calm, to suppress" },
    ],
  },
  {
    id: "n1-095",
    character: "鈍",
    level: "N1",
    setIndex: 4,
    positionInSet: 15,
    onyomi: ["ドン"],
    kunyomi: ["にぶ.い", "にぶ.る", "なま.る"],
    meanings: ["dull", "blunt", "slow", "dim"],
    strokeCount: 12,
    exampleWords: [
      { word: "鈍い", reading: "にぶい", meaning: "dull, blunt, slow" },
      { word: "鈍感", reading: "どんかん", meaning: "dull, insensitive" },
      { word: "鈍器", reading: "どんき", meaning: "blunt instrument" },
    ],
  },
  {
    id: "n1-096",
    character: "軟",
    level: "N1",
    setIndex: 4,
    positionInSet: 16,
    onyomi: ["ナン"],
    kunyomi: ["やわ.らか", "やわ.らかい"],
    meanings: ["soft", "tender", "flexible", "mild"],
    strokeCount: 11,
    exampleWords: [
      { word: "軟らか", reading: "やわらか", meaning: "soft, flexible" },
      { word: "軟化", reading: "なんか", meaning: "softening" },
      { word: "軟弱", reading: "なんじゃく", meaning: "weak, feeble" },
    ],
  },
  {
    id: "n1-097",
    character: "尼",
    level: "N1",
    setIndex: 4,
    positionInSet: 17,
    onyomi: ["ニ"],
    kunyomi: ["あま"],
    meanings: ["nun", "Buddhist nun"],
    strokeCount: 5,
    exampleWords: [
      { word: "尼", reading: "あま", meaning: "nun" },
      { word: "尼僧", reading: "にそう", meaning: "Buddhist nun" },
    ],
  },
  {
    id: "n1-098",
    character: "妊",
    level: "N1",
    setIndex: 4,
    positionInSet: 18,
    onyomi: ["ニン"],
    kunyomi: ["はら.む"],
    meanings: ["pregnancy", "be pregnant"],
    strokeCount: 7,
    exampleWords: [
      { word: "妊娠", reading: "にんしん", meaning: "pregnancy" },
      { word: "妊婦", reading: "にんぷ", meaning: "pregnant woman" },
    ],
  },
  {
    id: "n1-099",
    character: "粘",
    level: "N1",
    setIndex: 4,
    positionInSet: 19,
    onyomi: ["ネン"],
    kunyomi: ["ねば.る"],
    meanings: ["sticky", "glutinous", "persevere", "tenacious"],
    strokeCount: 11,
    exampleWords: [
      { word: "粘る", reading: "ねばる", meaning: "to be sticky, to persevere" },
      { word: "粘土", reading: "ねんど", meaning: "clay" },
      { word: "粘着", reading: "ねんちゃく", meaning: "adhesion, sticking" },
    ],
  },
  {
    id: "n1-100",
    character: "覇",
    level: "N1",
    setIndex: 5,
    positionInSet: 0,
    onyomi: ["ハ"],
    kunyomi: [],
    meanings: ["hegemony", "supremacy", "championship"],
    strokeCount: 19,
    exampleWords: [
      { word: "覇権", reading: "はけん", meaning: "hegemony, supremacy" },
      { word: "制覇", reading: "せいは", meaning: "conquest, championship" },
      { word: "覇者", reading: "はしゃ", meaning: "champion, conqueror" },
    ],
  },
  {
    id: "n1-101",
    character: "廃",
    level: "N1",
    setIndex: 5,
    positionInSet: 1,
    onyomi: ["ハイ"],
    kunyomi: ["すた.れる", "すた.る"],
    meanings: ["abolish", "cessation", "obsolete"],
    strokeCount: 12,
    exampleWords: [
      { word: "廃止", reading: "はいし", meaning: "abolition, discontinuation" },
      { word: "廃墟", reading: "はいきょ", meaning: "ruins, abandoned place" },
      { word: "廃棄", reading: "はいき", meaning: "disposal, abandonment" },
    ],
  },
  {
    id: "n1-102",
    character: "排",
    level: "N1",
    setIndex: 5,
    positionInSet: 2,
    onyomi: ["ハイ"],
    kunyomi: ["おし.のける"],
    meanings: ["reject", "expel", "arrange", "align"],
    strokeCount: 11,
    exampleWords: [
      { word: "排除", reading: "はいじょ", meaning: "exclusion, elimination" },
      { word: "排出", reading: "はいしゅつ", meaning: "discharge, emission" },
      { word: "排水", reading: "はいすい", meaning: "drainage" },
    ],
  },
  {
    id: "n1-103",
    character: "陪",
    level: "N1",
    setIndex: 5,
    positionInSet: 3,
    onyomi: ["バイ"],
    kunyomi: [],
    meanings: ["accompany", "attend on", "be subordinate"],
    strokeCount: 11,
    exampleWords: [
      { word: "陪審", reading: "ばいしん", meaning: "jury" },
      { word: "陪席", reading: "ばいせき", meaning: "attending a session" },
    ],
  },
  {
    id: "n1-104",
    character: "泊",
    level: "N1",
    setIndex: 5,
    positionInSet: 4,
    onyomi: ["ハク"],
    kunyomi: ["と.まる", "と.める"],
    meanings: ["overnight stay", "lodge", "anchor"],
    strokeCount: 8,
    exampleWords: [
      { word: "宿泊", reading: "しゅくはく", meaning: "accommodation, lodging" },
      { word: "泊まる", reading: "とまる", meaning: "to stay overnight" },
      { word: "外泊", reading: "がいはく", meaning: "staying out overnight" },
    ],
  },
  {
    id: "n1-105",
    character: "縛",
    level: "N1",
    setIndex: 5,
    positionInSet: 5,
    onyomi: ["バク"],
    kunyomi: ["しば.る"],
    meanings: ["truss", "bind", "tie", "restrain"],
    strokeCount: 16,
    exampleWords: [
      { word: "縛る", reading: "しばる", meaning: "to bind, to tie" },
      { word: "束縛", reading: "そくばく", meaning: "restraint, shackle" },
      { word: "自縛", reading: "じばく", meaning: "self-imposed restriction" },
    ],
  },
  {
    id: "n1-106",
    character: "罰",
    level: "N1",
    setIndex: 5,
    positionInSet: 6,
    onyomi: ["バツ", "バチ", "ハツ"],
    kunyomi: ["ばっ.する"],
    meanings: ["penalty", "punishment", "judgement"],
    strokeCount: 14,
    exampleWords: [
      { word: "罰則", reading: "ばっそく", meaning: "penal regulations, penalties" },
      { word: "処罰", reading: "しょばつ", meaning: "punishment, penalization" },
      { word: "懲罰", reading: "ちょうばつ", meaning: "punishment, discipline" },
    ],
  },
  {
    id: "n1-107",
    character: "繁",
    level: "N1",
    setIndex: 5,
    positionInSet: 7,
    onyomi: ["ハン"],
    kunyomi: ["しげ.る"],
    meanings: ["luxuriant", "thick", "overgrown", "frequent"],
    strokeCount: 16,
    exampleWords: [
      { word: "繁栄", reading: "はんえい", meaning: "prosperity, flourishing" },
      { word: "繁殖", reading: "はんしょく", meaning: "breeding, propagation" },
      { word: "繁盛", reading: "はんじょう", meaning: "prosperity, thriving" },
    ],
  },
  {
    id: "n1-108",
    character: "藩",
    level: "N1",
    setIndex: 5,
    positionInSet: 8,
    onyomi: ["ハン"],
    kunyomi: [],
    meanings: ["feudal domain", "clan", "han"],
    strokeCount: 18,
    exampleWords: [
      { word: "藩", reading: "はん", meaning: "feudal domain, han" },
      { word: "藩主", reading: "はんしゅ", meaning: "feudal lord, daimyo" },
      { word: "廃藩", reading: "はいはん", meaning: "abolition of feudal domains" },
    ],
  },
  {
    id: "n1-109",
    character: "卑",
    level: "N1",
    setIndex: 5,
    positionInSet: 9,
    onyomi: ["ヒ"],
    kunyomi: ["いや.しい", "いや.しむ", "いや.しめる"],
    meanings: ["lowly", "base", "vulgar", "humble"],
    strokeCount: 8,
    exampleWords: [
      { word: "卑劣", reading: "ひれつ", meaning: "despicable, mean, cowardly" },
      { word: "卑怯", reading: "ひきょう", meaning: "cowardly, sneaky" },
      { word: "低卑", reading: "ていひ", meaning: "low and base" },
    ],
  },
  {
    id: "n1-110",
    character: "庇",
    level: "N1",
    setIndex: 5,
    positionInSet: 10,
    onyomi: ["ヒ"],
    kunyomi: ["ひさし", "かば.う"],
    meanings: ["protect", "defend", "patronize", "eaves"],
    strokeCount: 8,
    exampleWords: [
      { word: "庇護", reading: "ひご", meaning: "protection, patronage" },
      { word: "庇う", reading: "かばう", meaning: "to protect, to defend" },
    ],
  },
  {
    id: "n1-111",
    character: "漂",
    level: "N1",
    setIndex: 5,
    positionInSet: 11,
    onyomi: ["ヒョウ"],
    kunyomi: ["ただよ.う"],
    meanings: ["drift", "float", "wander"],
    strokeCount: 14,
    exampleWords: [
      { word: "漂う", reading: "ただよう", meaning: "to drift, to float" },
      { word: "漂流", reading: "ひょうりゅう", meaning: "drifting, adrift" },
      { word: "漂白", reading: "ひょうはく", meaning: "bleaching" },
    ],
  },
  {
    id: "n1-112",
    character: "拍",
    level: "N1",
    setIndex: 5,
    positionInSet: 12,
    onyomi: ["ハク", "ヒョウ"],
    kunyomi: ["う.つ"],
    meanings: ["clap", "beat time", "pat"],
    strokeCount: 8,
    exampleWords: [
      { word: "拍手", reading: "はくしゅ", meaning: "applause, clapping" },
      { word: "拍子", reading: "ひょうし", meaning: "beat, rhythm, tempo" },
      { word: "鼓動", reading: "こどう", meaning: "beat, pulse, throb" },
    ],
  },
  {
    id: "n1-113",
    character: "膨",
    level: "N1",
    setIndex: 5,
    positionInSet: 13,
    onyomi: ["ボウ"],
    kunyomi: ["ふく.らむ", "ふく.れる"],
    meanings: ["swell", "expand", "inflate"],
    strokeCount: 16,
    exampleWords: [
      { word: "膨らむ", reading: "ふくらむ", meaning: "to swell, to expand" },
      { word: "膨張", reading: "ぼうちょう", meaning: "expansion, inflation" },
      { word: "膨大", reading: "ぼうだい", meaning: "enormous, vast" },
    ],
  },
  {
    id: "n1-114",
    character: "翻",
    level: "N1",
    setIndex: 5,
    positionInSet: 14,
    onyomi: ["ホン"],
    kunyomi: ["ひるが.える", "ひるが.えす"],
    meanings: ["flip", "turn over", "wave", "flutter", "translate"],
    strokeCount: 18,
    exampleWords: [
      { word: "翻訳", reading: "ほんやく", meaning: "translation" },
      { word: "翻す", reading: "ひるがえす", meaning: "to turn over, to overturn" },
      { word: "翻弄", reading: "ほんろう", meaning: "toying with, playing around" },
    ],
  },
  {
    id: "n1-115",
    character: "慢",
    level: "N1",
    setIndex: 5,
    positionInSet: 15,
    onyomi: ["マン"],
    kunyomi: [],
    meanings: ["ridicule", "arrogance", "slow", "inattentive"],
    strokeCount: 14,
    exampleWords: [
      { word: "自慢", reading: "じまん", meaning: "pride, boast" },
      { word: "傲慢", reading: "ごうまん", meaning: "arrogance, haughtiness" },
      { word: "慢性", reading: "まんせい", meaning: "chronic, long-standing" },
    ],
  },
  {
    id: "n1-116",
    character: "魅",
    level: "N1",
    setIndex: 5,
    positionInSet: 16,
    onyomi: ["ミ"],
    kunyomi: [],
    meanings: ["fascinate", "charm", "bewitch", "goblin"],
    strokeCount: 15,
    exampleWords: [
      { word: "魅力", reading: "みりょく", meaning: "attraction, charm" },
      { word: "魅了", reading: "みりょう", meaning: "fascination, captivation" },
      { word: "魅惑", reading: "みわく", meaning: "fascination, temptation" },
    ],
  },
  {
    id: "n1-117",
    character: "妙",
    level: "N1",
    setIndex: 5,
    positionInSet: 17,
    onyomi: ["ミョウ"],
    kunyomi: ["たえ"],
    meanings: ["strange", "odd", "curious", "queer", "exquisite"],
    strokeCount: 7,
    exampleWords: [
      { word: "妙", reading: "みょう", meaning: "strange, odd" },
      { word: "奇妙", reading: "きみょう", meaning: "strange, mysterious, odd" },
      { word: "絶妙", reading: "ぜつみょう", meaning: "exquisite, superb" },
    ],
  },
  {
    id: "n1-118",
    character: "猛",
    level: "N1",
    setIndex: 5,
    positionInSet: 18,
    onyomi: ["モウ"],
    kunyomi: ["たけ.し"],
    meanings: ["fierce", "wild", "violent", "brave"],
    strokeCount: 11,
    exampleWords: [
      { word: "猛烈", reading: "もうれつ", meaning: "fierce, intense, violent" },
      { word: "猛獣", reading: "もうじゅう", meaning: "fierce animal" },
      { word: "猛暑", reading: "もうしょ", meaning: "intense heat" },
    ],
  },
  {
    id: "n1-119",
    character: "紋",
    level: "N1",
    setIndex: 5,
    positionInSet: 19,
    onyomi: ["モン"],
    kunyomi: [],
    meanings: ["family crest", "pattern", "design"],
    strokeCount: 10,
    exampleWords: [
      { word: "家紋", reading: "かもん", meaning: "family crest" },
      { word: "指紋", reading: "しもん", meaning: "fingerprint" },
      { word: "紋章", reading: "もんしょう", meaning: "coat of arms, emblem" },
    ],
  },
  {
    id: "n1-120",
    character: "唯",
    level: "N1",
    setIndex: 6,
    positionInSet: 0,
    onyomi: ["ユイ", "イ"],
    kunyomi: ["ただ"],
    meanings: ["solely", "only", "merely", "nothing but"],
    strokeCount: 11,
    exampleWords: [
      { word: "唯一", reading: "ゆいいつ", meaning: "the only one, sole" },
      { word: "唯物論", reading: "ゆいぶつろん", meaning: "materialism" },
    ],
  },
  {
    id: "n1-121",
    character: "羅",
    level: "N1",
    setIndex: 6,
    positionInSet: 1,
    onyomi: ["ラ"],
    kunyomi: [],
    meanings: ["silk gauze", "arrange", "enumerate"],
    strokeCount: 19,
    exampleWords: [
      { word: "羅列", reading: "られつ", meaning: "enumeration, list" },
      { word: "網羅", reading: "もうら", meaning: "encompassing, comprehensive" },
    ],
  },
  {
    id: "n1-122",
    character: "裸",
    level: "N1",
    setIndex: 6,
    positionInSet: 2,
    onyomi: ["ラ"],
    kunyomi: ["はだか"],
    meanings: ["naked", "nude", "bare"],
    strokeCount: 13,
    exampleWords: [
      { word: "裸", reading: "はだか", meaning: "naked, nude, bare" },
      { word: "裸足", reading: "はだし", meaning: "barefoot" },
      { word: "丸裸", reading: "まるはだか", meaning: "stark naked, completely bare" },
    ],
  },
  {
    id: "n1-123",
    character: "濫",
    level: "N1",
    setIndex: 6,
    positionInSet: 3,
    onyomi: ["ラン"],
    kunyomi: ["みだ.りに"],
    meanings: ["overflow", "excessive", "diffuse"],
    strokeCount: 18,
    exampleWords: [
      { word: "濫用", reading: "らんよう", meaning: "misuse, abuse" },
      { word: "氾濫", reading: "はんらん", meaning: "flood, overflow" },
    ],
  },
  {
    id: "n1-124",
    character: "履",
    level: "N1",
    setIndex: 6,
    positionInSet: 4,
    onyomi: ["リ"],
    kunyomi: ["は.く"],
    meanings: ["step on", "walk in", "put on (shoes)", "footwear"],
    strokeCount: 15,
    exampleWords: [
      { word: "履く", reading: "はく", meaning: "to put on (footwear)" },
      { word: "履歴", reading: "りれき", meaning: "personal history, resume" },
      { word: "草履", reading: "ぞうり", meaning: "sandals, zori" },
    ],
  },
  {
    id: "n1-125",
    character: "略",
    level: "N1",
    setIndex: 6,
    positionInSet: 5,
    onyomi: ["リャク"],
    kunyomi: ["おさ.める", "はかりごと"],
    meanings: ["abbreviation", "omission", "summary", "strategy"],
    strokeCount: 11,
    exampleWords: [
      { word: "略語", reading: "りゃくご", meaning: "abbreviation, acronym" },
      { word: "戦略", reading: "せんりゃく", meaning: "strategy, tactics" },
      { word: "省略", reading: "しょうりゃく", meaning: "abbreviation, omission" },
    ],
  },
  {
    id: "n1-126",
    character: "倫",
    level: "N1",
    setIndex: 6,
    positionInSet: 6,
    onyomi: ["リン"],
    kunyomi: [],
    meanings: ["ethics", "morality", "companions"],
    strokeCount: 10,
    exampleWords: [
      { word: "倫理", reading: "りんり", meaning: "ethics, morality" },
      { word: "人倫", reading: "じんりん", meaning: "human relations, morality" },
    ],
  },
  {
    id: "n1-127",
    character: "隆",
    level: "N1",
    setIndex: 6,
    positionInSet: 7,
    onyomi: ["リュウ"],
    kunyomi: ["たか.い"],
    meanings: ["prosperous", "noble", "bulge", "high"],
    strokeCount: 11,
    exampleWords: [
      { word: "隆盛", reading: "りゅうせい", meaning: "prosperity, flourishing" },
      { word: "興隆", reading: "こうりゅう", meaning: "rise, prosperity" },
    ],
  },
  {
    id: "n1-128",
    character: "霊",
    level: "N1",
    setIndex: 6,
    positionInSet: 8,
    onyomi: ["レイ", "リョウ"],
    kunyomi: ["たま"],
    meanings: ["soul", "spirit", "ghost", "supernatural"],
    strokeCount: 15,
    exampleWords: [
      { word: "霊魂", reading: "れいこん", meaning: "soul, spirit" },
      { word: "幽霊", reading: "ゆうれい", meaning: "ghost, specter" },
      { word: "霊的", reading: "れいてき", meaning: "spiritual, ghostly" },
    ],
  },
];
