import type { Kanji } from "./types";

export const N2_KANJI: Kanji[] = [
  {
    id: "n2-000",
    character: "監",
    level: "N2",
    setIndex: 0,
    positionInSet: 0,
    onyomi: ["カン"],
    kunyomi: [],
    meanings: ["oversee", "supervise", "watch", "observe"],
    strokeCount: 15,
    exampleWords: [
      { word: "監督", reading: "かんとく", meaning: "supervision, director" },
      { word: "監視", reading: "かんし", meaning: "observation, surveillance" },
      { word: "監査", reading: "かんさ", meaning: "inspection, audit" },
    ],
  },
  {
    id: "n2-001",
    character: "握",
    level: "N2",
    setIndex: 0,
    positionInSet: 1,
    onyomi: ["アク"],
    kunyomi: ["にぎ.る"],
    meanings: ["grip", "grasp", "hold", "clench"],
    strokeCount: 12,
    exampleWords: [
      { word: "握る", reading: "にぎる", meaning: "to grasp, to hold" },
      { word: "握手", reading: "あくしゅ", meaning: "handshake" },
      { word: "把握", reading: "はあく", meaning: "grasp, understanding" },
    ],
  },
  {
    id: "n2-002",
    character: "扱",
    level: "N2",
    setIndex: 0,
    positionInSet: 2,
    onyomi: [],
    kunyomi: ["あつか.う", "あつか.い"],
    meanings: ["handle", "deal with", "treat"],
    strokeCount: 6,
    exampleWords: [
      { word: "扱う", reading: "あつかう", meaning: "to handle, to deal with" },
      { word: "取り扱い", reading: "とりあつかい", meaning: "handling, treatment" },
      { word: "扱い方", reading: "あつかいかた", meaning: "how to handle" },
    ],
  },
  {
    id: "n2-003",
    character: "維",
    level: "N2",
    setIndex: 0,
    positionInSet: 3,
    onyomi: ["イ"],
    kunyomi: [],
    meanings: ["fiber", "maintain", "preserve"],
    strokeCount: 14,
    exampleWords: [
      { word: "維持", reading: "いじ", meaning: "maintenance, preservation" },
      { word: "繊維", reading: "せんい", meaning: "fiber, textile" },
      { word: "維新", reading: "いしん", meaning: "restoration, revolution" },
    ],
  },
  {
    id: "n2-004",
    character: "違",
    level: "N2",
    setIndex: 0,
    positionInSet: 4,
    onyomi: ["イ"],
    kunyomi: ["ちが.う", "ちが.える"],
    meanings: ["differ", "wrong", "mistake", "change"],
    strokeCount: 13,
    exampleWords: [
      { word: "違う", reading: "ちがう", meaning: "to differ, to be wrong" },
      { word: "違反", reading: "いはん", meaning: "violation, infringement" },
      { word: "間違い", reading: "まちがい", meaning: "mistake, error" },
    ],
  },
  {
    id: "n2-005",
    character: "隔",
    level: "N2",
    setIndex: 0,
    positionInSet: 5,
    onyomi: ["カク"],
    kunyomi: ["へだ.てる", "へだ.たる"],
    meanings: ["isolate", "separate", "partition", "distance"],
    strokeCount: 13,
    exampleWords: [
      { word: "隔離", reading: "かくり", meaning: "isolation, quarantine" },
      { word: "隔週", reading: "かくしゅう", meaning: "every other week" },
      { word: "間隔", reading: "かんかく", meaning: "interval, spacing" },
    ],
  },
  {
    id: "n2-006",
    character: "拡",
    level: "N2",
    setIndex: 0,
    positionInSet: 6,
    onyomi: ["カク"],
    kunyomi: ["ひろ.げる", "ひろ.がる"],
    meanings: ["broaden", "expand", "extend", "enlarge"],
    strokeCount: 8,
    exampleWords: [
      { word: "拡大", reading: "かくだい", meaning: "expansion, enlargement" },
      { word: "拡張", reading: "かくちょう", meaning: "expansion, extension" },
      { word: "拡散", reading: "かくさん", meaning: "spread, diffusion" },
    ],
  },
  {
    id: "n2-007",
    character: "革",
    level: "N2",
    setIndex: 0,
    positionInSet: 7,
    onyomi: ["カク"],
    kunyomi: ["かわ"],
    meanings: ["leather", "reform", "change", "revolution"],
    strokeCount: 9,
    exampleWords: [
      { word: "革命", reading: "かくめい", meaning: "revolution" },
      { word: "改革", reading: "かいかく", meaning: "reform, change" },
      { word: "革新", reading: "かくしん", meaning: "innovation, reform" },
    ],
  },
  {
    id: "n2-008",
    character: "看",
    level: "N2",
    setIndex: 0,
    positionInSet: 8,
    onyomi: ["カン"],
    kunyomi: [],
    meanings: ["watch over", "look after", "observe"],
    strokeCount: 9,
    exampleWords: [
      { word: "看護", reading: "かんご", meaning: "nursing, care" },
      { word: "看板", reading: "かんばん", meaning: "signboard, billboard" },
      { word: "看病", reading: "かんびょう", meaning: "nursing, attending to the sick" },
    ],
  },
  {
    id: "n2-009",
    character: "環",
    level: "N2",
    setIndex: 0,
    positionInSet: 9,
    onyomi: ["カン"],
    kunyomi: ["たまき"],
    meanings: ["ring", "circle", "link", "loop"],
    strokeCount: 17,
    exampleWords: [
      { word: "環境", reading: "かんきょう", meaning: "environment" },
      { word: "循環", reading: "じゅんかん", meaning: "circulation, cycle" },
      { word: "環状", reading: "かんじょう", meaning: "circular, ring-shaped" },
    ],
  },
  {
    id: "n2-010",
    character: "寛",
    level: "N2",
    setIndex: 0,
    positionInSet: 10,
    onyomi: ["カン"],
    kunyomi: ["くつろ.ぐ", "ひろ.い"],
    meanings: ["tolerant", "easy-going", "lenient", "relax"],
    strokeCount: 13,
    exampleWords: [
      { word: "寛大", reading: "かんだい", meaning: "generous, lenient" },
      { word: "寛容", reading: "かんよう", meaning: "tolerance, leniency" },
      { word: "寛ぐ", reading: "くつろぐ", meaning: "to relax, to feel at ease" },
    ],
  },
  {
    id: "n2-011",
    character: "陥",
    level: "N2",
    setIndex: 0,
    positionInSet: 11,
    onyomi: ["カン"],
    kunyomi: ["おちい.る", "おとしい.れる"],
    meanings: ["fall into", "collapse", "cave in", "trap"],
    strokeCount: 10,
    exampleWords: [
      { word: "陥る", reading: "おちいる", meaning: "to fall into, to be trapped" },
      { word: "欠陥", reading: "けっかん", meaning: "defect, flaw" },
      { word: "陥落", reading: "かんらく", meaning: "fall, capture" },
    ],
  },
  {
    id: "n2-012",
    character: "企",
    level: "N2",
    setIndex: 0,
    positionInSet: 12,
    onyomi: ["キ"],
    kunyomi: ["くわだ.てる"],
    meanings: ["undertake", "plan", "scheme"],
    strokeCount: 6,
    exampleWords: [
      { word: "企業", reading: "きぎょう", meaning: "enterprise, company" },
      { word: "企画", reading: "きかく", meaning: "planning, project" },
      { word: "企てる", reading: "くわだてる", meaning: "to plan, to scheme" },
    ],
  },
  {
    id: "n2-013",
    character: "基",
    level: "N2",
    setIndex: 0,
    positionInSet: 13,
    onyomi: ["キ"],
    kunyomi: ["もと", "もとい"],
    meanings: ["fundamentals", "base", "foundation"],
    strokeCount: 11,
    exampleWords: [
      { word: "基本", reading: "きほん", meaning: "foundation, basis, standard" },
      { word: "基礎", reading: "きそ", meaning: "foundation, basis" },
      { word: "基準", reading: "きじゅん", meaning: "standard, criterion" },
    ],
  },
  {
    id: "n2-014",
    character: "飢",
    level: "N2",
    setIndex: 0,
    positionInSet: 14,
    onyomi: ["キ"],
    kunyomi: ["う.える"],
    meanings: ["hungry", "starve", "thirst for"],
    strokeCount: 10,
    exampleWords: [
      { word: "飢える", reading: "うえる", meaning: "to starve, to hunger" },
      { word: "飢饉", reading: "ききん", meaning: "famine, hunger" },
      { word: "飢餓", reading: "きが", meaning: "hunger, starvation" },
    ],
  },
  {
    id: "n2-015",
    character: "核",
    level: "N2",
    setIndex: 0,
    positionInSet: 15,
    onyomi: ["カク"],
    kunyomi: [],
    meanings: ["nucleus", "core", "kernel", "nuclear"],
    strokeCount: 10,
    exampleWords: [
      { word: "核心", reading: "かくしん", meaning: "core, heart, nucleus" },
      { word: "核兵器", reading: "かくへいき", meaning: "nuclear weapons" },
      { word: "核融合", reading: "かくゆうごう", meaning: "nuclear fusion" },
    ],
  },
  {
    id: "n2-016",
    character: "陰",
    level: "N2",
    setIndex: 0,
    positionInSet: 16,
    onyomi: ["イン"],
    kunyomi: ["かげ", "かげ.る"],
    meanings: ["shade", "shadow", "yin", "negative"],
    strokeCount: 11,
    exampleWords: [
      { word: "陰", reading: "かげ", meaning: "shade, shadow" },
      { word: "陰謀", reading: "いんぼう", meaning: "plot, conspiracy" },
      { word: "陰性", reading: "いんせい", meaning: "negative (test result)" },
    ],
  },
  {
    id: "n2-017",
    character: "影",
    level: "N2",
    setIndex: 0,
    positionInSet: 17,
    onyomi: ["エイ"],
    kunyomi: ["かげ"],
    meanings: ["shadow", "silhouette", "figure", "influence"],
    strokeCount: 15,
    exampleWords: [
      { word: "影響", reading: "えいきょう", meaning: "influence, effect" },
      { word: "影", reading: "かげ", meaning: "shadow, silhouette" },
      { word: "撮影", reading: "さつえい", meaning: "photography, filming" },
    ],
  },
  {
    id: "n2-018",
    character: "益",
    level: "N2",
    setIndex: 0,
    positionInSet: 18,
    onyomi: ["エキ", "ヤク"],
    kunyomi: ["ます"],
    meanings: ["benefit", "gain", "profit", "increase"],
    strokeCount: 10,
    exampleWords: [
      { word: "利益", reading: "りえき", meaning: "profit, benefit" },
      { word: "収益", reading: "しゅうえき", meaning: "earnings, profit" },
      { word: "有益", reading: "ゆうえき", meaning: "beneficial, profitable" },
    ],
  },
  {
    id: "n2-019",
    character: "越",
    level: "N2",
    setIndex: 0,
    positionInSet: 19,
    onyomi: ["エツ"],
    kunyomi: ["こ.える", "こ.す"],
    meanings: ["surpass", "cross over", "exceed", "go beyond"],
    strokeCount: 12,
    exampleWords: [
      { word: "越える", reading: "こえる", meaning: "to cross over, to exceed" },
      { word: "超越", reading: "ちょうえつ", meaning: "transcendence" },
      { word: "引越し", reading: "ひっこし", meaning: "moving (residence)" },
    ],
  },
  {
    id: "n2-020",
    character: "恩",
    level: "N2",
    setIndex: 1,
    positionInSet: 0,
    onyomi: ["オン"],
    kunyomi: [],
    meanings: ["grace", "kindness", "favor", "gratitude"],
    strokeCount: 10,
    exampleWords: [
      { word: "恩師", reading: "おんし", meaning: "one's teacher, mentor" },
      { word: "恩恵", reading: "おんけい", meaning: "favor, grace, benefit" },
      { word: "感恩", reading: "かんおん", meaning: "gratitude" },
    ],
  },
  {
    id: "n2-021",
    character: "解",
    level: "N2",
    setIndex: 1,
    positionInSet: 1,
    onyomi: ["カイ", "ゲ"],
    kunyomi: ["と.く", "と.かす", "と.ける", "ほど.く"],
    meanings: ["unravel", "solve", "understand", "release"],
    strokeCount: 13,
    exampleWords: [
      { word: "解決", reading: "かいけつ", meaning: "solution, resolution" },
      { word: "理解", reading: "りかい", meaning: "understanding, comprehension" },
      { word: "解説", reading: "かいせつ", meaning: "explanation, commentary" },
    ],
  },
  {
    id: "n2-022",
    character: "改",
    level: "N2",
    setIndex: 1,
    positionInSet: 2,
    onyomi: ["カイ"],
    kunyomi: ["あらた.める", "あらた.まる"],
    meanings: ["reformation", "change", "modify", "alter"],
    strokeCount: 7,
    exampleWords: [
      { word: "改善", reading: "かいぜん", meaning: "improvement, amelioration" },
      { word: "改革", reading: "かいかく", meaning: "reform, change" },
      { word: "改正", reading: "かいせい", meaning: "amendment, revision" },
    ],
  },
  {
    id: "n2-023",
    character: "価",
    level: "N2",
    setIndex: 1,
    positionInSet: 3,
    onyomi: ["カ"],
    kunyomi: ["あたい"],
    meanings: ["value", "price", "worth"],
    strokeCount: 8,
    exampleWords: [
      { word: "価値", reading: "かち", meaning: "value, worth" },
      { word: "物価", reading: "ぶっか", meaning: "commodity prices" },
      { word: "評価", reading: "ひょうか", meaning: "evaluation, assessment" },
    ],
  },
  {
    id: "n2-024",
    character: "介",
    level: "N2",
    setIndex: 1,
    positionInSet: 4,
    onyomi: ["カイ"],
    kunyomi: [],
    meanings: ["jammed in", "mediate", "shellfish", "go between"],
    strokeCount: 4,
    exampleWords: [
      { word: "紹介", reading: "しょうかい", meaning: "introduction" },
      { word: "介護", reading: "かいご", meaning: "nursing, caregiving" },
      { word: "媒介", reading: "ばいかい", meaning: "medium, intermediary" },
    ],
  },
  {
    id: "n2-025",
    character: "灰",
    level: "N2",
    setIndex: 1,
    positionInSet: 5,
    onyomi: ["カイ"],
    kunyomi: ["はい"],
    meanings: ["ashes", "grey"],
    strokeCount: 6,
    exampleWords: [
      { word: "灰色", reading: "はいいろ", meaning: "grey, gray" },
      { word: "灰", reading: "はい", meaning: "ash, ashes" },
      { word: "石灰", reading: "せっかい", meaning: "lime (calcium)" },
    ],
  },
  {
    id: "n2-026",
    character: "巻",
    level: "N2",
    setIndex: 1,
    positionInSet: 6,
    onyomi: ["カン"],
    kunyomi: ["ま.く", "ま.き"],
    meanings: ["scroll", "roll up", "wind", "coil", "volume"],
    strokeCount: 9,
    exampleWords: [
      { word: "巻く", reading: "まく", meaning: "to roll up, to wind" },
      { word: "第一巻", reading: "だいいっかん", meaning: "volume one" },
      { word: "巻き込む", reading: "まきこむ", meaning: "to involve, to get caught up in" },
    ],
  },
  {
    id: "n2-027",
    character: "乾",
    level: "N2",
    setIndex: 1,
    positionInSet: 7,
    onyomi: ["カン"],
    kunyomi: ["かわ.く", "かわ.かす"],
    meanings: ["dry", "arid", "parch"],
    strokeCount: 11,
    exampleWords: [
      { word: "乾燥", reading: "かんそう", meaning: "dryness, dehydration" },
      { word: "乾杯", reading: "かんぱい", meaning: "toast, cheers" },
      { word: "乾く", reading: "かわく", meaning: "to dry, to become dry" },
    ],
  },
  {
    id: "n2-028",
    character: "慣",
    level: "N2",
    setIndex: 1,
    positionInSet: 8,
    onyomi: ["カン"],
    kunyomi: ["な.れる", "な.らす"],
    meanings: ["accustomed", "get used to", "habituate"],
    strokeCount: 14,
    exampleWords: [
      { word: "習慣", reading: "しゅうかん", meaning: "habit, custom" },
      { word: "慣れる", reading: "なれる", meaning: "to get used to" },
      { word: "慣習", reading: "かんしゅう", meaning: "custom, convention" },
    ],
  },
  {
    id: "n2-029",
    character: "幹",
    level: "N2",
    setIndex: 1,
    positionInSet: 9,
    onyomi: ["カン"],
    kunyomi: ["みき"],
    meanings: ["trunk", "stem", "main", "chief"],
    strokeCount: 13,
    exampleWords: [
      { word: "幹部", reading: "かんぶ", meaning: "executive, management" },
      { word: "幹線", reading: "かんせん", meaning: "main line, trunk line" },
      { word: "木の幹", reading: "きのみき", meaning: "tree trunk" },
    ],
  },
  {
    id: "n2-030",
    character: "頑",
    level: "N2",
    setIndex: 1,
    positionInSet: 10,
    onyomi: ["ガン"],
    kunyomi: ["かたく.な"],
    meanings: ["stubborn", "determined", "robust", "firm"],
    strokeCount: 13,
    exampleWords: [
      { word: "頑張る", reading: "がんばる", meaning: "to persist, to do one's best" },
      { word: "頑固", reading: "がんこ", meaning: "stubborn, obstinate" },
      { word: "頑丈", reading: "がんじょう", meaning: "robust, sturdy" },
    ],
  },
  {
    id: "n2-031",
    character: "揮",
    level: "N2",
    setIndex: 1,
    positionInSet: 11,
    onyomi: ["キ"],
    kunyomi: [],
    meanings: ["brandish", "wave", "command", "direct"],
    strokeCount: 12,
    exampleWords: [
      { word: "指揮", reading: "しき", meaning: "command, direction" },
      { word: "発揮", reading: "はっき", meaning: "display, showing" },
      { word: "指揮者", reading: "しきしゃ", meaning: "conductor, commander" },
    ],
  },
  {
    id: "n2-032",
    character: "貴",
    level: "N2",
    setIndex: 1,
    positionInSet: 12,
    onyomi: ["キ"],
    kunyomi: ["たっと.い", "とうと.い", "たっと.ぶ"],
    meanings: ["precious", "noble", "exalted", "valuable"],
    strokeCount: 12,
    exampleWords: [
      { word: "貴重", reading: "きちょう", meaning: "precious, valuable" },
      { word: "高貴", reading: "こうき", meaning: "noble, high-class" },
      { word: "貴族", reading: "きぞく", meaning: "nobility, aristocracy" },
    ],
  },
  {
    id: "n2-033",
    character: "犠",
    level: "N2",
    setIndex: 1,
    positionInSet: 13,
    onyomi: ["ギ"],
    kunyomi: [],
    meanings: ["sacrifice", "victim", "scapegoat"],
    strokeCount: 17,
    exampleWords: [
      { word: "犠牲", reading: "ぎせい", meaning: "sacrifice, victim" },
      { word: "犠牲者", reading: "ぎせいしゃ", meaning: "victim, casualty" },
    ],
  },
  {
    id: "n2-034",
    character: "欠",
    level: "N2",
    setIndex: 1,
    positionInSet: 14,
    onyomi: ["ケツ"],
    kunyomi: ["か.ける", "か.く"],
    meanings: ["lack", "shortage", "deficiency"],
    strokeCount: 4,
    exampleWords: [
      { word: "欠席", reading: "けっせき", meaning: "absence" },
      { word: "欠点", reading: "けってん", meaning: "defect, flaw, weakness" },
      { word: "不可欠", reading: "ふかけつ", meaning: "indispensable, essential" },
    ],
  },
  {
    id: "n2-035",
    character: "穴",
    level: "N2",
    setIndex: 1,
    positionInSet: 15,
    onyomi: ["ケツ"],
    kunyomi: ["あな"],
    meanings: ["hole", "cave", "den"],
    strokeCount: 5,
    exampleWords: [
      { word: "穴", reading: "あな", meaning: "hole, cavity" },
      { word: "落とし穴", reading: "おとしあな", meaning: "pitfall, trap" },
      { word: "穴埋め", reading: "あなうめ", meaning: "fill in a gap" },
    ],
  },
  {
    id: "n2-036",
    character: "傾",
    level: "N2",
    setIndex: 1,
    positionInSet: 16,
    onyomi: ["ケイ"],
    kunyomi: ["かたむ.く", "かたむ.ける"],
    meanings: ["lean", "incline", "tilt", "tend toward"],
    strokeCount: 13,
    exampleWords: [
      { word: "傾向", reading: "けいこう", meaning: "tendency, trend" },
      { word: "傾く", reading: "かたむく", meaning: "to incline, to lean" },
      { word: "傾斜", reading: "けいしゃ", meaning: "inclination, slope" },
    ],
  },
  {
    id: "n2-037",
    character: "厳",
    level: "N2",
    setIndex: 1,
    positionInSet: 17,
    onyomi: ["ゲン", "ゴン"],
    kunyomi: ["おごそ.か", "きび.しい"],
    meanings: ["strict", "stern", "solemn", "awe-inspiring"],
    strokeCount: 17,
    exampleWords: [
      { word: "厳しい", reading: "きびしい", meaning: "strict, severe" },
      { word: "厳格", reading: "げんかく", meaning: "strict, stern" },
      { word: "厳重", reading: "げんじゅう", meaning: "strict, severe, rigorous" },
    ],
  },
  {
    id: "n2-038",
    character: "減",
    level: "N2",
    setIndex: 1,
    positionInSet: 18,
    onyomi: ["ゲン"],
    kunyomi: ["へ.る", "へ.らす"],
    meanings: ["dwindle", "decrease", "reduce"],
    strokeCount: 12,
    exampleWords: [
      { word: "減る", reading: "へる", meaning: "to decrease, to diminish" },
      { word: "削減", reading: "さくげん", meaning: "reduction, cutback" },
      { word: "減少", reading: "げんしょう", meaning: "decrease, reduction" },
    ],
  },
  {
    id: "n2-039",
    character: "源",
    level: "N2",
    setIndex: 1,
    positionInSet: 19,
    onyomi: ["ゲン"],
    kunyomi: ["みなもと"],
    meanings: ["source", "origin", "fountain"],
    strokeCount: 13,
    exampleWords: [
      { word: "資源", reading: "しげん", meaning: "resources" },
      { word: "起源", reading: "きげん", meaning: "origin, source" },
      { word: "電源", reading: "でんげん", meaning: "power source" },
    ],
  },
  {
    id: "n2-040",
    character: "固",
    level: "N2",
    setIndex: 2,
    positionInSet: 0,
    onyomi: ["コ"],
    kunyomi: ["かた.める", "かた.まる", "かた.い"],
    meanings: ["harden", "stiffen", "solid", "stubborn"],
    strokeCount: 8,
    exampleWords: [
      { word: "固める", reading: "かためる", meaning: "to harden, to solidify" },
      { word: "固定", reading: "こてい", meaning: "fixing, settlement" },
      { word: "固体", reading: "こたい", meaning: "solid body" },
    ],
  },
  {
    id: "n2-041",
    character: "壊",
    level: "N2",
    setIndex: 2,
    positionInSet: 1,
    onyomi: ["カイ"],
    kunyomi: ["こわ.す", "こわ.れる"],
    meanings: ["demolition", "break down", "destroy"],
    strokeCount: 16,
    exampleWords: [
      { word: "壊れる", reading: "こわれる", meaning: "to break, to be destroyed" },
      { word: "破壊", reading: "はかい", meaning: "destruction, demolition" },
      { word: "倒壊", reading: "とうかい", meaning: "collapse, downfall" },
    ],
  },
  {
    id: "n2-042",
    character: "居",
    level: "N2",
    setIndex: 2,
    positionInSet: 2,
    onyomi: ["キョ"],
    kunyomi: ["い.る", "お.る"],
    meanings: ["reside", "to be", "exist", "live"],
    strokeCount: 8,
    exampleWords: [
      { word: "居る", reading: "いる", meaning: "to be (animate)" },
      { word: "居間", reading: "いま", meaning: "living room" },
      { word: "同居", reading: "どうきょ", meaning: "living together" },
    ],
  },
  {
    id: "n2-043",
    character: "拒",
    level: "N2",
    setIndex: 2,
    positionInSet: 3,
    onyomi: ["キョ"],
    kunyomi: ["こば.む"],
    meanings: ["repel", "refuse", "reject", "resist"],
    strokeCount: 8,
    exampleWords: [
      { word: "拒否", reading: "きょひ", meaning: "rejection, refusal" },
      { word: "拒絶", reading: "きょぜつ", meaning: "rejection, refusal" },
      { word: "拒む", reading: "こばむ", meaning: "to refuse, to reject" },
    ],
  },
  {
    id: "n2-044",
    character: "均",
    level: "N2",
    setIndex: 2,
    positionInSet: 4,
    onyomi: ["キン"],
    kunyomi: ["なら.す"],
    meanings: ["level", "average", "equal", "uniform"],
    strokeCount: 7,
    exampleWords: [
      { word: "平均", reading: "へいきん", meaning: "average, mean" },
      { word: "均等", reading: "きんとう", meaning: "equality, evenness" },
      { word: "均衡", reading: "きんこう", meaning: "balance, equilibrium" },
    ],
  },
  {
    id: "n2-045",
    character: "緊",
    level: "N2",
    setIndex: 2,
    positionInSet: 5,
    onyomi: ["キン"],
    kunyomi: ["ちか.い"],
    meanings: ["tense", "tight", "taut", "urgent"],
    strokeCount: 15,
    exampleWords: [
      { word: "緊張", reading: "きんちょう", meaning: "tension, nervousness" },
      { word: "緊急", reading: "きんきゅう", meaning: "emergency, urgent" },
      { word: "緊迫", reading: "きんぱく", meaning: "tension, pressure" },
    ],
  },
  {
    id: "n2-046",
    character: "禁",
    level: "N2",
    setIndex: 2,
    positionInSet: 6,
    onyomi: ["キン"],
    kunyomi: [],
    meanings: ["prohibition", "ban", "forbid"],
    strokeCount: 13,
    exampleWords: [
      { word: "禁止", reading: "きんし", meaning: "prohibition, ban" },
      { word: "禁煙", reading: "きんえん", meaning: "no smoking" },
      { word: "禁じる", reading: "きんじる", meaning: "to prohibit, to ban" },
    ],
  },
  {
    id: "n2-047",
    character: "叫",
    level: "N2",
    setIndex: 2,
    positionInSet: 7,
    onyomi: ["キョウ"],
    kunyomi: ["さけ.ぶ"],
    meanings: ["shout", "cry out", "scream"],
    strokeCount: 6,
    exampleWords: [
      { word: "叫ぶ", reading: "さけぶ", meaning: "to shout, to cry out" },
      { word: "叫び声", reading: "さけびごえ", meaning: "shout, scream" },
    ],
  },
  {
    id: "n2-048",
    character: "脅",
    level: "N2",
    setIndex: 2,
    positionInSet: 8,
    onyomi: ["キョウ"],
    kunyomi: ["おびや.かす", "おど.す", "おど.かす"],
    meanings: ["threaten", "coerce", "menace"],
    strokeCount: 10,
    exampleWords: [
      { word: "脅す", reading: "おどす", meaning: "to threaten, to intimidate" },
      { word: "脅迫", reading: "きょうはく", meaning: "threat, coercion" },
      { word: "脅威", reading: "きょうい", meaning: "threat, menace" },
    ],
  },
  {
    id: "n2-049",
    character: "勤",
    level: "N2",
    setIndex: 2,
    positionInSet: 9,
    onyomi: ["キン", "ゴン"],
    kunyomi: ["つと.める", "つと.まる"],
    meanings: ["diligence", "serve", "work"],
    strokeCount: 12,
    exampleWords: [
      { word: "勤める", reading: "つとめる", meaning: "to work, to serve" },
      { word: "勤労", reading: "きんろう", meaning: "labor, work" },
      { word: "通勤", reading: "つうきん", meaning: "commuting" },
    ],
  },
  {
    id: "n2-050",
    character: "険",
    level: "N2",
    setIndex: 2,
    positionInSet: 10,
    onyomi: ["ケン"],
    kunyomi: ["けわ.しい"],
    meanings: ["precipitous", "inaccessible place", "steep", "danger"],
    strokeCount: 11,
    exampleWords: [
      { word: "険しい", reading: "けわしい", meaning: "steep, rugged, harsh" },
      { word: "保険", reading: "ほけん", meaning: "insurance" },
      { word: "危険", reading: "きけん", meaning: "danger, peril" },
    ],
  },
  {
    id: "n2-051",
    character: "謙",
    level: "N2",
    setIndex: 2,
    positionInSet: 11,
    onyomi: ["ケン"],
    kunyomi: ["へりくだ.る"],
    meanings: ["humble", "modest", "condescend"],
    strokeCount: 17,
    exampleWords: [
      { word: "謙虚", reading: "けんきょ", meaning: "modest, humble" },
      { word: "謙遜", reading: "けんそん", meaning: "modesty, humility" },
      { word: "謙譲", reading: "けんじょう", meaning: "modesty, humility" },
    ],
  },
  {
    id: "n2-052",
    character: "構",
    level: "N2",
    setIndex: 2,
    positionInSet: 12,
    onyomi: ["コウ"],
    kunyomi: ["かま.える", "かま.う"],
    meanings: ["posture", "build", "pose", "structure", "don't mind"],
    strokeCount: 14,
    exampleWords: [
      { word: "構造", reading: "こうぞう", meaning: "structure, construction" },
      { word: "構成", reading: "こうせい", meaning: "composition, structure" },
      { word: "機構", reading: "きこう", meaning: "mechanism, organization" },
    ],
  },
  {
    id: "n2-053",
    character: "購",
    level: "N2",
    setIndex: 2,
    positionInSet: 13,
    onyomi: ["コウ"],
    kunyomi: [],
    meanings: ["purchase", "buy", "subscribe to"],
    strokeCount: 17,
    exampleWords: [
      { word: "購入", reading: "こうにゅう", meaning: "purchase, buying" },
      { word: "購読", reading: "こうどく", meaning: "subscription, reading" },
      { word: "購買", reading: "こうばい", meaning: "purchasing, buying" },
    ],
  },
  {
    id: "n2-054",
    character: "鋼",
    level: "N2",
    setIndex: 2,
    positionInSet: 14,
    onyomi: ["コウ"],
    kunyomi: ["はがね"],
    meanings: ["steel"],
    strokeCount: 16,
    exampleWords: [
      { word: "鋼鉄", reading: "こうてつ", meaning: "steel" },
      { word: "鋼", reading: "はがね", meaning: "steel" },
      { word: "製鋼", reading: "せいこう", meaning: "steel manufacture" },
    ],
  },
  {
    id: "n2-055",
    character: "困",
    level: "N2",
    setIndex: 2,
    positionInSet: 15,
    onyomi: ["コン"],
    kunyomi: ["こま.る"],
    meanings: ["troubled", "worried", "strained", "in distress"],
    strokeCount: 7,
    exampleWords: [
      { word: "困る", reading: "こまる", meaning: "to be troubled, to be in trouble" },
      { word: "困難", reading: "こんなん", meaning: "difficulty, hardship" },
      { word: "貧困", reading: "ひんこん", meaning: "poverty, destitution" },
    ],
  },
  {
    id: "n2-056",
    character: "際",
    level: "N2",
    setIndex: 2,
    positionInSet: 16,
    onyomi: ["サイ"],
    kunyomi: ["きわ"],
    meanings: ["edge", "brink", "verge", "occasion", "when"],
    strokeCount: 14,
    exampleWords: [
      { word: "国際", reading: "こくさい", meaning: "international" },
      { word: "実際", reading: "じっさい", meaning: "actual, in practice" },
      { word: "際限", reading: "さいげん", meaning: "limit, bounds" },
    ],
  },
  {
    id: "n2-057",
    character: "災",
    level: "N2",
    setIndex: 2,
    positionInSet: 17,
    onyomi: ["サイ"],
    kunyomi: ["わざわ.い"],
    meanings: ["disaster", "calamity", "misfortune"],
    strokeCount: 7,
    exampleWords: [
      { word: "災害", reading: "さいがい", meaning: "disaster, calamity" },
      { word: "天災", reading: "てんさい", meaning: "natural disaster" },
      { word: "火災", reading: "かさい", meaning: "fire, conflagration" },
    ],
  },
  {
    id: "n2-058",
    character: "削",
    level: "N2",
    setIndex: 2,
    positionInSet: 18,
    onyomi: ["サク"],
    kunyomi: ["けず.る"],
    meanings: ["shave", "whittle", "cut down", "reduce"],
    strokeCount: 9,
    exampleWords: [
      { word: "削除", reading: "さくじょ", meaning: "deletion, elimination" },
      { word: "削減", reading: "さくげん", meaning: "reduction, cutback" },
      { word: "削る", reading: "けずる", meaning: "to shave, to whittle" },
    ],
  },
  {
    id: "n2-059",
    character: "賛",
    level: "N2",
    setIndex: 2,
    positionInSet: 19,
    onyomi: ["サン"],
    kunyomi: [],
    meanings: ["agree", "support", "praise"],
    strokeCount: 15,
    exampleWords: [
      { word: "賛成", reading: "さんせい", meaning: "approval, agreement" },
      { word: "賛同", reading: "さんどう", meaning: "agreement, support" },
      { word: "称賛", reading: "しょうさん", meaning: "praise, admiration" },
    ],
  },
  {
    id: "n2-060",
    character: "沿",
    level: "N2",
    setIndex: 3,
    positionInSet: 0,
    onyomi: ["エン"],
    kunyomi: ["そ.う"],
    meanings: ["run alongside", "follow along", "parallel"],
    strokeCount: 8,
    exampleWords: [
      { word: "沿って", reading: "そって", meaning: "along, following" },
      { word: "沿岸", reading: "えんがん", meaning: "coast, shore" },
      { word: "川沿い", reading: "かわぞい", meaning: "along the river" },
    ],
  },
  {
    id: "n2-061",
    character: "損",
    level: "N2",
    setIndex: 3,
    positionInSet: 1,
    onyomi: ["ソン"],
    kunyomi: ["そこ.なう", "そこ.ねる"],
    meanings: ["loss", "damage", "harm", "injure"],
    strokeCount: 13,
    exampleWords: [
      { word: "損害", reading: "そんがい", meaning: "damage, loss" },
      { word: "損失", reading: "そんしつ", meaning: "loss, damage" },
      { word: "破損", reading: "はそん", meaning: "damage, breakage" },
    ],
  },
  {
    id: "n2-062",
    character: "素",
    level: "N2",
    setIndex: 3,
    positionInSet: 2,
    onyomi: ["ソ", "ス"],
    kunyomi: ["もと"],
    meanings: ["element", "ingredient", "plain", "original"],
    strokeCount: 10,
    exampleWords: [
      { word: "素材", reading: "そざい", meaning: "material, element" },
      { word: "素直", reading: "すなお", meaning: "obedient, honest, gentle" },
      { word: "素晴らしい", reading: "すばらしい", meaning: "wonderful, splendid" },
    ],
  },
  {
    id: "n2-063",
    character: "退",
    level: "N2",
    setIndex: 3,
    positionInSet: 3,
    onyomi: ["タイ"],
    kunyomi: ["しりぞ.く", "しりぞ.ける", "の.く"],
    meanings: ["retreat", "withdraw", "retire", "resign"],
    strokeCount: 9,
    exampleWords: [
      { word: "退職", reading: "たいしょく", meaning: "retirement, resignation" },
      { word: "退場", reading: "たいじょう", meaning: "exit, leaving" },
      { word: "撤退", reading: "てったい", meaning: "withdrawal, retreat" },
    ],
  },
  {
    id: "n2-064",
    character: "貸",
    level: "N2",
    setIndex: 3,
    positionInSet: 4,
    onyomi: ["タイ"],
    kunyomi: ["か.す"],
    meanings: ["lend", "loan"],
    strokeCount: 12,
    exampleWords: [
      { word: "貸す", reading: "かす", meaning: "to lend, to loan" },
      { word: "賃貸", reading: "ちんたい", meaning: "lease, rent" },
      { word: "貸出", reading: "かしだし", meaning: "lending, checkout" },
    ],
  },
  {
    id: "n2-065",
    character: "弾",
    level: "N2",
    setIndex: 3,
    positionInSet: 5,
    onyomi: ["ダン", "タン"],
    kunyomi: ["はず.む", "たま", "ひ.く"],
    meanings: ["bullet", "twang", "flip", "play (guitar)"],
    strokeCount: 12,
    exampleWords: [
      { word: "弾く", reading: "ひく", meaning: "to play (instrument)" },
      { word: "爆弾", reading: "ばくだん", meaning: "bomb" },
      { word: "弾丸", reading: "だんがん", meaning: "bullet" },
    ],
  },
  {
    id: "n2-066",
    character: "担",
    level: "N2",
    setIndex: 3,
    positionInSet: 6,
    onyomi: ["タン"],
    kunyomi: ["かつ.ぐ", "にな.う"],
    meanings: ["shouldering", "carry", "be in charge of"],
    strokeCount: 8,
    exampleWords: [
      { word: "担当", reading: "たんとう", meaning: "person in charge" },
      { word: "担う", reading: "になう", meaning: "to bear, to shoulder" },
      { word: "負担", reading: "ふたん", meaning: "burden, load" },
    ],
  },
  {
    id: "n2-067",
    character: "暖",
    level: "N2",
    setIndex: 3,
    positionInSet: 7,
    onyomi: ["ダン"],
    kunyomi: ["あたた.か", "あたた.かい", "あたた.める"],
    meanings: ["warmth", "warm"],
    strokeCount: 13,
    exampleWords: [
      { word: "暖かい", reading: "あたたかい", meaning: "warm (weather)" },
      { word: "温暖", reading: "おんだん", meaning: "warm, mild" },
      { word: "暖房", reading: "だんぼう", meaning: "heating, space heating" },
    ],
  },
  {
    id: "n2-068",
    character: "蓄",
    level: "N2",
    setIndex: 3,
    positionInSet: 8,
    onyomi: ["チク"],
    kunyomi: ["たくわ.える"],
    meanings: ["store up", "lay in", "accumulate"],
    strokeCount: 13,
    exampleWords: [
      { word: "蓄積", reading: "ちくせき", meaning: "accumulation, stockpile" },
      { word: "貯蓄", reading: "ちょちく", meaning: "savings, reserve" },
      { word: "蓄える", reading: "たくわえる", meaning: "to store, to save up" },
    ],
  },
  {
    id: "n2-069",
    character: "柱",
    level: "N2",
    setIndex: 3,
    positionInSet: 9,
    onyomi: ["チュウ"],
    kunyomi: ["はしら"],
    meanings: ["pillar", "post", "support", "column"],
    strokeCount: 9,
    exampleWords: [
      { word: "柱", reading: "はしら", meaning: "pillar, post, column" },
      { word: "電柱", reading: "でんちゅう", meaning: "utility pole" },
      { word: "大黒柱", reading: "だいこくばしら", meaning: "main pillar, breadwinner" },
    ],
  },
  {
    id: "n2-070",
    character: "断",
    level: "N2",
    setIndex: 3,
    positionInSet: 10,
    onyomi: ["ダン"],
    kunyomi: ["た.つ", "ことわ.る"],
    meanings: ["sever", "cut", "interrupt", "refuse"],
    strokeCount: 11,
    exampleWords: [
      { word: "断る", reading: "ことわる", meaning: "to refuse, to decline" },
      { word: "判断", reading: "はんだん", meaning: "judgment, decision" },
      { word: "断定", reading: "だんてい", meaning: "conclusion, decision" },
    ],
  },
  {
    id: "n2-071",
    character: "宙",
    level: "N2",
    setIndex: 3,
    positionInSet: 11,
    onyomi: ["チュウ"],
    kunyomi: [],
    meanings: ["space", "midair", "the sky"],
    strokeCount: 8,
    exampleWords: [
      { word: "宇宙", reading: "うちゅう", meaning: "space, universe" },
      { word: "宙に浮く", reading: "ちゅうにうく", meaning: "to float in the air" },
    ],
  },
  {
    id: "n2-072",
    character: "脱",
    level: "N2",
    setIndex: 3,
    positionInSet: 12,
    onyomi: ["ダツ"],
    kunyomi: ["ぬ.ぐ", "ぬ.げる"],
    meanings: ["escape from", "take off", "undress", "evade"],
    strokeCount: 11,
    exampleWords: [
      { word: "脱出", reading: "だっしゅつ", meaning: "escape, breakout" },
      { word: "脱ぐ", reading: "ぬぐ", meaning: "to take off (clothes)" },
      { word: "離脱", reading: "りだつ", meaning: "withdrawal, breakaway" },
    ],
  },
  {
    id: "n2-073",
    character: "訂",
    level: "N2",
    setIndex: 3,
    positionInSet: 13,
    onyomi: ["テイ"],
    kunyomi: [],
    meanings: ["revise", "correct", "make right"],
    strokeCount: 9,
    exampleWords: [
      { word: "改訂", reading: "かいてい", meaning: "revision, correction" },
      { word: "訂正", reading: "ていせい", meaning: "correction, amendment" },
    ],
  },
  {
    id: "n2-074",
    character: "鉄",
    level: "N2",
    setIndex: 3,
    positionInSet: 14,
    onyomi: ["テツ"],
    kunyomi: [],
    meanings: ["iron", "metal"],
    strokeCount: 13,
    exampleWords: [
      { word: "地下鉄", reading: "ちかてつ", meaning: "subway, underground" },
      { word: "鉄道", reading: "てつどう", meaning: "railroad, railway" },
      { word: "鉄橋", reading: "てっきょう", meaning: "iron bridge" },
    ],
  },
  {
    id: "n2-075",
    character: "典",
    level: "N2",
    setIndex: 3,
    positionInSet: 15,
    onyomi: ["テン"],
    kunyomi: [],
    meanings: ["code", "ceremony", "law", "rule", "standard"],
    strokeCount: 8,
    exampleWords: [
      { word: "辞典", reading: "じてん", meaning: "dictionary" },
      { word: "古典", reading: "こてん", meaning: "classical literature, classics" },
      { word: "典型", reading: "てんけい", meaning: "typical example, model" },
    ],
  },
  {
    id: "n2-076",
    character: "展",
    level: "N2",
    setIndex: 3,
    positionInSet: 16,
    onyomi: ["テン"],
    kunyomi: [],
    meanings: ["unfold", "expand", "exhibit", "display"],
    strokeCount: 10,
    exampleWords: [
      { word: "展開", reading: "てんかい", meaning: "development, expansion" },
      { word: "展示", reading: "てんじ", meaning: "exhibition, display" },
      { word: "発展", reading: "はってん", meaning: "development, growth" },
    ],
  },
  {
    id: "n2-077",
    character: "陶",
    level: "N2",
    setIndex: 3,
    positionInSet: 17,
    onyomi: ["トウ"],
    kunyomi: [],
    meanings: ["pottery", "ceramics", "inspire", "mold"],
    strokeCount: 11,
    exampleWords: [
      { word: "陶器", reading: "とうき", meaning: "pottery, ceramics" },
      { word: "陶芸", reading: "とうげい", meaning: "ceramic art, pottery" },
      { word: "陶酔", reading: "とうすい", meaning: "rapture, ecstasy" },
    ],
  },
  {
    id: "n2-078",
    character: "燃",
    level: "N2",
    setIndex: 3,
    positionInSet: 18,
    onyomi: ["ネン"],
    kunyomi: ["も.える", "も.やす", "も.す"],
    meanings: ["burn", "combustion"],
    strokeCount: 16,
    exampleWords: [
      { word: "燃える", reading: "もえる", meaning: "to burn, to ignite" },
      { word: "燃料", reading: "ねんりょう", meaning: "fuel" },
      { word: "不燃", reading: "ふねん", meaning: "non-flammable, fireproof" },
    ],
  },
  {
    id: "n2-079",
    character: "農",
    level: "N2",
    setIndex: 3,
    positionInSet: 19,
    onyomi: ["ノウ"],
    kunyomi: [],
    meanings: ["agriculture", "farming"],
    strokeCount: 13,
    exampleWords: [
      { word: "農業", reading: "のうぎょう", meaning: "agriculture, farming" },
      { word: "農家", reading: "のうか", meaning: "farm household" },
      { word: "農産物", reading: "のうさんぶつ", meaning: "farm produce" },
    ],
  },
  {
    id: "n2-080",
    character: "濃",
    level: "N2",
    setIndex: 4,
    positionInSet: 0,
    onyomi: ["ノウ"],
    kunyomi: ["こ.い"],
    meanings: ["concentrated", "dense", "thick", "dark"],
    strokeCount: 16,
    exampleWords: [
      { word: "濃い", reading: "こい", meaning: "thick, dense, concentrated" },
      { word: "濃度", reading: "のうど", meaning: "concentration, density" },
      { word: "濃縮", reading: "のうしゅく", meaning: "concentration, enrichment" },
    ],
  },
  {
    id: "n2-081",
    character: "博",
    level: "N2",
    setIndex: 4,
    positionInSet: 1,
    onyomi: ["ハク", "バク"],
    kunyomi: [],
    meanings: ["wide", "broad", "extensive", "doctorate"],
    strokeCount: 12,
    exampleWords: [
      { word: "博士", reading: "はかせ", meaning: "doctoral degree, doctor" },
      { word: "博物館", reading: "はくぶつかん", meaning: "museum" },
      { word: "博覧会", reading: "はくらんかい", meaning: "exhibition, fair" },
    ],
  },
  {
    id: "n2-082",
    character: "版",
    level: "N2",
    setIndex: 4,
    positionInSet: 2,
    onyomi: ["ハン"],
    kunyomi: [],
    meanings: ["printing block", "edition", "impression"],
    strokeCount: 8,
    exampleWords: [
      { word: "出版", reading: "しゅっぱん", meaning: "publication" },
      { word: "版権", reading: "はんけん", meaning: "copyright" },
      { word: "初版", reading: "しょはん", meaning: "first edition" },
    ],
  },
  {
    id: "n2-083",
    character: "比",
    level: "N2",
    setIndex: 4,
    positionInSet: 3,
    onyomi: ["ヒ"],
    kunyomi: ["くら.べる"],
    meanings: ["compare", "ratio", "Philippine", "versus"],
    strokeCount: 4,
    exampleWords: [
      { word: "比較", reading: "ひかく", meaning: "comparison, contrast" },
      { word: "比べる", reading: "くらべる", meaning: "to compare" },
      { word: "対比", reading: "たいひ", meaning: "contrast, comparison" },
    ],
  },
  {
    id: "n2-084",
    character: "批",
    level: "N2",
    setIndex: 4,
    positionInSet: 4,
    onyomi: ["ヒ"],
    kunyomi: [],
    meanings: ["criticism", "judge", "comment"],
    strokeCount: 7,
    exampleWords: [
      { word: "批判", reading: "ひはん", meaning: "criticism, critique" },
      { word: "批評", reading: "ひひょう", meaning: "criticism, review" },
      { word: "批准", reading: "ひじゅん", meaning: "ratification" },
    ],
  },
  {
    id: "n2-085",
    character: "費",
    level: "N2",
    setIndex: 4,
    positionInSet: 5,
    onyomi: ["ヒ"],
    kunyomi: ["つい.やす", "つい.える"],
    meanings: ["expense", "cost", "spend", "consume"],
    strokeCount: 12,
    exampleWords: [
      { word: "費用", reading: "ひよう", meaning: "cost, expense" },
      { word: "消費", reading: "しょうひ", meaning: "consumption" },
      { word: "出費", reading: "しゅっぴ", meaning: "expenditure, spending" },
    ],
  },
  {
    id: "n2-086",
    character: "必",
    level: "N2",
    setIndex: 4,
    positionInSet: 6,
    onyomi: ["ヒツ"],
    kunyomi: ["かなら.ず"],
    meanings: ["invariably", "certain", "inevitable"],
    strokeCount: 5,
    exampleWords: [
      { word: "必要", reading: "ひつよう", meaning: "necessary, required" },
      { word: "必ず", reading: "かならず", meaning: "certainly, definitely" },
      { word: "必死", reading: "ひっし", meaning: "frantic, desperate" },
    ],
  },
  {
    id: "n2-087",
    character: "標",
    level: "N2",
    setIndex: 4,
    positionInSet: 7,
    onyomi: ["ヒョウ"],
    kunyomi: ["しるべ", "しるし"],
    meanings: ["signpost", "mark", "target", "goal"],
    strokeCount: 15,
    exampleWords: [
      { word: "目標", reading: "もくひょう", meaning: "goal, target, aim" },
      { word: "標準", reading: "ひょうじゅん", meaning: "standard, criterion" },
      { word: "標識", reading: "ひょうしき", meaning: "sign, signal, marker" },
    ],
  },
  {
    id: "n2-088",
    character: "補",
    level: "N2",
    setIndex: 4,
    positionInSet: 8,
    onyomi: ["ホ"],
    kunyomi: ["おぎな.う"],
    meanings: ["supplement", "patch", "fill", "assist"],
    strokeCount: 12,
    exampleWords: [
      { word: "補充", reading: "ほじゅう", meaning: "replenishment, supplement" },
      { word: "補助", reading: "ほじょ", meaning: "assistance, supplement" },
      { word: "候補", reading: "こうほ", meaning: "candidate, choice" },
    ],
  },
  {
    id: "n2-089",
    character: "墓",
    level: "N2",
    setIndex: 4,
    positionInSet: 9,
    onyomi: ["ボ"],
    kunyomi: ["はか"],
    meanings: ["grave", "tomb"],
    strokeCount: 13,
    exampleWords: [
      { word: "墓地", reading: "ぼち", meaning: "cemetery, graveyard" },
      { word: "お墓", reading: "おはか", meaning: "grave, tomb" },
      { word: "墓石", reading: "はかいし", meaning: "gravestone, tombstone" },
    ],
  },
  {
    id: "n2-090",
    character: "報",
    level: "N2",
    setIndex: 4,
    positionInSet: 10,
    onyomi: ["ホウ"],
    kunyomi: ["むく.いる"],
    meanings: ["report", "news", "inform", "reward"],
    strokeCount: 12,
    exampleWords: [
      { word: "情報", reading: "じょうほう", meaning: "information" },
      { word: "報告", reading: "ほうこく", meaning: "report" },
      { word: "報道", reading: "ほうどう", meaning: "news, reporting" },
    ],
  },
  {
    id: "n2-091",
    character: "豊",
    level: "N2",
    setIndex: 4,
    positionInSet: 11,
    onyomi: ["ホウ"],
    kunyomi: ["ゆた.か", "とよ"],
    meanings: ["bountiful", "excellent", "rich", "abundant"],
    strokeCount: 13,
    exampleWords: [
      { word: "豊か", reading: "ゆたか", meaning: "wealthy, abundant" },
      { word: "豊富", reading: "ほうふ", meaning: "abundance, plenty" },
      { word: "豊作", reading: "ほうさく", meaning: "good harvest" },
    ],
  },
  {
    id: "n2-092",
    character: "飽",
    level: "N2",
    setIndex: 4,
    positionInSet: 12,
    onyomi: ["ホウ"],
    kunyomi: ["あ.きる", "あ.かす"],
    meanings: ["tired of", "sated", "satisfied", "bored"],
    strokeCount: 13,
    exampleWords: [
      { word: "飽きる", reading: "あきる", meaning: "to get tired of, to be bored" },
      { word: "飽和", reading: "ほうわ", meaning: "saturation" },
    ],
  },
  {
    id: "n2-093",
    character: "暴",
    level: "N2",
    setIndex: 4,
    positionInSet: 13,
    onyomi: ["ボウ", "バク"],
    kunyomi: ["あば.く", "あば.れる"],
    meanings: ["outburst", "rave", "violence", "cruelty", "expose"],
    strokeCount: 15,
    exampleWords: [
      { word: "暴力", reading: "ぼうりょく", meaning: "violence, brute force" },
      { word: "暴れる", reading: "あばれる", meaning: "to act violently" },
      { word: "暴走", reading: "ぼうそう", meaning: "running amok, reckless driving" },
    ],
  },
  {
    id: "n2-094",
    character: "防",
    level: "N2",
    setIndex: 4,
    positionInSet: 14,
    onyomi: ["ボウ"],
    kunyomi: ["ふせ.ぐ"],
    meanings: ["ward off", "defend", "protect", "prevent"],
    strokeCount: 7,
    exampleWords: [
      { word: "防止", reading: "ぼうし", meaning: "prevention" },
      { word: "防衛", reading: "ぼうえい", meaning: "defense, protection" },
      { word: "予防", reading: "よぼう", meaning: "prevention, precaution" },
    ],
  },
  {
    id: "n2-095",
    character: "貿",
    level: "N2",
    setIndex: 4,
    positionInSet: 15,
    onyomi: ["ボウ"],
    kunyomi: [],
    meanings: ["trade", "exchange"],
    strokeCount: 12,
    exampleWords: [
      { word: "貿易", reading: "ぼうえき", meaning: "trade, commerce" },
      { word: "自由貿易", reading: "じゆうぼうえき", meaning: "free trade" },
    ],
  },
  {
    id: "n2-096",
    character: "免",
    level: "N2",
    setIndex: 4,
    positionInSet: 16,
    onyomi: ["メン"],
    kunyomi: ["まぬか.れる"],
    meanings: ["excuse", "exempt", "dismiss", "evade"],
    strokeCount: 8,
    exampleWords: [
      { word: "免許", reading: "めんきょ", meaning: "license, permission" },
      { word: "免税", reading: "めんぜい", meaning: "tax exemption" },
      { word: "免疫", reading: "めんえき", meaning: "immunity" },
    ],
  },
  {
    id: "n2-097",
    character: "模",
    level: "N2",
    setIndex: 4,
    positionInSet: 17,
    onyomi: ["モ", "ボ"],
    kunyomi: [],
    meanings: ["model", "imitate", "copy", "pattern"],
    strokeCount: 14,
    exampleWords: [
      { word: "模型", reading: "もけい", meaning: "model, scale model" },
      { word: "模倣", reading: "もほう", meaning: "imitation, copying" },
      { word: "規模", reading: "きぼ", meaning: "scale, scope" },
    ],
  },
  {
    id: "n2-098",
    character: "躍",
    level: "N2",
    setIndex: 4,
    positionInSet: 18,
    onyomi: ["ヤク"],
    kunyomi: ["おど.る"],
    meanings: ["leap", "jump", "skip", "bounce"],
    strokeCount: 21,
    exampleWords: [
      { word: "躍動", reading: "やくどう", meaning: "lively, dynamic movement" },
      { word: "活躍", reading: "かつやく", meaning: "activity, playing an active role" },
      { word: "飛躍", reading: "ひやく", meaning: "leap, jump, rapid progress" },
    ],
  },
  {
    id: "n2-099",
    character: "余",
    level: "N2",
    setIndex: 4,
    positionInSet: 19,
    onyomi: ["ヨ"],
    kunyomi: ["あま.る", "あま.す", "あまり"],
    meanings: ["too much", "excess", "remainder", "surplus"],
    strokeCount: 7,
    exampleWords: [
      { word: "余裕", reading: "よゆう", meaning: "surplus, margin, composure" },
      { word: "余分", reading: "よぶん", meaning: "extra, surplus" },
      { word: "余暇", reading: "よか", meaning: "leisure, spare time" },
    ],
  },
  {
    id: "n2-100",
    character: "抑",
    level: "N2",
    setIndex: 5,
    positionInSet: 0,
    onyomi: ["ヨク"],
    kunyomi: ["おさ.える"],
    meanings: ["suppress", "hold down", "subdue", "restrain"],
    strokeCount: 7,
    exampleWords: [
      { word: "抑制", reading: "よくせい", meaning: "suppression, control" },
      { word: "抑える", reading: "おさえる", meaning: "to hold down, to restrain" },
      { word: "抑圧", reading: "よくあつ", meaning: "oppression, repression" },
    ],
  },
  {
    id: "n2-101",
    character: "預",
    level: "N2",
    setIndex: 5,
    positionInSet: 1,
    onyomi: ["ヨ"],
    kunyomi: ["あず.ける", "あず.かる"],
    meanings: ["deposit", "leave with", "entrust"],
    strokeCount: 13,
    exampleWords: [
      { word: "預ける", reading: "あずける", meaning: "to leave in custody, to deposit" },
      { word: "預金", reading: "よきん", meaning: "bank deposit, savings" },
      { word: "預かる", reading: "あずかる", meaning: "to be entrusted with" },
    ],
  },
  {
    id: "n2-102",
    character: "抱",
    level: "N2",
    setIndex: 5,
    positionInSet: 2,
    onyomi: ["ホウ"],
    kunyomi: ["だ.く", "いだ.く", "かか.える"],
    meanings: ["embrace", "hug", "hold", "harbor"],
    strokeCount: 8,
    exampleWords: [
      { word: "抱く", reading: "だく", meaning: "to hold, to embrace" },
      { word: "抱える", reading: "かかえる", meaning: "to carry, to hold, to have" },
      { word: "抱負", reading: "ほうふ", meaning: "aspiration, ambition" },
    ],
  },
];
