import type { Kanji } from "./types";

export const N3_KANJI: Kanji[] = [
  {
    id: "n3-000",
    character: "愛",
    level: "N3",
    setIndex: 0,
    positionInSet: 0,
    onyomi: ["アイ"],
    kunyomi: ["あい"],
    meanings: ["love", "affection", "care"],
    strokeCount: 13,
    exampleWords: [
      { word: "愛情", reading: "あいじょう", meaning: "love, affection" },
      { word: "愛する", reading: "あいする", meaning: "to love" },
      { word: "恋愛", reading: "れんあい", meaning: "romantic love" },
    ],
  },
  {
    id: "n3-001",
    character: "暗",
    level: "N3",
    setIndex: 0,
    positionInSet: 1,
    onyomi: ["アン"],
    kunyomi: ["くら.い"],
    meanings: ["dark", "gloomy", "hidden", "secret"],
    strokeCount: 13,
    exampleWords: [
      { word: "暗い", reading: "くらい", meaning: "dark, gloomy" },
      { word: "暗記", reading: "あんき", meaning: "memorization" },
      { word: "暗号", reading: "あんごう", meaning: "code, cipher" },
    ],
  },
  {
    id: "n3-002",
    character: "委",
    level: "N3",
    setIndex: 0,
    positionInSet: 2,
    onyomi: ["イ"],
    kunyomi: ["ゆだ.ねる"],
    meanings: ["committee", "entrust", "leave to"],
    strokeCount: 8,
    exampleWords: [
      { word: "委員", reading: "いいん", meaning: "committee member" },
      { word: "委員会", reading: "いいんかい", meaning: "committee" },
      { word: "委任", reading: "いにん", meaning: "delegation, commission" },
    ],
  },
  {
    id: "n3-003",
    character: "威",
    level: "N3",
    setIndex: 0,
    positionInSet: 3,
    onyomi: ["イ"],
    kunyomi: ["おど.す"],
    meanings: ["intimidate", "authority", "power", "awe"],
    strokeCount: 9,
    exampleWords: [
      { word: "威力", reading: "いりょく", meaning: "power, authority" },
      { word: "権威", reading: "けんい", meaning: "authority, power" },
      { word: "威圧", reading: "いあつ", meaning: "intimidation, coercion" },
    ],
  },
  {
    id: "n3-004",
    character: "移",
    level: "N3",
    setIndex: 0,
    positionInSet: 4,
    onyomi: ["イ"],
    kunyomi: ["うつ.る", "うつ.す"],
    meanings: ["shift", "move", "change", "transfer"],
    strokeCount: 11,
    exampleWords: [
      { word: "移動", reading: "いどう", meaning: "movement, transfer" },
      { word: "移住", reading: "いじゅう", meaning: "emigration, migration" },
      { word: "推移", reading: "すいい", meaning: "transition, change" },
    ],
  },
  {
    id: "n3-005",
    character: "因",
    level: "N3",
    setIndex: 0,
    positionInSet: 5,
    onyomi: ["イン"],
    kunyomi: ["よ.る"],
    meanings: ["cause", "reason", "from", "based on"],
    strokeCount: 6,
    exampleWords: [
      { word: "原因", reading: "げんいん", meaning: "cause, origin, reason" },
      { word: "要因", reading: "よういん", meaning: "main cause, factor" },
      { word: "因果", reading: "いんが", meaning: "cause and effect, karma" },
    ],
  },
  {
    id: "n3-006",
    character: "印",
    level: "N3",
    setIndex: 0,
    positionInSet: 6,
    onyomi: ["イン"],
    kunyomi: ["しるし"],
    meanings: ["stamp", "seal", "mark", "sign", "India"],
    strokeCount: 6,
    exampleWords: [
      { word: "印象", reading: "いんしょう", meaning: "impression" },
      { word: "印鑑", reading: "いんかん", meaning: "personal seal, stamp" },
      { word: "印刷", reading: "いんさつ", meaning: "printing" },
    ],
  },
  {
    id: "n3-007",
    character: "員",
    level: "N3",
    setIndex: 0,
    positionInSet: 7,
    onyomi: ["イン"],
    kunyomi: [],
    meanings: ["member", "person", "employee"],
    strokeCount: 10,
    exampleWords: [
      { word: "社員", reading: "しゃいん", meaning: "company employee" },
      { word: "店員", reading: "てんいん", meaning: "store clerk" },
      { word: "全員", reading: "ぜんいん", meaning: "all members, everyone" },
    ],
  },
  {
    id: "n3-008",
    character: "宇",
    level: "N3",
    setIndex: 0,
    positionInSet: 8,
    onyomi: ["ウ"],
    kunyomi: [],
    meanings: ["eaves", "roof", "house", "universe"],
    strokeCount: 6,
    exampleWords: [
      { word: "宇宙", reading: "うちゅう", meaning: "space, universe" },
      { word: "宇宙人", reading: "うちゅうじん", meaning: "alien, space person" },
      { word: "宇宙船", reading: "うちゅうせん", meaning: "spaceship" },
    ],
  },
  {
    id: "n3-009",
    character: "受",
    level: "N3",
    setIndex: 0,
    positionInSet: 9,
    onyomi: ["ジュ"],
    kunyomi: ["う.ける", "う.かる"],
    meanings: ["accept", "receive", "catch", "be given"],
    strokeCount: 8,
    exampleWords: [
      { word: "受ける", reading: "うける", meaning: "to receive, to take (exam)" },
      { word: "受付", reading: "うけつけ", meaning: "reception, reception desk" },
      { word: "受験", reading: "じゅけん", meaning: "taking an examination" },
    ],
  },
  {
    id: "n3-010",
    character: "羽",
    level: "N3",
    setIndex: 0,
    positionInSet: 10,
    onyomi: ["ウ"],
    kunyomi: ["は", "はね"],
    meanings: ["feathers", "wings", "plume"],
    strokeCount: 6,
    exampleWords: [
      { word: "羽", reading: "はね", meaning: "feather, wing" },
      { word: "羽根", reading: "はね", meaning: "feather, wing" },
      { word: "白羽", reading: "しらは", meaning: "white feather" },
    ],
  },
  {
    id: "n3-011",
    character: "泳",
    level: "N3",
    setIndex: 0,
    positionInSet: 11,
    onyomi: ["エイ"],
    kunyomi: ["およ.ぐ"],
    meanings: ["swim"],
    strokeCount: 8,
    exampleWords: [
      { word: "泳ぐ", reading: "およぐ", meaning: "to swim" },
      { word: "水泳", reading: "すいえい", meaning: "swimming" },
      { word: "背泳ぎ", reading: "せおよぎ", meaning: "backstroke" },
    ],
  },
  {
    id: "n3-012",
    character: "汚",
    level: "N3",
    setIndex: 0,
    positionInSet: 12,
    onyomi: ["オ"],
    kunyomi: ["けが.す", "けが.れる", "きたな.い", "よご.す", "よご.れる"],
    meanings: ["dirty", "filthy", "soiled", "pollute"],
    strokeCount: 6,
    exampleWords: [
      { word: "汚い", reading: "きたない", meaning: "dirty, filthy" },
      { word: "汚染", reading: "おせん", meaning: "pollution, contamination" },
      { word: "汚れる", reading: "よごれる", meaning: "to become dirty" },
    ],
  },
  {
    id: "n3-013",
    character: "温",
    level: "N3",
    setIndex: 0,
    positionInSet: 13,
    onyomi: ["オン"],
    kunyomi: ["あたた.か", "あたた.かい", "あたた.まる", "あたた.める"],
    meanings: ["warm", "mild", "kind"],
    strokeCount: 12,
    exampleWords: [
      { word: "温度", reading: "おんど", meaning: "temperature" },
      { word: "温泉", reading: "おんせん", meaning: "hot spring" },
      { word: "気温", reading: "きおん", meaning: "air temperature" },
    ],
  },
  {
    id: "n3-014",
    character: "可",
    level: "N3",
    setIndex: 0,
    positionInSet: 14,
    onyomi: ["カ"],
    kunyomi: [],
    meanings: ["can", "possible", "can do", "approve"],
    strokeCount: 5,
    exampleWords: [
      { word: "可能", reading: "かのう", meaning: "possible, feasible" },
      { word: "許可", reading: "きょか", meaning: "permission, approval" },
      { word: "不可能", reading: "ふかのう", meaning: "impossible" },
    ],
  },
  {
    id: "n3-015",
    character: "果",
    level: "N3",
    setIndex: 0,
    positionInSet: 15,
    onyomi: ["カ"],
    kunyomi: ["は.たす", "は.てる", "は.て", "くだ.もの"],
    meanings: ["fruit", "result", "accomplish", "fulfill"],
    strokeCount: 8,
    exampleWords: [
      { word: "果物", reading: "くだもの", meaning: "fruit" },
      { word: "結果", reading: "けっか", meaning: "result, outcome" },
      { word: "効果", reading: "こうか", meaning: "effect, efficacy" },
    ],
  },
  {
    id: "n3-016",
    character: "荷",
    level: "N3",
    setIndex: 0,
    positionInSet: 16,
    onyomi: ["カ"],
    kunyomi: ["に"],
    meanings: ["baggage", "load", "cargo", "freight"],
    strokeCount: 10,
    exampleWords: [
      { word: "荷物", reading: "にもつ", meaning: "luggage, baggage" },
      { word: "入荷", reading: "にゅうか", meaning: "arrival of goods" },
      { word: "出荷", reading: "しゅっか", meaning: "shipping, dispatch" },
    ],
  },
  {
    id: "n3-017",
    character: "仮",
    level: "N3",
    setIndex: 0,
    positionInSet: 17,
    onyomi: ["カ", "ケ"],
    kunyomi: ["かり"],
    meanings: ["provisional", "temporary", "supposed", "formal"],
    strokeCount: 6,
    exampleWords: [
      { word: "仮定", reading: "かてい", meaning: "assumption, hypothesis" },
      { word: "仮名", reading: "かな", meaning: "kana (Japanese syllabary)" },
      { word: "仮説", reading: "かせつ", meaning: "hypothesis, theory" },
    ],
  },
  {
    id: "n3-018",
    character: "画",
    level: "N3",
    setIndex: 0,
    positionInSet: 18,
    onyomi: ["ガ", "カク"],
    kunyomi: [],
    meanings: ["picture", "painting", "stroke", "picture"],
    strokeCount: 8,
    exampleWords: [
      { word: "映画", reading: "えいが", meaning: "movie, film" },
      { word: "計画", reading: "けいかく", meaning: "plan, scheme" },
      { word: "漫画", reading: "まんが", meaning: "manga, comic" },
    ],
  },
  {
    id: "n3-019",
    character: "界",
    level: "N3",
    setIndex: 0,
    positionInSet: 19,
    onyomi: ["カイ"],
    kunyomi: [],
    meanings: ["world", "boundary"],
    strokeCount: 9,
    exampleWords: [
      { word: "世界", reading: "せかい", meaning: "world" },
      { word: "業界", reading: "ぎょうかい", meaning: "industry, business world" },
      { word: "限界", reading: "げんかい", meaning: "limit, bounds" },
    ],
  },
  {
    id: "n3-020",
    character: "格",
    level: "N3",
    setIndex: 1,
    positionInSet: 0,
    onyomi: ["カク", "コウ", "キャク", "ゴウ"],
    kunyomi: [],
    meanings: ["status", "character", "grid", "standard"],
    strokeCount: 10,
    exampleWords: [
      { word: "性格", reading: "せいかく", meaning: "character, personality" },
      { word: "価格", reading: "かかく", meaning: "price, cost" },
      { word: "資格", reading: "しかく", meaning: "qualification, license" },
    ],
  },
  {
    id: "n3-021",
    character: "確",
    level: "N3",
    setIndex: 1,
    positionInSet: 1,
    onyomi: ["カク"],
    kunyomi: ["たし.か", "たし.かめる"],
    meanings: ["certain", "sure", "accurate", "confirm"],
    strokeCount: 15,
    exampleWords: [
      { word: "確認", reading: "かくにん", meaning: "confirmation, verification" },
      { word: "確かめる", reading: "たしかめる", meaning: "to confirm, to make sure" },
      { word: "正確", reading: "せいかく", meaning: "accurate, exact" },
    ],
  },
  {
    id: "n3-022",
    character: "過",
    level: "N3",
    setIndex: 1,
    positionInSet: 2,
    onyomi: ["カ"],
    kunyomi: ["す.ぎる", "す.ごす", "あやま.ち"],
    meanings: ["pass", "exceed", "go beyond", "mistake"],
    strokeCount: 12,
    exampleWords: [
      { word: "過去", reading: "かこ", meaning: "the past" },
      { word: "通過", reading: "つうか", meaning: "passage, transit" },
      { word: "過ごす", reading: "すごす", meaning: "to spend (time)" },
    ],
  },
  {
    id: "n3-023",
    character: "感",
    level: "N3",
    setIndex: 1,
    positionInSet: 3,
    onyomi: ["カン"],
    kunyomi: ["かん.じる"],
    meanings: ["emotion", "feeling", "sensation"],
    strokeCount: 13,
    exampleWords: [
      { word: "感じる", reading: "かんじる", meaning: "to feel, to sense" },
      { word: "感謝", reading: "かんしゃ", meaning: "gratitude, thanks" },
      { word: "感動", reading: "かんどう", meaning: "being moved, impressed" },
    ],
  },
  {
    id: "n3-024",
    character: "完",
    level: "N3",
    setIndex: 1,
    positionInSet: 4,
    onyomi: ["カン"],
    kunyomi: [],
    meanings: ["perfect", "completion", "end"],
    strokeCount: 7,
    exampleWords: [
      { word: "完成", reading: "かんせい", meaning: "completion, perfection" },
      { word: "完全", reading: "かんぜん", meaning: "perfect, complete" },
      { word: "完了", reading: "かんりょう", meaning: "completion, finish" },
    ],
  },
  {
    id: "n3-025",
    character: "観",
    level: "N3",
    setIndex: 1,
    positionInSet: 5,
    onyomi: ["カン"],
    kunyomi: ["み.る"],
    meanings: ["observe", "watch", "view", "outlook"],
    strokeCount: 18,
    exampleWords: [
      { word: "観光", reading: "かんこう", meaning: "sightseeing, tourism" },
      { word: "観察", reading: "かんさつ", meaning: "observation" },
      { word: "主観", reading: "しゅかん", meaning: "subjectivity" },
    ],
  },
  {
    id: "n3-026",
    character: "考",
    level: "N3",
    setIndex: 1,
    positionInSet: 6,
    onyomi: ["コウ"],
    kunyomi: ["かんが.える"],
    meanings: ["consider", "think over"],
    strokeCount: 6,
    exampleWords: [
      { word: "考える", reading: "かんがえる", meaning: "to think, to consider" },
      { word: "考え方", reading: "かんがえかた", meaning: "way of thinking" },
      { word: "参考", reading: "さんこう", meaning: "reference, consultation" },
    ],
  },
  {
    id: "n3-027",
    character: "機",
    level: "N3",
    setIndex: 1,
    positionInSet: 7,
    onyomi: ["キ"],
    kunyomi: ["はた"],
    meanings: ["machine", "opportunity", "chance", "aircraft"],
    strokeCount: 16,
    exampleWords: [
      { word: "飛行機", reading: "ひこうき", meaning: "airplane" },
      { word: "機会", reading: "きかい", meaning: "opportunity, chance" },
      { word: "機械", reading: "きかい", meaning: "machine, machinery" },
    ],
  },
  {
    id: "n3-028",
    character: "危",
    level: "N3",
    setIndex: 1,
    positionInSet: 8,
    onyomi: ["キ"],
    kunyomi: ["あぶ.ない", "あや.うい", "あや.ぶむ"],
    meanings: ["dangerous", "perilous", "hazardous"],
    strokeCount: 6,
    exampleWords: [
      { word: "危険", reading: "きけん", meaning: "danger, peril" },
      { word: "危ない", reading: "あぶない", meaning: "dangerous, risky" },
      { word: "危機", reading: "きき", meaning: "crisis, critical moment" },
    ],
  },
  {
    id: "n3-029",
    character: "期",
    level: "N3",
    setIndex: 1,
    positionInSet: 9,
    onyomi: ["キ", "ゴ"],
    kunyomi: ["ご"],
    meanings: ["period", "term", "expectation"],
    strokeCount: 12,
    exampleWords: [
      { word: "期間", reading: "きかん", meaning: "period, duration" },
      { word: "学期", reading: "がっき", meaning: "school term, semester" },
      { word: "期待", reading: "きたい", meaning: "expectation, hope" },
    ],
  },
  {
    id: "n3-030",
    character: "疑",
    level: "N3",
    setIndex: 1,
    positionInSet: 10,
    onyomi: ["ギ"],
    kunyomi: ["うたが.う"],
    meanings: ["doubt", "distrust", "be suspicious"],
    strokeCount: 14,
    exampleWords: [
      { word: "疑問", reading: "ぎもん", meaning: "question, doubt" },
      { word: "疑う", reading: "うたがう", meaning: "to doubt, to suspect" },
      { word: "容疑者", reading: "ようぎしゃ", meaning: "suspect (criminal)" },
    ],
  },
  {
    id: "n3-031",
    character: "規",
    level: "N3",
    setIndex: 1,
    positionInSet: 11,
    onyomi: ["キ"],
    kunyomi: [],
    meanings: ["standard", "rule", "regulation"],
    strokeCount: 11,
    exampleWords: [
      { word: "規則", reading: "きそく", meaning: "rule, regulation" },
      { word: "規模", reading: "きぼ", meaning: "scale, scope" },
      { word: "定規", reading: "じょうぎ", meaning: "ruler (measuring)" },
    ],
  },
  {
    id: "n3-032",
    character: "技",
    level: "N3",
    setIndex: 1,
    positionInSet: 12,
    onyomi: ["ギ"],
    kunyomi: ["わざ"],
    meanings: ["skill", "art", "craft", "ability", "technique"],
    strokeCount: 7,
    exampleWords: [
      { word: "技術", reading: "ぎじゅつ", meaning: "technology, skill" },
      { word: "技能", reading: "ぎのう", meaning: "technical skill, ability" },
      { word: "演技", reading: "えんぎ", meaning: "performance, acting" },
    ],
  },
  {
    id: "n3-033",
    character: "客",
    level: "N3",
    setIndex: 1,
    positionInSet: 13,
    onyomi: ["キャク", "カク"],
    kunyomi: [],
    meanings: ["guest", "visitor", "customer"],
    strokeCount: 9,
    exampleWords: [
      { word: "客", reading: "きゃく", meaning: "guest, customer" },
      { word: "観光客", reading: "かんこうきゃく", meaning: "tourist" },
      { word: "乗客", reading: "じょうきゃく", meaning: "passenger" },
    ],
  },
  {
    id: "n3-034",
    character: "給",
    level: "N3",
    setIndex: 1,
    positionInSet: 14,
    onyomi: ["キュウ"],
    kunyomi: [],
    meanings: ["salary", "supply", "provide", "give"],
    strokeCount: 12,
    exampleWords: [
      { word: "給料", reading: "きゅうりょう", meaning: "salary, wages" },
      { word: "給食", reading: "きゅうしょく", meaning: "school lunch, provided meal" },
      { word: "供給", reading: "きょうきゅう", meaning: "supply, provision" },
    ],
  },
  {
    id: "n3-035",
    character: "許",
    level: "N3",
    setIndex: 1,
    positionInSet: 15,
    onyomi: ["キョ"],
    kunyomi: ["ゆる.す"],
    meanings: ["permit", "allow", "forgive"],
    strokeCount: 11,
    exampleWords: [
      { word: "許す", reading: "ゆるす", meaning: "to permit, to forgive" },
      { word: "免許", reading: "めんきょ", meaning: "license, permission" },
      { word: "許可", reading: "きょか", meaning: "permission, approval" },
    ],
  },
  {
    id: "n3-036",
    character: "境",
    level: "N3",
    setIndex: 1,
    positionInSet: 16,
    onyomi: ["キョウ", "ケイ"],
    kunyomi: ["さかい"],
    meanings: ["boundary", "border", "circumstances"],
    strokeCount: 14,
    exampleWords: [
      { word: "環境", reading: "かんきょう", meaning: "environment" },
      { word: "国境", reading: "こっきょう", meaning: "national border" },
      { word: "境界", reading: "きょうかい", meaning: "boundary, border" },
    ],
  },
  {
    id: "n3-037",
    character: "共",
    level: "N3",
    setIndex: 1,
    positionInSet: 17,
    onyomi: ["キョウ"],
    kunyomi: ["とも", "とも.に"],
    meanings: ["together", "both", "all", "common"],
    strokeCount: 6,
    exampleWords: [
      { word: "共通", reading: "きょうつう", meaning: "common, shared" },
      { word: "共同", reading: "きょうどう", meaning: "cooperation, collaboration" },
      { word: "共有", reading: "きょうゆう", meaning: "shared ownership" },
    ],
  },
  {
    id: "n3-038",
    character: "協",
    level: "N3",
    setIndex: 1,
    positionInSet: 18,
    onyomi: ["キョウ"],
    kunyomi: [],
    meanings: ["cooperate", "unite"],
    strokeCount: 8,
    exampleWords: [
      { word: "協力", reading: "きょうりょく", meaning: "cooperation, collaboration" },
      { word: "協議", reading: "きょうぎ", meaning: "conference, discussion" },
      { word: "妥協", reading: "だきょう", meaning: "compromise" },
    ],
  },
  {
    id: "n3-039",
    character: "競",
    level: "N3",
    setIndex: 1,
    positionInSet: 19,
    onyomi: ["キョウ", "ケイ"],
    kunyomi: ["きそ.う", "せ.る"],
    meanings: ["compete", "race", "contest"],
    strokeCount: 20,
    exampleWords: [
      { word: "競争", reading: "きょうそう", meaning: "competition, contest" },
      { word: "競技", reading: "きょうぎ", meaning: "athletic event, competition" },
      { word: "競馬", reading: "けいば", meaning: "horse racing" },
    ],
  },
  {
    id: "n3-040",
    character: "極",
    level: "N3",
    setIndex: 2,
    positionInSet: 0,
    onyomi: ["キョク", "ゴク"],
    kunyomi: ["きわ.める", "きわ.まる", "きわ.み"],
    meanings: ["extreme", "pole", "climax", "utmost"],
    strokeCount: 12,
    exampleWords: [
      { word: "極端", reading: "きょくたん", meaning: "extreme, radical" },
      { word: "北極", reading: "ほっきょく", meaning: "North Pole, Arctic" },
      { word: "積極的", reading: "せっきょくてき", meaning: "positive, proactive" },
    ],
  },
  {
    id: "n3-041",
    character: "具",
    level: "N3",
    setIndex: 2,
    positionInSet: 1,
    onyomi: ["グ"],
    kunyomi: ["そな.わる", "そな.える"],
    meanings: ["tool", "possess", "furnish", "provide"],
    strokeCount: 8,
    exampleWords: [
      { word: "道具", reading: "どうぐ", meaning: "tool, implement" },
      { word: "家具", reading: "かぐ", meaning: "furniture" },
      { word: "具体的", reading: "ぐたいてき", meaning: "concrete, specific" },
    ],
  },
  {
    id: "n3-042",
    character: "経",
    level: "N3",
    setIndex: 2,
    positionInSet: 2,
    onyomi: ["ケイ", "キョウ"],
    kunyomi: ["へ.る", "た.つ"],
    meanings: ["pass", "sutra", "longitude", "economy"],
    strokeCount: 11,
    exampleWords: [
      { word: "経済", reading: "けいざい", meaning: "economy" },
      { word: "経験", reading: "けいけん", meaning: "experience" },
      { word: "経営", reading: "けいえい", meaning: "management, administration" },
    ],
  },
  {
    id: "n3-043",
    character: "刑",
    level: "N3",
    setIndex: 2,
    positionInSet: 3,
    onyomi: ["ケイ"],
    kunyomi: [],
    meanings: ["punish", "penalty", "sentence"],
    strokeCount: 6,
    exampleWords: [
      { word: "刑事", reading: "けいじ", meaning: "detective, criminal case" },
      { word: "刑務所", reading: "けいむしょ", meaning: "prison, penitentiary" },
      { word: "死刑", reading: "しけい", meaning: "death penalty" },
    ],
  },
  {
    id: "n3-044",
    character: "決",
    level: "N3",
    setIndex: 2,
    positionInSet: 4,
    onyomi: ["ケツ"],
    kunyomi: ["き.める", "き.まる", "さ.く"],
    meanings: ["decide", "fix", "agree"],
    strokeCount: 7,
    exampleWords: [
      { word: "決める", reading: "きめる", meaning: "to decide, to determine" },
      { word: "解決", reading: "かいけつ", meaning: "solution, resolution" },
      { word: "決定", reading: "けってい", meaning: "decision, determination" },
    ],
  },
  {
    id: "n3-045",
    character: "権",
    level: "N3",
    setIndex: 2,
    positionInSet: 5,
    onyomi: ["ケン", "ゴン"],
    kunyomi: ["おもり", "かり"],
    meanings: ["authority", "rights", "power", "privilege"],
    strokeCount: 15,
    exampleWords: [
      { word: "権利", reading: "けんり", meaning: "right, privilege" },
      { word: "人権", reading: "じんけん", meaning: "human rights" },
      { word: "政権", reading: "せいけん", meaning: "political power, regime" },
    ],
  },
  {
    id: "n3-046",
    character: "現",
    level: "N3",
    setIndex: 2,
    positionInSet: 6,
    onyomi: ["ゲン"],
    kunyomi: ["あらわ.れる", "あらわ.す"],
    meanings: ["present", "existing", "actual", "appear"],
    strokeCount: 11,
    exampleWords: [
      { word: "現在", reading: "げんざい", meaning: "present, current" },
      { word: "現実", reading: "げんじつ", meaning: "reality, actuality" },
      { word: "表現", reading: "ひょうげん", meaning: "expression, representation" },
    ],
  },
  {
    id: "n3-047",
    character: "限",
    level: "N3",
    setIndex: 2,
    positionInSet: 7,
    onyomi: ["ゲン"],
    kunyomi: ["かぎ.る"],
    meanings: ["limit", "restrict", "bounds"],
    strokeCount: 9,
    exampleWords: [
      { word: "限界", reading: "げんかい", meaning: "limit, boundary" },
      { word: "制限", reading: "せいげん", meaning: "restriction, limitation" },
      { word: "期限", reading: "きげん", meaning: "deadline, time limit" },
    ],
  },
  {
    id: "n3-048",
    character: "個",
    level: "N3",
    setIndex: 2,
    positionInSet: 8,
    onyomi: ["コ"],
    kunyomi: [],
    meanings: ["individual", "counter for small items"],
    strokeCount: 10,
    exampleWords: [
      { word: "個人", reading: "こじん", meaning: "individual, personal" },
      { word: "個性", reading: "こせい", meaning: "individuality, personality" },
      { word: "個別", reading: "こべつ", meaning: "individual, separate" },
    ],
  },
  {
    id: "n3-049",
    character: "護",
    level: "N3",
    setIndex: 2,
    positionInSet: 9,
    onyomi: ["ゴ"],
    kunyomi: ["まも.る"],
    meanings: ["protect", "guard", "defend"],
    strokeCount: 20,
    exampleWords: [
      { word: "保護", reading: "ほご", meaning: "protection, preservation" },
      { word: "弁護士", reading: "べんごし", meaning: "lawyer, attorney" },
      { word: "看護師", reading: "かんごし", meaning: "nurse" },
    ],
  },
  {
    id: "n3-050",
    character: "向",
    level: "N3",
    setIndex: 2,
    positionInSet: 10,
    onyomi: ["コウ"],
    kunyomi: ["む.く", "む.ける", "む.かう", "む.こう"],
    meanings: ["direction", "face", "point toward"],
    strokeCount: 6,
    exampleWords: [
      { word: "方向", reading: "ほうこう", meaning: "direction, orientation" },
      { word: "向かう", reading: "むかう", meaning: "to face, to go toward" },
      { word: "傾向", reading: "けいこう", meaning: "tendency, trend" },
    ],
  },
  {
    id: "n3-051",
    character: "公",
    level: "N3",
    setIndex: 2,
    positionInSet: 11,
    onyomi: ["コウ", "ク"],
    kunyomi: ["おおやけ"],
    meanings: ["public", "official", "prince", "fair"],
    strokeCount: 4,
    exampleWords: [
      { word: "公園", reading: "こうえん", meaning: "park" },
      { word: "公共", reading: "こうきょう", meaning: "public" },
      { word: "公式", reading: "こうしき", meaning: "official, formal" },
    ],
  },
  {
    id: "n3-052",
    character: "効",
    level: "N3",
    setIndex: 2,
    positionInSet: 12,
    onyomi: ["コウ"],
    kunyomi: ["き.く"],
    meanings: ["effect", "benefit", "effective"],
    strokeCount: 8,
    exampleWords: [
      { word: "効果", reading: "こうか", meaning: "effect, efficacy" },
      { word: "有効", reading: "ゆうこう", meaning: "valid, effective" },
      { word: "効率", reading: "こうりつ", meaning: "efficiency" },
    ],
  },
  {
    id: "n3-053",
    character: "混",
    level: "N3",
    setIndex: 2,
    positionInSet: 13,
    onyomi: ["コン"],
    kunyomi: ["こ.む", "こ.ぜる", "ま.じる"],
    meanings: ["mix", "confused", "medley"],
    strokeCount: 11,
    exampleWords: [
      { word: "混雑", reading: "こんざつ", meaning: "congestion, crowding" },
      { word: "混乱", reading: "こんらん", meaning: "disorder, confusion" },
      { word: "混じる", reading: "まじる", meaning: "to be mixed, to be blended" },
    ],
  },
  {
    id: "n3-054",
    character: "差",
    level: "N3",
    setIndex: 2,
    positionInSet: 14,
    onyomi: ["サ"],
    kunyomi: ["さ.す"],
    meanings: ["difference", "variation", "margin", "distinction"],
    strokeCount: 10,
    exampleWords: [
      { word: "差別", reading: "さべつ", meaning: "discrimination" },
      { word: "格差", reading: "かくさ", meaning: "disparity, gap" },
      { word: "誤差", reading: "ごさ", meaning: "error, margin of error" },
    ],
  },
  {
    id: "n3-055",
    character: "採",
    level: "N3",
    setIndex: 2,
    positionInSet: 15,
    onyomi: ["サイ"],
    kunyomi: ["と.る"],
    meanings: ["pick", "gather", "adopt", "accept", "employ"],
    strokeCount: 11,
    exampleWords: [
      { word: "採用", reading: "さいよう", meaning: "adoption, hiring" },
      { word: "採点", reading: "さいてん", meaning: "grading, marking" },
      { word: "採集", reading: "さいしゅう", meaning: "collection, gathering" },
    ],
  },
  {
    id: "n3-056",
    character: "際",
    level: "N3",
    setIndex: 2,
    positionInSet: 16,
    onyomi: ["サイ"],
    kunyomi: ["きわ"],
    meanings: ["occasion", "time", "edge", "edge of", "when"],
    strokeCount: 14,
    exampleWords: [
      { word: "国際", reading: "こくさい", meaning: "international" },
      { word: "実際", reading: "じっさい", meaning: "actually, in practice" },
      { word: "交際", reading: "こうさい", meaning: "company, association" },
    ],
  },
  {
    id: "n3-057",
    character: "最",
    level: "N3",
    setIndex: 2,
    positionInSet: 17,
    onyomi: ["サイ"],
    kunyomi: ["もっと.も"],
    meanings: ["most", "utmost", "extremely"],
    strokeCount: 12,
    exampleWords: [
      { word: "最近", reading: "さいきん", meaning: "recently, lately" },
      { word: "最初", reading: "さいしょ", meaning: "first, beginning" },
      { word: "最後", reading: "さいご", meaning: "last, final" },
    ],
  },
  {
    id: "n3-058",
    character: "昨",
    level: "N3",
    setIndex: 2,
    positionInSet: 18,
    onyomi: ["サク"],
    kunyomi: [],
    meanings: ["yesterday", "previous"],
    strokeCount: 9,
    exampleWords: [
      { word: "昨日", reading: "きのう", meaning: "yesterday" },
      { word: "昨年", reading: "さくねん", meaning: "last year" },
      { word: "昨夜", reading: "さくや", meaning: "last night" },
    ],
  },
  {
    id: "n3-059",
    character: "察",
    level: "N3",
    setIndex: 2,
    positionInSet: 19,
    onyomi: ["サツ"],
    kunyomi: [],
    meanings: ["guess", "presume", "inspect", "observe"],
    strokeCount: 14,
    exampleWords: [
      { word: "観察", reading: "かんさつ", meaning: "observation" },
      { word: "警察", reading: "けいさつ", meaning: "police" },
      { word: "察する", reading: "さっする", meaning: "to guess, to infer" },
    ],
  },
  {
    id: "n3-060",
    character: "参",
    level: "N3",
    setIndex: 3,
    positionInSet: 0,
    onyomi: ["サン", "シン"],
    kunyomi: ["まい.る"],
    meanings: ["go", "visit", "attend", "three (formal)"],
    strokeCount: 8,
    exampleWords: [
      { word: "参加", reading: "さんか", meaning: "participation" },
      { word: "参考", reading: "さんこう", meaning: "reference, consultation" },
      { word: "持参", reading: "じさん", meaning: "bringing, carrying" },
    ],
  },
  {
    id: "n3-061",
    character: "産",
    level: "N3",
    setIndex: 3,
    positionInSet: 1,
    onyomi: ["サン"],
    kunyomi: ["う.む", "う.まれる", "うぶ"],
    meanings: ["produce", "give birth", "assets", "property"],
    strokeCount: 11,
    exampleWords: [
      { word: "産業", reading: "さんぎょう", meaning: "industry" },
      { word: "生産", reading: "せいさん", meaning: "production" },
      { word: "不動産", reading: "ふどうさん", meaning: "real estate" },
    ],
  },
  {
    id: "n3-062",
    character: "残",
    level: "N3",
    setIndex: 3,
    positionInSet: 2,
    onyomi: ["ザン"],
    kunyomi: ["のこ.る", "のこ.す"],
    meanings: ["remainder", "leftover", "continue", "remain"],
    strokeCount: 10,
    exampleWords: [
      { word: "残る", reading: "のこる", meaning: "to remain, to be left" },
      { word: "残念", reading: "ざんねん", meaning: "regret, disappointment" },
      { word: "残業", reading: "ざんぎょう", meaning: "overtime work" },
    ],
  },
  {
    id: "n3-063",
    character: "支",
    level: "N3",
    setIndex: 3,
    positionInSet: 3,
    onyomi: ["シ"],
    kunyomi: ["ささ.える"],
    meanings: ["branch", "support", "sustain"],
    strokeCount: 4,
    exampleWords: [
      { word: "支援", reading: "しえん", meaning: "support, assistance" },
      { word: "支店", reading: "してん", meaning: "branch office" },
      { word: "収支", reading: "しゅうし", meaning: "income and expenditure" },
    ],
  },
  {
    id: "n3-064",
    character: "資",
    level: "N3",
    setIndex: 3,
    positionInSet: 4,
    onyomi: ["シ"],
    kunyomi: [],
    meanings: ["assets", "resources", "capital", "data"],
    strokeCount: 13,
    exampleWords: [
      { word: "資料", reading: "しりょう", meaning: "materials, data" },
      { word: "資源", reading: "しげん", meaning: "resources" },
      { word: "投資", reading: "とうし", meaning: "investment" },
    ],
  },
  {
    id: "n3-065",
    character: "示",
    level: "N3",
    setIndex: 3,
    positionInSet: 5,
    onyomi: ["ジ", "シ"],
    kunyomi: ["しめ.す"],
    meanings: ["show", "indicate", "point out", "exhibit"],
    strokeCount: 5,
    exampleWords: [
      { word: "表示", reading: "ひょうじ", meaning: "display, indication" },
      { word: "指示", reading: "しじ", meaning: "instruction, direction" },
      { word: "示す", reading: "しめす", meaning: "to show, to indicate" },
    ],
  },
  {
    id: "n3-066",
    character: "識",
    level: "N3",
    setIndex: 3,
    positionInSet: 6,
    onyomi: ["シキ"],
    kunyomi: [],
    meanings: ["know", "discriminate", "knowledge"],
    strokeCount: 19,
    exampleWords: [
      { word: "知識", reading: "ちしき", meaning: "knowledge" },
      { word: "意識", reading: "いしき", meaning: "consciousness, awareness" },
      { word: "常識", reading: "じょうしき", meaning: "common sense" },
    ],
  },
  {
    id: "n3-067",
    character: "実",
    level: "N3",
    setIndex: 3,
    positionInSet: 7,
    onyomi: ["ジツ", "シツ"],
    kunyomi: ["み", "みの.る"],
    meanings: ["reality", "truth", "fact", "actual", "fruit"],
    strokeCount: 8,
    exampleWords: [
      { word: "実際", reading: "じっさい", meaning: "actuality, reality" },
      { word: "実験", reading: "じっけん", meaning: "experiment" },
      { word: "事実", reading: "じじつ", meaning: "fact, truth" },
    ],
  },
  {
    id: "n3-068",
    character: "質",
    level: "N3",
    setIndex: 3,
    positionInSet: 8,
    onyomi: ["シツ", "シチ", "チ"],
    kunyomi: [],
    meanings: ["quality", "nature", "substance", "pawn"],
    strokeCount: 15,
    exampleWords: [
      { word: "質問", reading: "しつもん", meaning: "question" },
      { word: "品質", reading: "ひんしつ", meaning: "quality (of goods)" },
      { word: "本質", reading: "ほんしつ", meaning: "essence, nature" },
    ],
  },
  {
    id: "n3-069",
    character: "取",
    level: "N3",
    setIndex: 3,
    positionInSet: 9,
    onyomi: ["シュ"],
    kunyomi: ["と.る"],
    meanings: ["take", "fetch", "pick up"],
    strokeCount: 8,
    exampleWords: [
      { word: "取る", reading: "とる", meaning: "to take, to get" },
      { word: "取り組む", reading: "とりくむ", meaning: "to tackle, to work on" },
      { word: "受け取る", reading: "うけとる", meaning: "to receive" },
    ],
  },
  {
    id: "n3-070",
    character: "種",
    level: "N3",
    setIndex: 3,
    positionInSet: 10,
    onyomi: ["シュ"],
    kunyomi: ["たね", "-ぐさ"],
    meanings: ["species", "type", "kind", "seed"],
    strokeCount: 14,
    exampleWords: [
      { word: "種類", reading: "しゅるい", meaning: "type, kind, variety" },
      { word: "各種", reading: "かくしゅ", meaning: "every kind, various" },
      { word: "人種", reading: "じんしゅ", meaning: "race (human)" },
    ],
  },
  {
    id: "n3-071",
    character: "初",
    level: "N3",
    setIndex: 3,
    positionInSet: 11,
    onyomi: ["ショ"],
    kunyomi: ["はじ.め", "はじ.めて", "はつ", "うい-"],
    meanings: ["first", "beginning", "original"],
    strokeCount: 7,
    exampleWords: [
      { word: "最初", reading: "さいしょ", meaning: "first, beginning" },
      { word: "初めて", reading: "はじめて", meaning: "for the first time" },
      { word: "初日", reading: "しょにち", meaning: "first day" },
    ],
  },
  {
    id: "n3-072",
    character: "笑",
    level: "N3",
    setIndex: 3,
    positionInSet: 12,
    onyomi: ["ショウ"],
    kunyomi: ["わら.う", "え.む"],
    meanings: ["laugh", "smile"],
    strokeCount: 10,
    exampleWords: [
      { word: "笑う", reading: "わらう", meaning: "to laugh, to smile" },
      { word: "笑顔", reading: "えがお", meaning: "smiling face" },
      { word: "苦笑", reading: "くしょう", meaning: "bitter smile, wry smile" },
    ],
  },
  {
    id: "n3-073",
    character: "賞",
    level: "N3",
    setIndex: 3,
    positionInSet: 13,
    onyomi: ["ショウ"],
    kunyomi: [],
    meanings: ["prize", "award", "commend"],
    strokeCount: 15,
    exampleWords: [
      { word: "賞", reading: "しょう", meaning: "prize, award" },
      { word: "受賞", reading: "じゅしょう", meaning: "winning a prize" },
      { word: "賞金", reading: "しょうきん", meaning: "prize money" },
    ],
  },
  {
    id: "n3-074",
    character: "情",
    level: "N3",
    setIndex: 3,
    positionInSet: 14,
    onyomi: ["ジョウ", "セイ"],
    kunyomi: ["なさ.け"],
    meanings: ["feelings", "emotion", "sympathy", "situation"],
    strokeCount: 11,
    exampleWords: [
      { word: "感情", reading: "かんじょう", meaning: "emotion, feeling" },
      { word: "情報", reading: "じょうほう", meaning: "information" },
      { word: "同情", reading: "どうじょう", meaning: "sympathy, compassion" },
    ],
  },
  {
    id: "n3-075",
    character: "状",
    level: "N3",
    setIndex: 3,
    positionInSet: 15,
    onyomi: ["ジョウ"],
    kunyomi: [],
    meanings: ["status", "condition", "circumstances"],
    strokeCount: 7,
    exampleWords: [
      { word: "状況", reading: "じょうきょう", meaning: "situation, circumstances" },
      { word: "現状", reading: "げんじょう", meaning: "present situation" },
      { word: "症状", reading: "しょうじょう", meaning: "symptoms" },
    ],
  },
  {
    id: "n3-076",
    character: "職",
    level: "N3",
    setIndex: 3,
    positionInSet: 16,
    onyomi: ["ショク"],
    kunyomi: [],
    meanings: ["employment", "occupation", "work"],
    strokeCount: 18,
    exampleWords: [
      { word: "職業", reading: "しょくぎょう", meaning: "occupation, profession" },
      { word: "就職", reading: "しゅうしょく", meaning: "getting a job" },
      { word: "職場", reading: "しょくば", meaning: "workplace" },
    ],
  },
  {
    id: "n3-077",
    character: "信",
    level: "N3",
    setIndex: 3,
    positionInSet: 17,
    onyomi: ["シン"],
    kunyomi: ["しん.じる"],
    meanings: ["trust", "believe", "faith"],
    strokeCount: 9,
    exampleWords: [
      { word: "信じる", reading: "しんじる", meaning: "to believe, to trust" },
      { word: "信頼", reading: "しんらい", meaning: "trust, reliance" },
      { word: "自信", reading: "じしん", meaning: "self-confidence" },
    ],
  },
  {
    id: "n3-078",
    character: "申",
    level: "N3",
    setIndex: 3,
    positionInSet: 18,
    onyomi: ["シン"],
    kunyomi: ["もう.す"],
    meanings: ["say", "report", "petition", "9th zodiac sign"],
    strokeCount: 5,
    exampleWords: [
      { word: "申し込む", reading: "もうしこむ", meaning: "to apply, to register" },
      { word: "申告", reading: "しんこく", meaning: "report, declaration" },
      { word: "申請", reading: "しんせい", meaning: "application, request" },
    ],
  },
  {
    id: "n3-079",
    character: "数",
    level: "N3",
    setIndex: 3,
    positionInSet: 19,
    onyomi: ["スウ", "ス"],
    kunyomi: ["かず", "かぞ.える"],
    meanings: ["number", "count", "several"],
    strokeCount: 13,
    exampleWords: [
      { word: "数字", reading: "すうじ", meaning: "numeral, figure" },
      { word: "多数", reading: "たすう", meaning: "large number, majority" },
      { word: "数学", reading: "すうがく", meaning: "mathematics" },
    ],
  },
  {
    id: "n3-080",
    character: "制",
    level: "N3",
    setIndex: 4,
    positionInSet: 0,
    onyomi: ["セイ"],
    kunyomi: [],
    meanings: ["system", "law", "regulate", "control"],
    strokeCount: 8,
    exampleWords: [
      { word: "制度", reading: "せいど", meaning: "system, institution" },
      { word: "規制", reading: "きせい", meaning: "regulation, restriction" },
      { word: "制限", reading: "せいげん", meaning: "restriction, limitation" },
    ],
  },
  {
    id: "n3-081",
    character: "成",
    level: "N3",
    setIndex: 4,
    positionInSet: 1,
    onyomi: ["セイ", "ジョウ"],
    kunyomi: ["な.る", "な.す"],
    meanings: ["become", "form", "achieve", "accomplish"],
    strokeCount: 6,
    exampleWords: [
      { word: "成功", reading: "せいこう", meaning: "success" },
      { word: "成長", reading: "せいちょう", meaning: "growth, development" },
      { word: "完成", reading: "かんせい", meaning: "completion" },
    ],
  },
  {
    id: "n3-082",
    character: "整",
    level: "N3",
    setIndex: 4,
    positionInSet: 2,
    onyomi: ["セイ"],
    kunyomi: ["ととの.える", "ととの.う"],
    meanings: ["organize", "arrange", "adjust"],
    strokeCount: 16,
    exampleWords: [
      { word: "整理", reading: "せいり", meaning: "arrangement, organization" },
      { word: "調整", reading: "ちょうせい", meaning: "adjustment, regulation" },
      { word: "整備", reading: "せいび", meaning: "maintenance, upkeep" },
    ],
  },
  {
    id: "n3-083",
    character: "清",
    level: "N3",
    setIndex: 4,
    positionInSet: 3,
    onyomi: ["セイ", "ショウ"],
    kunyomi: ["きよ.い", "きよ.める", "きよ.まる"],
    meanings: ["pure", "clean", "clear"],
    strokeCount: 11,
    exampleWords: [
      { word: "清潔", reading: "せいけつ", meaning: "clean, hygienic" },
      { word: "清書", reading: "せいしょ", meaning: "clean copy, final draft" },
      { word: "清掃", reading: "せいそう", meaning: "cleaning, cleanup" },
    ],
  },
  {
    id: "n3-084",
    character: "積",
    level: "N3",
    setIndex: 4,
    positionInSet: 4,
    onyomi: ["セキ"],
    kunyomi: ["つ.む", "つ.もる"],
    meanings: ["volume", "pile up", "accumulate"],
    strokeCount: 16,
    exampleWords: [
      { word: "積む", reading: "つむ", meaning: "to pile up, to accumulate" },
      { word: "面積", reading: "めんせき", meaning: "area, square measure" },
      { word: "積極的", reading: "せっきょくてき", meaning: "positive, proactive" },
    ],
  },
  {
    id: "n3-085",
    character: "責",
    level: "N3",
    setIndex: 4,
    positionInSet: 5,
    onyomi: ["セキ"],
    kunyomi: ["せ.める"],
    meanings: ["blame", "responsibility", "condemn"],
    strokeCount: 11,
    exampleWords: [
      { word: "責任", reading: "せきにん", meaning: "responsibility, duty" },
      { word: "責める", reading: "せめる", meaning: "to blame, to criticize" },
      { word: "自責", reading: "じせき", meaning: "self-reproach" },
    ],
  },
  {
    id: "n3-086",
    character: "節",
    level: "N3",
    setIndex: 4,
    positionInSet: 6,
    onyomi: ["セツ", "セチ"],
    kunyomi: ["ふし"],
    meanings: ["occasion", "season", "section", "joint"],
    strokeCount: 13,
    exampleWords: [
      { word: "季節", reading: "きせつ", meaning: "season" },
      { word: "節約", reading: "せつやく", meaning: "economizing, saving" },
      { word: "調節", reading: "ちょうせつ", meaning: "regulation, adjustment" },
    ],
  },
  {
    id: "n3-087",
    character: "専",
    level: "N3",
    setIndex: 4,
    positionInSet: 7,
    onyomi: ["セン"],
    kunyomi: ["もっぱ.ら"],
    meanings: ["specialty", "exclusive", "solely"],
    strokeCount: 9,
    exampleWords: [
      { word: "専門", reading: "せんもん", meaning: "specialty, expertise" },
      { word: "専用", reading: "せんよう", meaning: "exclusive use, dedicated" },
      { word: "専念", reading: "せんねん", meaning: "devoting oneself to" },
    ],
  },
  {
    id: "n3-088",
    character: "争",
    level: "N3",
    setIndex: 4,
    positionInSet: 8,
    onyomi: ["ソウ"],
    kunyomi: ["あらそ.う"],
    meanings: ["compete", "dispute", "quarrel", "contend"],
    strokeCount: 6,
    exampleWords: [
      { word: "競争", reading: "きょうそう", meaning: "competition, contest" },
      { word: "戦争", reading: "せんそう", meaning: "war, battle" },
      { word: "争う", reading: "あらそう", meaning: "to compete, to dispute" },
    ],
  },
  {
    id: "n3-089",
    character: "帯",
    level: "N3",
    setIndex: 4,
    positionInSet: 9,
    onyomi: ["タイ"],
    kunyomi: ["お.びる", "おび"],
    meanings: ["belt", "band", "carry", "wear"],
    strokeCount: 10,
    exampleWords: [
      { word: "携帯", reading: "けいたい", meaning: "carrying, mobile phone" },
      { word: "地帯", reading: "ちたい", meaning: "zone, area, region" },
      { word: "熱帯", reading: "ねったい", meaning: "tropics" },
    ],
  },
  {
    id: "n3-090",
    character: "態",
    level: "N3",
    setIndex: 4,
    positionInSet: 10,
    onyomi: ["タイ"],
    kunyomi: ["わざ"],
    meanings: ["attitude", "condition", "appearance"],
    strokeCount: 14,
    exampleWords: [
      { word: "態度", reading: "たいど", meaning: "attitude, manner" },
      { word: "状態", reading: "じょうたい", meaning: "state, condition" },
      { word: "事態", reading: "じたい", meaning: "situation, state of affairs" },
    ],
  },
  {
    id: "n3-091",
    character: "達",
    level: "N3",
    setIndex: 4,
    positionInSet: 11,
    onyomi: ["タツ", "ダチ"],
    kunyomi: ["た.つ"],
    meanings: ["achieve", "accomplish", "reach", "skilled"],
    strokeCount: 12,
    exampleWords: [
      { word: "達成", reading: "たっせい", meaning: "achievement, accomplishment" },
      { word: "友達", reading: "ともだち", meaning: "friend" },
      { word: "上達", reading: "じょうたつ", meaning: "improvement, progress" },
    ],
  },
  {
    id: "n3-092",
    character: "団",
    level: "N3",
    setIndex: 4,
    positionInSet: 12,
    onyomi: ["ダン", "トン"],
    kunyomi: ["かたまり"],
    meanings: ["group", "association", "organization", "party"],
    strokeCount: 6,
    exampleWords: [
      { word: "団体", reading: "だんたい", meaning: "group, organization" },
      { word: "集団", reading: "しゅうだん", meaning: "group, mass" },
      { word: "楽団", reading: "がくだん", meaning: "orchestra, band" },
    ],
  },
  {
    id: "n3-093",
    character: "置",
    level: "N3",
    setIndex: 4,
    positionInSet: 13,
    onyomi: ["チ"],
    kunyomi: ["お.く"],
    meanings: ["placement", "put", "set"],
    strokeCount: 13,
    exampleWords: [
      { word: "置く", reading: "おく", meaning: "to put, to place" },
      { word: "配置", reading: "はいち", meaning: "arrangement, placement" },
      { word: "処置", reading: "しょち", meaning: "measure, treatment" },
    ],
  },
  {
    id: "n3-094",
    character: "徴",
    level: "N3",
    setIndex: 4,
    positionInSet: 14,
    onyomi: ["チョウ"],
    kunyomi: ["しるし"],
    meanings: ["sign", "symptom", "collect", "levy", "summon"],
    strokeCount: 14,
    exampleWords: [
      { word: "特徴", reading: "とくちょう", meaning: "characteristic, feature" },
      { word: "象徴", reading: "しょうちょう", meaning: "symbol, emblem" },
      { word: "徴収", reading: "ちょうしゅう", meaning: "collection, levy" },
    ],
  },
  {
    id: "n3-095",
    character: "調",
    level: "N3",
    setIndex: 4,
    positionInSet: 15,
    onyomi: ["チョウ"],
    kunyomi: ["しら.べる", "しら.べ", "ととの.う", "ととの.える"],
    meanings: ["investigate", "tone", "tune", "prepare"],
    strokeCount: 15,
    exampleWords: [
      { word: "調べる", reading: "しらべる", meaning: "to investigate, to research" },
      { word: "調整", reading: "ちょうせい", meaning: "adjustment" },
      { word: "強調", reading: "きょうちょう", meaning: "emphasis, stress" },
    ],
  },
  {
    id: "n3-096",
    character: "追",
    level: "N3",
    setIndex: 4,
    positionInSet: 16,
    onyomi: ["ツイ"],
    kunyomi: ["お.う"],
    meanings: ["chase", "pursue", "follow"],
    strokeCount: 9,
    exampleWords: [
      { word: "追う", reading: "おう", meaning: "to chase, to pursue" },
      { word: "追加", reading: "ついか", meaning: "addition, supplement" },
      { word: "追求", reading: "ついきゅう", meaning: "pursuit, seeking" },
    ],
  },
  {
    id: "n3-097",
    character: "定",
    level: "N3",
    setIndex: 4,
    positionInSet: 17,
    onyomi: ["テイ", "ジョウ"],
    kunyomi: ["さだ.める", "さだ.まる", "さだ.か"],
    meanings: ["determine", "establish", "fix", "stable"],
    strokeCount: 8,
    exampleWords: [
      { word: "決定", reading: "けってい", meaning: "decision, determination" },
      { word: "定員", reading: "ていいん", meaning: "fixed number, capacity" },
      { word: "規定", reading: "きてい", meaning: "regulation, provisions" },
    ],
  },
  {
    id: "n3-098",
    character: "停",
    level: "N3",
    setIndex: 4,
    positionInSet: 18,
    onyomi: ["テイ"],
    kunyomi: ["と.まる", "と.める"],
    meanings: ["halt", "stop", "suspension"],
    strokeCount: 11,
    exampleWords: [
      { word: "停止", reading: "ていし", meaning: "stop, suspension" },
      { word: "停車", reading: "ていしゃ", meaning: "stopping a vehicle" },
      { word: "停電", reading: "ていでん", meaning: "power outage, blackout" },
    ],
  },
  {
    id: "n3-099",
    character: "得",
    level: "N3",
    setIndex: 4,
    positionInSet: 19,
    onyomi: ["トク"],
    kunyomi: ["え.る", "う.る"],
    meanings: ["gain", "get", "profit", "advantage", "acquire"],
    strokeCount: 11,
    exampleWords: [
      { word: "得る", reading: "える", meaning: "to get, to gain" },
      { word: "利得", reading: "りとく", meaning: "profit, gain" },
      { word: "納得", reading: "なっとく", meaning: "consent, understanding" },
    ],
  },
  {
    id: "n3-100",
    character: "難",
    level: "N3",
    setIndex: 5,
    positionInSet: 0,
    onyomi: ["ナン"],
    kunyomi: ["むずか.しい", "にく.い"],
    meanings: ["difficult", "hard", "trouble", "impossible"],
    strokeCount: 18,
    exampleWords: [
      { word: "難しい", reading: "むずかしい", meaning: "difficult, hard" },
      { word: "困難", reading: "こんなん", meaning: "difficulty, trouble" },
      { word: "難問", reading: "なんもん", meaning: "difficult question" },
    ],
  },
  {
    id: "n3-101",
    character: "認",
    level: "N3",
    setIndex: 5,
    positionInSet: 1,
    onyomi: ["ニン"],
    kunyomi: ["みと.める", "みと.め"],
    meanings: ["acknowledge", "admit", "recognize", "approve"],
    strokeCount: 14,
    exampleWords: [
      { word: "認める", reading: "みとめる", meaning: "to acknowledge, to approve" },
      { word: "確認", reading: "かくにん", meaning: "confirmation, verification" },
      { word: "承認", reading: "しょうにん", meaning: "approval, recognition" },
    ],
  },
  {
    id: "n3-102",
    character: "熱",
    level: "N3",
    setIndex: 5,
    positionInSet: 2,
    onyomi: ["ネツ"],
    kunyomi: ["あつ.い"],
    meanings: ["heat", "fever", "enthusiasm"],
    strokeCount: 15,
    exampleWords: [
      { word: "熱い", reading: "あつい", meaning: "hot (to the touch)" },
      { word: "熱心", reading: "ねっしん", meaning: "enthusiasm, zeal" },
      { word: "体温", reading: "たいおん", meaning: "body temperature" },
    ],
  },
  {
    id: "n3-103",
    character: "念",
    level: "N3",
    setIndex: 5,
    positionInSet: 3,
    onyomi: ["ネン"],
    kunyomi: [],
    meanings: ["wish", "idea", "thought", "intention"],
    strokeCount: 8,
    exampleWords: [
      { word: "念", reading: "ねん", meaning: "sense, feeling, thought" },
      { word: "残念", reading: "ざんねん", meaning: "regret, disappointment" },
      { word: "記念", reading: "きねん", meaning: "commemoration, memory" },
    ],
  },
  {
    id: "n3-104",
    character: "能",
    level: "N3",
    setIndex: 5,
    positionInSet: 4,
    onyomi: ["ノウ"],
    kunyomi: [],
    meanings: ["ability", "talent", "skill", "Noh play"],
    strokeCount: 10,
    exampleWords: [
      { word: "能力", reading: "のうりょく", meaning: "ability, capability" },
      { word: "可能", reading: "かのう", meaning: "possible" },
      { word: "機能", reading: "きのう", meaning: "function, capability" },
    ],
  },
  {
    id: "n3-105",
    character: "倍",
    level: "N3",
    setIndex: 5,
    positionInSet: 5,
    onyomi: ["バイ"],
    kunyomi: [],
    meanings: ["twice", "double", "times", "fold"],
    strokeCount: 10,
    exampleWords: [
      { word: "二倍", reading: "にばい", meaning: "twice, double" },
      { word: "倍増", reading: "ばいぞう", meaning: "doubling" },
      { word: "何倍", reading: "なんばい", meaning: "how many times" },
    ],
  },
  {
    id: "n3-106",
    character: "背",
    level: "N3",
    setIndex: 5,
    positionInSet: 6,
    onyomi: ["ハイ"],
    kunyomi: ["せ", "せい", "そむ.く", "そむ.ける"],
    meanings: ["stature", "height", "back", "turn away"],
    strokeCount: 9,
    exampleWords: [
      { word: "背中", reading: "せなか", meaning: "back (body part)" },
      { word: "背景", reading: "はいけい", meaning: "background, setting" },
      { word: "身長", reading: "しんちょう", meaning: "height, stature" },
    ],
  },
  {
    id: "n3-107",
    character: "破",
    level: "N3",
    setIndex: 5,
    positionInSet: 7,
    onyomi: ["ハ"],
    kunyomi: ["やぶ.る", "やぶ.れる"],
    meanings: ["rend", "tear", "break", "destroy", "defeat"],
    strokeCount: 10,
    exampleWords: [
      { word: "破壊", reading: "はかい", meaning: "destruction, demolition" },
      { word: "破る", reading: "やぶる", meaning: "to break, to tear, to defeat" },
      { word: "突破", reading: "とっぱ", meaning: "breaking through" },
    ],
  },
  {
    id: "n3-108",
    character: "変",
    level: "N3",
    setIndex: 5,
    positionInSet: 8,
    onyomi: ["ヘン"],
    kunyomi: ["か.わる", "か.える"],
    meanings: ["change", "strange", "unusual", "transform"],
    strokeCount: 9,
    exampleWords: [
      { word: "変わる", reading: "かわる", meaning: "to change, to transform" },
      { word: "変化", reading: "へんか", meaning: "change, variation" },
      { word: "大変", reading: "たいへん", meaning: "terrible, dreadful, very" },
    ],
  },
  {
    id: "n3-109",
    character: "表",
    level: "N3",
    setIndex: 5,
    positionInSet: 9,
    onyomi: ["ヒョウ"],
    kunyomi: ["おもて", "あらわ.れる", "あらわ.す"],
    meanings: ["surface", "table", "chart", "express", "show"],
    strokeCount: 8,
    exampleWords: [
      { word: "発表", reading: "はっぴょう", meaning: "announcement, presentation" },
      { word: "表現", reading: "ひょうげん", meaning: "expression" },
      { word: "代表", reading: "だいひょう", meaning: "representative, delegation" },
    ],
  },
  {
    id: "n3-110",
    character: "評",
    level: "N3",
    setIndex: 5,
    positionInSet: 10,
    onyomi: ["ヒョウ"],
    kunyomi: [],
    meanings: ["evaluate", "criticism", "comment"],
    strokeCount: 12,
    exampleWords: [
      { word: "評価", reading: "ひょうか", meaning: "evaluation, assessment" },
      { word: "批評", reading: "ひひょう", meaning: "criticism, critique" },
      { word: "好評", reading: "こうひょう", meaning: "favorable reputation" },
    ],
  },
  {
    id: "n3-111",
    character: "布",
    level: "N3",
    setIndex: 5,
    positionInSet: 11,
    onyomi: ["フ"],
    kunyomi: ["ぬの"],
    meanings: ["linen", "cloth", "spread", "distribute"],
    strokeCount: 5,
    exampleWords: [
      { word: "分布", reading: "ぶんぷ", meaning: "distribution" },
      { word: "布", reading: "ぬの", meaning: "cloth, fabric" },
      { word: "配布", reading: "はいふ", meaning: "distribution, delivery" },
    ],
  },
  {
    id: "n3-112",
    character: "復",
    level: "N3",
    setIndex: 5,
    positionInSet: 12,
    onyomi: ["フク"],
    kunyomi: [],
    meanings: ["restore", "return", "repeat", "recover"],
    strokeCount: 12,
    exampleWords: [
      { word: "回復", reading: "かいふく", meaning: "recovery, recuperation" },
      { word: "復習", reading: "ふくしゅう", meaning: "review, revision" },
      { word: "復元", reading: "ふくげん", meaning: "restoration, reconstruction" },
    ],
  },
  {
    id: "n3-113",
    character: "複",
    level: "N3",
    setIndex: 5,
    positionInSet: 13,
    onyomi: ["フク"],
    kunyomi: [],
    meanings: ["duplicate", "double", "compound", "multiple"],
    strokeCount: 14,
    exampleWords: [
      { word: "複雑", reading: "ふくざつ", meaning: "complicated, complex" },
      { word: "複数", reading: "ふくすう", meaning: "plural, multiple" },
      { word: "重複", reading: "じゅうふく", meaning: "duplication, repetition" },
    ],
  },
  {
    id: "n3-114",
    character: "分",
    level: "N3",
    setIndex: 5,
    positionInSet: 14,
    onyomi: ["ブン", "フン", "ブ"],
    kunyomi: ["わ.ける", "わ.かれる", "わ.かる"],
    meanings: ["part", "minute", "understand", "separate"],
    strokeCount: 4,
    exampleWords: [
      { word: "十分", reading: "じゅうぶん", meaning: "enough, sufficient" },
      { word: "自分", reading: "じぶん", meaning: "oneself" },
      { word: "分野", reading: "ぶんや", meaning: "field, sphere" },
    ],
  },
  {
    id: "n3-115",
    character: "平",
    level: "N3",
    setIndex: 5,
    positionInSet: 15,
    onyomi: ["ヘイ", "ビョウ"],
    kunyomi: ["たい.ら", "ひら"],
    meanings: ["flat", "level", "even", "peaceful", "ordinary"],
    strokeCount: 5,
    exampleWords: [
      { word: "平和", reading: "へいわ", meaning: "peace, harmony" },
      { word: "平均", reading: "へいきん", meaning: "average, mean" },
      { word: "水平", reading: "すいへい", meaning: "horizontal, level" },
    ],
  },
  {
    id: "n3-116",
    character: "保",
    level: "N3",
    setIndex: 5,
    positionInSet: 16,
    onyomi: ["ホ", "ホウ"],
    kunyomi: ["たも.つ"],
    meanings: ["protect", "maintain", "keep", "preserve"],
    strokeCount: 9,
    exampleWords: [
      { word: "保護", reading: "ほご", meaning: "protection, preservation" },
      { word: "確保", reading: "かくほ", meaning: "securing, ensuring" },
      { word: "保険", reading: "ほけん", meaning: "insurance" },
    ],
  },
  {
    id: "n3-117",
    character: "訪",
    level: "N3",
    setIndex: 5,
    positionInSet: 17,
    onyomi: ["ホウ"],
    kunyomi: ["おとず.れる", "たず.ねる"],
    meanings: ["visit", "call on"],
    strokeCount: 11,
    exampleWords: [
      { word: "訪問", reading: "ほうもん", meaning: "visit, call" },
      { word: "訪れる", reading: "おとずれる", meaning: "to visit, to arrive" },
      { word: "来訪", reading: "らいほう", meaning: "visit, calling on" },
    ],
  },
  {
    id: "n3-118",
    character: "務",
    level: "N3",
    setIndex: 5,
    positionInSet: 18,
    onyomi: ["ム"],
    kunyomi: ["つと.める", "つと.まる"],
    meanings: ["task", "duty", "serve", "work"],
    strokeCount: 11,
    exampleWords: [
      { word: "業務", reading: "ぎょうむ", meaning: "business, duties" },
      { word: "義務", reading: "ぎむ", meaning: "duty, obligation" },
      { word: "事務所", reading: "じむしょ", meaning: "office" },
    ],
  },
  {
    id: "n3-119",
    character: "命",
    level: "N3",
    setIndex: 5,
    positionInSet: 19,
    onyomi: ["メイ", "ミョウ"],
    kunyomi: ["いのち"],
    meanings: ["fate", "command", "life", "destiny"],
    strokeCount: 8,
    exampleWords: [
      { word: "命令", reading: "めいれい", meaning: "command, order" },
      { word: "生命", reading: "せいめい", meaning: "life" },
      { word: "運命", reading: "うんめい", meaning: "fate, destiny" },
    ],
  },
  {
    id: "n3-120",
    character: "予",
    level: "N3",
    setIndex: 6,
    positionInSet: 0,
    onyomi: ["ヨ"],
    kunyomi: ["あらかじ.め"],
    meanings: ["in advance", "beforehand", "preliminary"],
    strokeCount: 4,
    exampleWords: [
      { word: "予定", reading: "よてい", meaning: "plan, schedule" },
      { word: "予約", reading: "よやく", meaning: "reservation, appointment" },
      { word: "予測", reading: "よそく", meaning: "prediction, forecast" },
    ],
  },
  {
    id: "n3-121",
    character: "容",
    level: "N3",
    setIndex: 6,
    positionInSet: 1,
    onyomi: ["ヨウ"],
    kunyomi: [],
    meanings: ["contain", "form", "appearance", "accept"],
    strokeCount: 10,
    exampleWords: [
      { word: "内容", reading: "ないよう", meaning: "contents, subject matter" },
      { word: "容量", reading: "ようりょう", meaning: "capacity, volume" },
      { word: "美容", reading: "びよう", meaning: "beauty care, cosmetics" },
    ],
  },
  {
    id: "n3-122",
    character: "様",
    level: "N3",
    setIndex: 6,
    positionInSet: 2,
    onyomi: ["ヨウ"],
    kunyomi: ["さま"],
    meanings: ["manner", "situation", "-san (honorific)", "appearance"],
    strokeCount: 14,
    exampleWords: [
      { word: "様子", reading: "ようす", meaning: "situation, appearance, manner" },
      { word: "同様", reading: "どうよう", meaning: "similar, same" },
      { word: "多様", reading: "たよう", meaning: "diverse, varied" },
    ],
  },
  {
    id: "n3-123",
    character: "要",
    level: "N3",
    setIndex: 6,
    positionInSet: 3,
    onyomi: ["ヨウ"],
    kunyomi: ["い.る", "かなめ"],
    meanings: ["need", "require", "important", "main point"],
    strokeCount: 9,
    exampleWords: [
      { word: "重要", reading: "じゅうよう", meaning: "important, significant" },
      { word: "必要", reading: "ひつよう", meaning: "necessary, required" },
      { word: "要約", reading: "ようやく", meaning: "summary, abstract" },
    ],
  },
];
