import type { Kanji } from "./types";

export const N4_KANJI: Kanji[] = [
  {
    id: "n4-000",
    character: "悪",
    level: "N4",
    setIndex: 0,
    positionInSet: 0,
    onyomi: ["アク", "オ"],
    kunyomi: ["わる.い", "わる-", "あ.し", "にく.い"],
    meanings: ["bad", "evil", "wrong"],
    strokeCount: 11,
    exampleWords: [
      { word: "悪い", reading: "わるい", meaning: "bad, wrong" },
      { word: "悪人", reading: "あくにん", meaning: "villain, evil person" },
      { word: "最悪", reading: "さいあく", meaning: "worst" },
    ],
  },
  {
    id: "n4-001",
    character: "安",
    level: "N4",
    setIndex: 0,
    positionInSet: 1,
    onyomi: ["アン"],
    kunyomi: ["やす.い", "やす.まる", "やす"],
    meanings: ["cheap", "relax", "peaceful", "safe"],
    strokeCount: 6,
    exampleWords: [
      { word: "安い", reading: "やすい", meaning: "cheap, inexpensive" },
      { word: "安全", reading: "あんぜん", meaning: "safety, security" },
      { word: "安心", reading: "あんしん", meaning: "peace of mind" },
    ],
  },
  {
    id: "n4-002",
    character: "以",
    level: "N4",
    setIndex: 0,
    positionInSet: 2,
    onyomi: ["イ"],
    kunyomi: [],
    meanings: ["by means of", "because", "in view of", "compared with"],
    strokeCount: 5,
    exampleWords: [
      { word: "以上", reading: "いじょう", meaning: "more than, above" },
      { word: "以下", reading: "いか", meaning: "below, less than" },
      { word: "以前", reading: "いぜん", meaning: "before, formerly" },
    ],
  },
  {
    id: "n4-003",
    character: "医",
    level: "N4",
    setIndex: 0,
    positionInSet: 3,
    onyomi: ["イ"],
    kunyomi: [],
    meanings: ["doctor", "medicine"],
    strokeCount: 7,
    exampleWords: [
      { word: "医者", reading: "いしゃ", meaning: "doctor, physician" },
      { word: "医学", reading: "いがく", meaning: "medical science" },
      { word: "医院", reading: "いいん", meaning: "clinic, doctor's office" },
    ],
  },
  {
    id: "n4-004",
    character: "意",
    level: "N4",
    setIndex: 0,
    positionInSet: 4,
    onyomi: ["イ"],
    kunyomi: [],
    meanings: ["idea", "mind", "thought", "feeling", "meaning"],
    strokeCount: 13,
    exampleWords: [
      { word: "意味", reading: "いみ", meaning: "meaning, significance" },
      { word: "意見", reading: "いけん", meaning: "opinion, view" },
      { word: "注意", reading: "ちゅうい", meaning: "caution, attention" },
    ],
  },
  {
    id: "n4-005",
    character: "院",
    level: "N4",
    setIndex: 0,
    positionInSet: 5,
    onyomi: ["イン"],
    kunyomi: [],
    meanings: ["institution", "temple", "mansion", "school"],
    strokeCount: 10,
    exampleWords: [
      { word: "病院", reading: "びょういん", meaning: "hospital" },
      { word: "大学院", reading: "だいがくいん", meaning: "graduate school" },
      { word: "院長", reading: "いんちょう", meaning: "director of an institution" },
    ],
  },
  {
    id: "n4-006",
    character: "飲",
    level: "N4",
    setIndex: 0,
    positionInSet: 6,
    onyomi: ["イン"],
    kunyomi: ["の.む"],
    meanings: ["drink", "swallow"],
    strokeCount: 12,
    exampleWords: [
      { word: "飲む", reading: "のむ", meaning: "to drink" },
      { word: "飲み物", reading: "のみもの", meaning: "beverage, drink" },
      { word: "飲食", reading: "いんしょく", meaning: "food and drink" },
    ],
  },
  {
    id: "n4-007",
    character: "運",
    level: "N4",
    setIndex: 0,
    positionInSet: 7,
    onyomi: ["ウン"],
    kunyomi: ["はこ.ぶ"],
    meanings: ["carry", "luck", "destiny", "fate", "transport"],
    strokeCount: 12,
    exampleWords: [
      { word: "運動", reading: "うんどう", meaning: "exercise, movement" },
      { word: "運転", reading: "うんてん", meaning: "driving, operation" },
      { word: "運ぶ", reading: "はこぶ", meaning: "to carry, to transport" },
    ],
  },
  {
    id: "n4-008",
    character: "映",
    level: "N4",
    setIndex: 0,
    positionInSet: 8,
    onyomi: ["エイ"],
    kunyomi: ["うつ.る", "うつ.す", "は.える"],
    meanings: ["reflect", "project", "map on", "shine"],
    strokeCount: 9,
    exampleWords: [
      { word: "映画", reading: "えいが", meaning: "movie, film" },
      { word: "映す", reading: "うつす", meaning: "to project, to reflect" },
      { word: "上映", reading: "じょうえい", meaning: "screening, showing" },
    ],
  },
  {
    id: "n4-009",
    character: "英",
    level: "N4",
    setIndex: 0,
    positionInSet: 9,
    onyomi: ["エイ"],
    kunyomi: [],
    meanings: ["England", "excellent", "hero", "petal"],
    strokeCount: 8,
    exampleWords: [
      { word: "英語", reading: "えいご", meaning: "English language" },
      { word: "英国", reading: "えいこく", meaning: "England, Britain" },
      { word: "英文", reading: "えいぶん", meaning: "English text" },
    ],
  },
  {
    id: "n4-010",
    character: "駅",
    level: "N4",
    setIndex: 0,
    positionInSet: 10,
    onyomi: ["エキ"],
    kunyomi: [],
    meanings: ["station"],
    strokeCount: 14,
    exampleWords: [
      { word: "駅", reading: "えき", meaning: "station" },
      { word: "駅前", reading: "えきまえ", meaning: "in front of the station" },
      { word: "終点駅", reading: "しゅうてんえき", meaning: "terminal station" },
    ],
  },
  {
    id: "n4-011",
    character: "園",
    level: "N4",
    setIndex: 0,
    positionInSet: 11,
    onyomi: ["エン"],
    kunyomi: ["その"],
    meanings: ["garden", "park", "nursery school"],
    strokeCount: 13,
    exampleWords: [
      { word: "公園", reading: "こうえん", meaning: "park" },
      { word: "動物園", reading: "どうぶつえん", meaning: "zoo" },
      { word: "幼稚園", reading: "ようちえん", meaning: "kindergarten" },
    ],
  },
  {
    id: "n4-012",
    character: "遠",
    level: "N4",
    setIndex: 0,
    positionInSet: 12,
    onyomi: ["エン", "オン"],
    kunyomi: ["とお.い"],
    meanings: ["far", "distant", "remote"],
    strokeCount: 13,
    exampleWords: [
      { word: "遠い", reading: "とおい", meaning: "far, distant" },
      { word: "遠足", reading: "えんそく", meaning: "excursion, field trip" },
      { word: "永遠", reading: "えいえん", meaning: "eternity, permanence" },
    ],
  },
  {
    id: "n4-013",
    character: "横",
    level: "N4",
    setIndex: 0,
    positionInSet: 13,
    onyomi: ["オウ"],
    kunyomi: ["よこ"],
    meanings: ["beside", "side", "width", "horizontal"],
    strokeCount: 15,
    exampleWords: [
      { word: "横", reading: "よこ", meaning: "side, width, horizontal" },
      { word: "横断", reading: "おうだん", meaning: "crossing, traversal" },
      { word: "横断歩道", reading: "おうだんほどう", meaning: "pedestrian crossing" },
    ],
  },
  {
    id: "n4-014",
    character: "音",
    level: "N4",
    setIndex: 0,
    positionInSet: 14,
    onyomi: ["オン", "イン"],
    kunyomi: ["おと", "ね"],
    meanings: ["sound", "noise", "note"],
    strokeCount: 9,
    exampleWords: [
      { word: "音楽", reading: "おんがく", meaning: "music" },
      { word: "音声", reading: "おんせい", meaning: "voice, sound" },
      { word: "発音", reading: "はつおん", meaning: "pronunciation" },
    ],
  },
  {
    id: "n4-015",
    character: "家",
    level: "N4",
    setIndex: 0,
    positionInSet: 15,
    onyomi: ["カ", "ケ"],
    kunyomi: ["いえ", "や", "うち"],
    meanings: ["house", "home", "family", "expert"],
    strokeCount: 10,
    exampleWords: [
      { word: "家族", reading: "かぞく", meaning: "family" },
      { word: "家庭", reading: "かてい", meaning: "home, household" },
      { word: "家賃", reading: "やちん", meaning: "rent" },
    ],
  },
  {
    id: "n4-016",
    character: "化",
    level: "N4",
    setIndex: 0,
    positionInSet: 16,
    onyomi: ["カ", "ケ"],
    kunyomi: ["ば.ける", "ば.かす", "ふ.ける", "け.する"],
    meanings: ["change", "convert", "transform", "-ization"],
    strokeCount: 4,
    exampleWords: [
      { word: "文化", reading: "ぶんか", meaning: "culture" },
      { word: "変化", reading: "へんか", meaning: "change, variation" },
      { word: "化学", reading: "かがく", meaning: "chemistry" },
    ],
  },
  {
    id: "n4-017",
    character: "夏",
    level: "N4",
    setIndex: 0,
    positionInSet: 17,
    onyomi: ["カ", "ゲ"],
    kunyomi: ["なつ"],
    meanings: ["summer"],
    strokeCount: 10,
    exampleWords: [
      { word: "夏", reading: "なつ", meaning: "summer" },
      { word: "夏休み", reading: "なつやすみ", meaning: "summer vacation" },
      { word: "初夏", reading: "しょか", meaning: "early summer" },
    ],
  },
  {
    id: "n4-018",
    character: "会",
    level: "N4",
    setIndex: 0,
    positionInSet: 18,
    onyomi: ["カイ", "エ"],
    kunyomi: ["あ.う", "あ.わせる"],
    meanings: ["meeting", "association", "meet"],
    strokeCount: 6,
    exampleWords: [
      { word: "会社", reading: "かいしゃ", meaning: "company, corporation" },
      { word: "会議", reading: "かいぎ", meaning: "meeting, conference" },
      { word: "社会", reading: "しゃかい", meaning: "society" },
    ],
  },
  {
    id: "n4-019",
    character: "海",
    level: "N4",
    setIndex: 0,
    positionInSet: 19,
    onyomi: ["カイ"],
    kunyomi: ["うみ"],
    meanings: ["sea", "ocean"],
    strokeCount: 9,
    exampleWords: [
      { word: "海", reading: "うみ", meaning: "sea, ocean" },
      { word: "海外", reading: "かいがい", meaning: "overseas, abroad" },
      { word: "日本海", reading: "にほんかい", meaning: "Sea of Japan" },
    ],
  },
  {
    id: "n4-020",
    character: "開",
    level: "N4",
    setIndex: 1,
    positionInSet: 0,
    onyomi: ["カイ"],
    kunyomi: ["あ.ける", "あ.く", "あ.かす", "ひら.く", "ひら.き"],
    meanings: ["open", "unfold", "begin"],
    strokeCount: 12,
    exampleWords: [
      { word: "開く", reading: "ひらく", meaning: "to open" },
      { word: "開発", reading: "かいはつ", meaning: "development" },
      { word: "公開", reading: "こうかい", meaning: "open to the public" },
    ],
  },
  {
    id: "n4-021",
    character: "帰",
    level: "N4",
    setIndex: 1,
    positionInSet: 1,
    onyomi: ["キ"],
    kunyomi: ["かえ.る", "かえ.す"],
    meanings: ["return", "homecoming"],
    strokeCount: 10,
    exampleWords: [
      { word: "帰る", reading: "かえる", meaning: "to return, to go home" },
      { word: "帰国", reading: "きこく", meaning: "return to one's country" },
      { word: "帰宅", reading: "きたく", meaning: "returning home" },
    ],
  },
  {
    id: "n4-022",
    character: "起",
    level: "N4",
    setIndex: 1,
    positionInSet: 2,
    onyomi: ["キ"],
    kunyomi: ["お.きる", "お.こる", "お.こす"],
    meanings: ["rouse", "get up", "wake", "rise"],
    strokeCount: 10,
    exampleWords: [
      { word: "起きる", reading: "おきる", meaning: "to wake up, to get up" },
      { word: "起こす", reading: "おこす", meaning: "to wake someone up" },
      { word: "起床", reading: "きしょう", meaning: "getting up, rising" },
    ],
  },
  {
    id: "n4-023",
    character: "記",
    level: "N4",
    setIndex: 1,
    positionInSet: 3,
    onyomi: ["キ"],
    kunyomi: ["しる.す"],
    meanings: ["write", "record", "mark"],
    strokeCount: 10,
    exampleWords: [
      { word: "記念", reading: "きねん", meaning: "commemoration, memory" },
      { word: "日記", reading: "にっき", meaning: "diary" },
      { word: "記事", reading: "きじ", meaning: "article, news story" },
    ],
  },
  {
    id: "n4-024",
    character: "気",
    level: "N4",
    setIndex: 1,
    positionInSet: 4,
    onyomi: ["キ", "ケ"],
    kunyomi: [],
    meanings: ["spirit", "mind", "air", "atmosphere", "energy"],
    strokeCount: 6,
    exampleWords: [
      { word: "天気", reading: "てんき", meaning: "weather" },
      { word: "気分", reading: "きぶん", meaning: "feeling, mood" },
      { word: "気持ち", reading: "きもち", meaning: "feeling, sensation" },
    ],
  },
  {
    id: "n4-025",
    character: "急",
    level: "N4",
    setIndex: 1,
    positionInSet: 5,
    onyomi: ["キュウ"],
    kunyomi: ["いそ.ぐ"],
    meanings: ["hurry", "emergency", "sudden", "steep"],
    strokeCount: 9,
    exampleWords: [
      { word: "急ぐ", reading: "いそぐ", meaning: "to hurry, to rush" },
      { word: "急行", reading: "きゅうこう", meaning: "express train" },
      { word: "緊急", reading: "きんきゅう", meaning: "emergency, urgent" },
    ],
  },
  {
    id: "n4-026",
    character: "業",
    level: "N4",
    setIndex: 1,
    positionInSet: 6,
    onyomi: ["ギョウ", "ゴウ"],
    kunyomi: ["わざ"],
    meanings: ["business", "profession", "work", "karma"],
    strokeCount: 13,
    exampleWords: [
      { word: "授業", reading: "じゅぎょう", meaning: "class, lesson" },
      { word: "業務", reading: "ぎょうむ", meaning: "business, duties" },
      { word: "卒業", reading: "そつぎょう", meaning: "graduation" },
    ],
  },
  {
    id: "n4-027",
    character: "教",
    level: "N4",
    setIndex: 1,
    positionInSet: 7,
    onyomi: ["キョウ"],
    kunyomi: ["おし.える", "おそ.わる"],
    meanings: ["teach", "faith", "doctrine"],
    strokeCount: 11,
    exampleWords: [
      { word: "教える", reading: "おしえる", meaning: "to teach, to inform" },
      { word: "教室", reading: "きょうしつ", meaning: "classroom" },
      { word: "宗教", reading: "しゅうきょう", meaning: "religion" },
    ],
  },
  {
    id: "n4-028",
    character: "強",
    level: "N4",
    setIndex: 1,
    positionInSet: 8,
    onyomi: ["キョウ", "ゴウ"],
    kunyomi: ["つよ.い", "つよ.まる", "し.いる"],
    meanings: ["strong", "powerful", "intense"],
    strokeCount: 11,
    exampleWords: [
      { word: "強い", reading: "つよい", meaning: "strong, powerful" },
      { word: "勉強", reading: "べんきょう", meaning: "study" },
      { word: "強調", reading: "きょうちょう", meaning: "emphasis, stress" },
    ],
  },
  {
    id: "n4-029",
    character: "銀",
    level: "N4",
    setIndex: 1,
    positionInSet: 9,
    onyomi: ["ギン"],
    kunyomi: [],
    meanings: ["silver"],
    strokeCount: 14,
    exampleWords: [
      { word: "銀行", reading: "ぎんこう", meaning: "bank" },
      { word: "銀色", reading: "ぎんいろ", meaning: "silver color" },
      { word: "銀メダル", reading: "ぎんメダル", meaning: "silver medal" },
    ],
  },
  {
    id: "n4-030",
    character: "計",
    level: "N4",
    setIndex: 1,
    positionInSet: 10,
    onyomi: ["ケイ"],
    kunyomi: ["はか.る", "はか.らう"],
    meanings: ["plot", "plan", "scheme", "measure", "count", "total"],
    strokeCount: 9,
    exampleWords: [
      { word: "時計", reading: "とけい", meaning: "clock, watch" },
      { word: "計画", reading: "けいかく", meaning: "plan, project" },
      { word: "合計", reading: "ごうけい", meaning: "sum total" },
    ],
  },
  {
    id: "n4-031",
    character: "建",
    level: "N4",
    setIndex: 1,
    positionInSet: 11,
    onyomi: ["ケン", "コン"],
    kunyomi: ["た.てる", "た.て"],
    meanings: ["build", "construct"],
    strokeCount: 9,
    exampleWords: [
      { word: "建物", reading: "たてもの", meaning: "building" },
      { word: "建設", reading: "けんせつ", meaning: "construction" },
      { word: "建築", reading: "けんちく", meaning: "architecture, construction" },
    ],
  },
  {
    id: "n4-032",
    character: "見",
    level: "N4",
    setIndex: 1,
    positionInSet: 12,
    onyomi: ["ケン"],
    kunyomi: ["み.る", "み.える", "み.せる"],
    meanings: ["see", "look", "show", "appear"],
    strokeCount: 7,
    exampleWords: [
      { word: "見る", reading: "みる", meaning: "to see, to look" },
      { word: "意見", reading: "いけん", meaning: "opinion" },
      { word: "発見", reading: "はっけん", meaning: "discovery" },
    ],
  },
  {
    id: "n4-033",
    character: "研",
    level: "N4",
    setIndex: 1,
    positionInSet: 13,
    onyomi: ["ケン"],
    kunyomi: ["と.ぐ"],
    meanings: ["polish", "study", "sharpen"],
    strokeCount: 9,
    exampleWords: [
      { word: "研究", reading: "けんきゅう", meaning: "research, study" },
      { word: "研修", reading: "けんしゅう", meaning: "training, study" },
      { word: "研究所", reading: "けんきゅうじょ", meaning: "research institute" },
    ],
  },
  {
    id: "n4-034",
    character: "後",
    level: "N4",
    setIndex: 1,
    positionInSet: 14,
    onyomi: ["ゴ", "コウ"],
    kunyomi: ["のち", "うし.ろ", "あと", "おく.れる"],
    meanings: ["behind", "after", "later"],
    strokeCount: 9,
    exampleWords: [
      { word: "午後", reading: "ごご", meaning: "afternoon, PM" },
      { word: "後で", reading: "あとで", meaning: "later, afterwards" },
      { word: "最後", reading: "さいご", meaning: "last, final" },
    ],
  },
  {
    id: "n4-035",
    character: "語",
    level: "N4",
    setIndex: 1,
    positionInSet: 15,
    onyomi: ["ゴ"],
    kunyomi: ["かた.る", "かた.らう"],
    meanings: ["language", "word", "speech", "talk"],
    strokeCount: 14,
    exampleWords: [
      { word: "日本語", reading: "にほんご", meaning: "Japanese language" },
      { word: "語学", reading: "ごがく", meaning: "language study" },
      { word: "物語", reading: "ものがたり", meaning: "story, tale" },
    ],
  },
  {
    id: "n4-036",
    character: "高",
    level: "N4",
    setIndex: 1,
    positionInSet: 16,
    onyomi: ["コウ"],
    kunyomi: ["たか.い", "たか", "たか.まる", "たか.める"],
    meanings: ["tall", "high", "expensive"],
    strokeCount: 10,
    exampleWords: [
      { word: "高い", reading: "たかい", meaning: "tall, high, expensive" },
      { word: "高校", reading: "こうこう", meaning: "high school" },
      { word: "最高", reading: "さいこう", meaning: "highest, maximum, best" },
    ],
  },
  {
    id: "n4-037",
    character: "合",
    level: "N4",
    setIndex: 1,
    positionInSet: 17,
    onyomi: ["ゴウ", "ガッ", "カッ"],
    kunyomi: ["あ.う", "あ.わす", "あ.わせる"],
    meanings: ["fit", "suit", "join", "combine"],
    strokeCount: 6,
    exampleWords: [
      { word: "場合", reading: "ばあい", meaning: "case, situation" },
      { word: "合う", reading: "あう", meaning: "to fit, to suit" },
      { word: "試合", reading: "しあい", meaning: "match, game" },
    ],
  },
  {
    id: "n4-038",
    character: "黒",
    level: "N4",
    setIndex: 1,
    positionInSet: 18,
    onyomi: ["コク"],
    kunyomi: ["くろ", "くろ.い"],
    meanings: ["black"],
    strokeCount: 11,
    exampleWords: [
      { word: "黒い", reading: "くろい", meaning: "black" },
      { word: "黒板", reading: "こくばん", meaning: "blackboard" },
      { word: "黒字", reading: "くろじ", meaning: "surplus, black (financially)" },
    ],
  },
  {
    id: "n4-039",
    character: "今",
    level: "N4",
    setIndex: 1,
    positionInSet: 19,
    onyomi: ["コン", "キン"],
    kunyomi: ["いま"],
    meanings: ["now", "current", "present"],
    strokeCount: 4,
    exampleWords: [
      { word: "今日", reading: "きょう", meaning: "today" },
      { word: "今年", reading: "ことし", meaning: "this year" },
      { word: "今週", reading: "こんしゅう", meaning: "this week" },
    ],
  },
  {
    id: "n4-040",
    character: "才",
    level: "N4",
    setIndex: 2,
    positionInSet: 0,
    onyomi: ["サイ"],
    kunyomi: [],
    meanings: ["genius", "years old", "ability", "talent"],
    strokeCount: 3,
    exampleWords: [
      { word: "才能", reading: "さいのう", meaning: "talent, ability" },
      { word: "天才", reading: "てんさい", meaning: "genius" },
      { word: "二十歳", reading: "はたち", meaning: "20 years old" },
    ],
  },
  {
    id: "n4-041",
    character: "作",
    level: "N4",
    setIndex: 2,
    positionInSet: 1,
    onyomi: ["サク", "サ"],
    kunyomi: ["つく.る"],
    meanings: ["make", "create", "prepare", "write"],
    strokeCount: 7,
    exampleWords: [
      { word: "作る", reading: "つくる", meaning: "to make, to create" },
      { word: "作品", reading: "さくひん", meaning: "work of art, production" },
      { word: "作業", reading: "さぎょう", meaning: "work, operation" },
    ],
  },
  {
    id: "n4-042",
    character: "使",
    level: "N4",
    setIndex: 2,
    positionInSet: 2,
    onyomi: ["シ"],
    kunyomi: ["つか.う", "つか.い"],
    meanings: ["use", "employ", "exert"],
    strokeCount: 8,
    exampleWords: [
      { word: "使う", reading: "つかう", meaning: "to use" },
      { word: "大使館", reading: "たいしかん", meaning: "embassy" },
      { word: "使用", reading: "しよう", meaning: "use, employment" },
    ],
  },
  {
    id: "n4-043",
    character: "始",
    level: "N4",
    setIndex: 2,
    positionInSet: 3,
    onyomi: ["シ"],
    kunyomi: ["はじ.める", "はじ.まる"],
    meanings: ["begin", "start"],
    strokeCount: 8,
    exampleWords: [
      { word: "始まる", reading: "はじまる", meaning: "to begin, to start" },
      { word: "始める", reading: "はじめる", meaning: "to start, to commence" },
      { word: "開始", reading: "かいし", meaning: "start, commencement" },
    ],
  },
  {
    id: "n4-044",
    character: "試",
    level: "N4",
    setIndex: 2,
    positionInSet: 4,
    onyomi: ["シ"],
    kunyomi: ["こころ.みる", "ため.す"],
    meanings: ["test", "try", "attempt"],
    strokeCount: 13,
    exampleWords: [
      { word: "試験", reading: "しけん", meaning: "examination, test" },
      { word: "試合", reading: "しあい", meaning: "match, game" },
      { word: "試す", reading: "ためす", meaning: "to try, to test" },
    ],
  },
  {
    id: "n4-045",
    character: "思",
    level: "N4",
    setIndex: 2,
    positionInSet: 5,
    onyomi: ["シ"],
    kunyomi: ["おも.う"],
    meanings: ["think", "consider", "believe"],
    strokeCount: 9,
    exampleWords: [
      { word: "思う", reading: "おもう", meaning: "to think, to feel" },
      { word: "思い出", reading: "おもいで", meaning: "memory, recollection" },
      { word: "意思", reading: "いし", meaning: "intention, will" },
    ],
  },
  {
    id: "n4-046",
    character: "持",
    level: "N4",
    setIndex: 2,
    positionInSet: 6,
    onyomi: ["ジ"],
    kunyomi: ["も.つ"],
    meanings: ["hold", "have", "possess"],
    strokeCount: 9,
    exampleWords: [
      { word: "持つ", reading: "もつ", meaning: "to hold, to carry" },
      { word: "気持ち", reading: "きもち", meaning: "feeling, sensation" },
      { word: "持参", reading: "じさん", meaning: "bringing with oneself" },
    ],
  },
  {
    id: "n4-047",
    character: "室",
    level: "N4",
    setIndex: 2,
    positionInSet: 7,
    onyomi: ["シツ"],
    kunyomi: ["むろ"],
    meanings: ["room", "chamber", "apartment"],
    strokeCount: 9,
    exampleWords: [
      { word: "教室", reading: "きょうしつ", meaning: "classroom" },
      { word: "室内", reading: "しつない", meaning: "indoors, interior" },
      { word: "洋室", reading: "ようしつ", meaning: "Western-style room" },
    ],
  },
  {
    id: "n4-048",
    character: "写",
    level: "N4",
    setIndex: 2,
    positionInSet: 8,
    onyomi: ["シャ"],
    kunyomi: ["うつ.す", "うつ.る"],
    meanings: ["copy", "photograph", "depict"],
    strokeCount: 5,
    exampleWords: [
      { word: "写真", reading: "しゃしん", meaning: "photograph" },
      { word: "写す", reading: "うつす", meaning: "to copy, to photograph" },
      { word: "複写", reading: "ふくしゃ", meaning: "copy, duplicate" },
    ],
  },
  {
    id: "n4-049",
    character: "者",
    level: "N4",
    setIndex: 2,
    positionInSet: 9,
    onyomi: ["シャ"],
    kunyomi: ["もの"],
    meanings: ["person", "-er", "-or"],
    strokeCount: 8,
    exampleWords: [
      { word: "医者", reading: "いしゃ", meaning: "doctor" },
      { word: "記者", reading: "きしゃ", meaning: "journalist, reporter" },
      { word: "若者", reading: "わかもの", meaning: "young person, youth" },
    ],
  },
  {
    id: "n4-050",
    character: "弱",
    level: "N4",
    setIndex: 2,
    positionInSet: 10,
    onyomi: ["ジャク"],
    kunyomi: ["よわ.い", "よわ.る", "よわ.まる", "よわ.める"],
    meanings: ["weak", "frail"],
    strokeCount: 10,
    exampleWords: [
      { word: "弱い", reading: "よわい", meaning: "weak, frail" },
      { word: "弱点", reading: "じゃくてん", meaning: "weak point, weakness" },
      { word: "強弱", reading: "きょうじゃく", meaning: "strength and weakness" },
    ],
  },
  {
    id: "n4-051",
    character: "手",
    level: "N4",
    setIndex: 2,
    positionInSet: 11,
    onyomi: ["シュ"],
    kunyomi: ["て", "て-", "-て"],
    meanings: ["hand", "arm"],
    strokeCount: 4,
    exampleWords: [
      { word: "手紙", reading: "てがみ", meaning: "letter" },
      { word: "上手", reading: "じょうず", meaning: "skillful, good at" },
      { word: "手伝う", reading: "てつだう", meaning: "to help, to assist" },
    ],
  },
  {
    id: "n4-052",
    character: "主",
    level: "N4",
    setIndex: 2,
    positionInSet: 12,
    onyomi: ["シュ", "ス"],
    kunyomi: ["ぬし", "おも"],
    meanings: ["lord", "chief", "master", "main", "primary"],
    strokeCount: 5,
    exampleWords: [
      { word: "主人", reading: "しゅじん", meaning: "husband, master" },
      { word: "主語", reading: "しゅご", meaning: "subject (grammar)" },
      { word: "民主", reading: "みんしゅ", meaning: "democracy" },
    ],
  },
  {
    id: "n4-053",
    character: "集",
    level: "N4",
    setIndex: 2,
    positionInSet: 13,
    onyomi: ["シュウ"],
    kunyomi: ["あつ.まる", "あつ.める", "つど.う"],
    meanings: ["gather", "collect", "assemble"],
    strokeCount: 12,
    exampleWords: [
      { word: "集める", reading: "あつめる", meaning: "to collect, to gather" },
      { word: "集会", reading: "しゅうかい", meaning: "meeting, assembly" },
      { word: "編集", reading: "へんしゅう", meaning: "editing, compilation" },
    ],
  },
  {
    id: "n4-054",
    character: "住",
    level: "N4",
    setIndex: 2,
    positionInSet: 14,
    onyomi: ["ジュウ", "チュウ"],
    kunyomi: ["す.む", "す.まう"],
    meanings: ["dwell", "reside", "live"],
    strokeCount: 7,
    exampleWords: [
      { word: "住む", reading: "すむ", meaning: "to live, to reside" },
      { word: "住所", reading: "じゅうしょ", meaning: "address" },
      { word: "住宅", reading: "じゅうたく", meaning: "housing, residence" },
    ],
  },
  {
    id: "n4-055",
    character: "重",
    level: "N4",
    setIndex: 2,
    positionInSet: 15,
    onyomi: ["ジュウ", "チョウ"],
    kunyomi: ["おも.い", "かさ.ねる", "かさ.なる"],
    meanings: ["heavy", "pile up", "layer", "important"],
    strokeCount: 9,
    exampleWords: [
      { word: "重い", reading: "おもい", meaning: "heavy" },
      { word: "重要", reading: "じゅうよう", meaning: "important, essential" },
      { word: "体重", reading: "たいじゅう", meaning: "body weight" },
    ],
  },
  {
    id: "n4-056",
    character: "春",
    level: "N4",
    setIndex: 2,
    positionInSet: 16,
    onyomi: ["シュン"],
    kunyomi: ["はる"],
    meanings: ["spring"],
    strokeCount: 9,
    exampleWords: [
      { word: "春", reading: "はる", meaning: "spring" },
      { word: "春休み", reading: "はるやすみ", meaning: "spring vacation" },
      { word: "青春", reading: "せいしゅん", meaning: "youth, springtime of life" },
    ],
  },
  {
    id: "n4-057",
    character: "所",
    level: "N4",
    setIndex: 2,
    positionInSet: 17,
    onyomi: ["ショ"],
    kunyomi: ["ところ", "-どころ"],
    meanings: ["place", "location"],
    strokeCount: 8,
    exampleWords: [
      { word: "場所", reading: "ばしょ", meaning: "place, location" },
      { word: "住所", reading: "じゅうしょ", meaning: "address" },
      { word: "台所", reading: "だいどころ", meaning: "kitchen" },
    ],
  },
  {
    id: "n4-058",
    character: "暑",
    level: "N4",
    setIndex: 2,
    positionInSet: 18,
    onyomi: ["ショ"],
    kunyomi: ["あつ.い"],
    meanings: ["hot (weather)", "sultry"],
    strokeCount: 12,
    exampleWords: [
      { word: "暑い", reading: "あつい", meaning: "hot (weather)" },
      { word: "暑さ", reading: "あつさ", meaning: "heat, hotness" },
      { word: "猛暑", reading: "もうしょ", meaning: "extreme heat" },
    ],
  },
  {
    id: "n4-059",
    character: "少",
    level: "N4",
    setIndex: 2,
    positionInSet: 19,
    onyomi: ["ショウ"],
    kunyomi: ["すく.ない", "すこ.し"],
    meanings: ["few", "little", "small"],
    strokeCount: 4,
    exampleWords: [
      { word: "少ない", reading: "すくない", meaning: "few, little" },
      { word: "少し", reading: "すこし", meaning: "a little, a bit" },
      { word: "少年", reading: "しょうねん", meaning: "boy, youth" },
    ],
  },
  {
    id: "n4-060",
    character: "書",
    level: "N4",
    setIndex: 3,
    positionInSet: 0,
    onyomi: ["ショ"],
    kunyomi: ["か.く"],
    meanings: ["write", "book"],
    strokeCount: 10,
    exampleWords: [
      { word: "書く", reading: "かく", meaning: "to write" },
      { word: "教科書", reading: "きょうかしょ", meaning: "textbook" },
      { word: "図書館", reading: "としょかん", meaning: "library" },
    ],
  },
  {
    id: "n4-061",
    character: "食",
    level: "N4",
    setIndex: 3,
    positionInSet: 1,
    onyomi: ["ショク", "ジキ"],
    kunyomi: ["た.べる", "く.う", "く.らう"],
    meanings: ["eat", "food"],
    strokeCount: 9,
    exampleWords: [
      { word: "食べる", reading: "たべる", meaning: "to eat" },
      { word: "食事", reading: "しょくじ", meaning: "meal" },
      { word: "食堂", reading: "しょくどう", meaning: "cafeteria, dining hall" },
    ],
  },
  {
    id: "n4-062",
    character: "心",
    level: "N4",
    setIndex: 3,
    positionInSet: 2,
    onyomi: ["シン"],
    kunyomi: ["こころ"],
    meanings: ["heart", "mind", "spirit"],
    strokeCount: 4,
    exampleWords: [
      { word: "安心", reading: "あんしん", meaning: "peace of mind" },
      { word: "心配", reading: "しんぱい", meaning: "worry, concern" },
      { word: "熱心", reading: "ねっしん", meaning: "enthusiasm, zeal" },
    ],
  },
  {
    id: "n4-063",
    character: "新",
    level: "N4",
    setIndex: 3,
    positionInSet: 3,
    onyomi: ["シン"],
    kunyomi: ["あたら.しい", "あら.た", "にい-"],
    meanings: ["new"],
    strokeCount: 13,
    exampleWords: [
      { word: "新しい", reading: "あたらしい", meaning: "new" },
      { word: "新聞", reading: "しんぶん", meaning: "newspaper" },
      { word: "最新", reading: "さいしん", meaning: "newest, latest" },
    ],
  },
  {
    id: "n4-064",
    character: "親",
    level: "N4",
    setIndex: 3,
    positionInSet: 4,
    onyomi: ["シン"],
    kunyomi: ["おや", "したし.い", "したし.む"],
    meanings: ["parent", "intimacy", "relative", "affection"],
    strokeCount: 16,
    exampleWords: [
      { word: "親", reading: "おや", meaning: "parent" },
      { word: "両親", reading: "りょうしん", meaning: "parents" },
      { word: "親切", reading: "しんせつ", meaning: "kind, kindness" },
    ],
  },
  {
    id: "n4-065",
    character: "図",
    level: "N4",
    setIndex: 3,
    positionInSet: 5,
    onyomi: ["ズ", "ト"],
    kunyomi: ["はか.る"],
    meanings: ["map", "drawing", "diagram", "figure"],
    strokeCount: 7,
    exampleWords: [
      { word: "地図", reading: "ちず", meaning: "map" },
      { word: "図書館", reading: "としょかん", meaning: "library" },
      { word: "図形", reading: "ずけい", meaning: "figure, shape" },
    ],
  },
  {
    id: "n4-066",
    character: "頭",
    level: "N4",
    setIndex: 3,
    positionInSet: 6,
    onyomi: ["トウ", "ズ", "ト"],
    kunyomi: ["あたま", "かしら"],
    meanings: ["head", "leader", "top"],
    strokeCount: 16,
    exampleWords: [
      { word: "頭", reading: "あたま", meaning: "head" },
      { word: "頭痛", reading: "ずつう", meaning: "headache" },
      { word: "先頭", reading: "せんとう", meaning: "head, front, lead" },
    ],
  },
  {
    id: "n4-067",
    character: "声",
    level: "N4",
    setIndex: 3,
    positionInSet: 7,
    onyomi: ["セイ", "ショウ"],
    kunyomi: ["こえ", "こわ-"],
    meanings: ["voice", "sound"],
    strokeCount: 7,
    exampleWords: [
      { word: "声", reading: "こえ", meaning: "voice" },
      { word: "音声", reading: "おんせい", meaning: "voice, sound" },
      { word: "大声", reading: "おおごえ", meaning: "loud voice" },
    ],
  },
  {
    id: "n4-068",
    character: "先",
    level: "N4",
    setIndex: 3,
    positionInSet: 8,
    onyomi: ["セン"],
    kunyomi: ["さき", "ま.ず"],
    meanings: ["before", "ahead", "earlier", "future"],
    strokeCount: 6,
    exampleWords: [
      { word: "先生", reading: "せんせい", meaning: "teacher" },
      { word: "先週", reading: "せんしゅう", meaning: "last week" },
      { word: "先輩", reading: "せんぱい", meaning: "senior, upperclassman" },
    ],
  },
  {
    id: "n4-069",
    character: "船",
    level: "N4",
    setIndex: 3,
    positionInSet: 9,
    onyomi: ["セン"],
    kunyomi: ["ふね", "ふな-"],
    meanings: ["ship", "boat"],
    strokeCount: 11,
    exampleWords: [
      { word: "船", reading: "ふね", meaning: "ship, boat" },
      { word: "汽船", reading: "きせん", meaning: "steamship" },
      { word: "船長", reading: "せんちょう", meaning: "captain" },
    ],
  },
  {
    id: "n4-070",
    character: "全",
    level: "N4",
    setIndex: 3,
    positionInSet: 10,
    onyomi: ["ゼン"],
    kunyomi: ["まった.く", "すべ.て"],
    meanings: ["all", "whole", "entire", "complete"],
    strokeCount: 6,
    exampleWords: [
      { word: "全部", reading: "ぜんぶ", meaning: "all, everything" },
      { word: "全員", reading: "ぜんいん", meaning: "all members" },
      { word: "安全", reading: "あんぜん", meaning: "safety, security" },
    ],
  },
  {
    id: "n4-071",
    character: "走",
    level: "N4",
    setIndex: 3,
    positionInSet: 11,
    onyomi: ["ソウ"],
    kunyomi: ["はし.る"],
    meanings: ["run"],
    strokeCount: 7,
    exampleWords: [
      { word: "走る", reading: "はしる", meaning: "to run" },
      { word: "走者", reading: "そうしゃ", meaning: "runner" },
      { word: "競走", reading: "きょうそう", meaning: "race, running competition" },
    ],
  },
  {
    id: "n4-072",
    character: "速",
    level: "N4",
    setIndex: 3,
    positionInSet: 12,
    onyomi: ["ソク"],
    kunyomi: ["はや.い", "はや-", "はや.める", "すみ.やか"],
    meanings: ["quick", "fast", "speed"],
    strokeCount: 10,
    exampleWords: [
      { word: "速い", reading: "はやい", meaning: "fast, quick" },
      { word: "速度", reading: "そくど", meaning: "speed, velocity" },
      { word: "急速", reading: "きゅうそく", meaning: "rapid, swift" },
    ],
  },
  {
    id: "n4-073",
    character: "体",
    level: "N4",
    setIndex: 3,
    positionInSet: 13,
    onyomi: ["タイ", "テイ"],
    kunyomi: ["からだ"],
    meanings: ["body", "substance", "object"],
    strokeCount: 7,
    exampleWords: [
      { word: "体", reading: "からだ", meaning: "body" },
      { word: "体操", reading: "たいそう", meaning: "gymnastics, exercise" },
      { word: "全体", reading: "ぜんたい", meaning: "whole body, entirety" },
    ],
  },
  {
    id: "n4-074",
    character: "待",
    level: "N4",
    setIndex: 3,
    positionInSet: 14,
    onyomi: ["タイ"],
    kunyomi: ["ま.つ"],
    meanings: ["wait", "await", "expect"],
    strokeCount: 9,
    exampleWords: [
      { word: "待つ", reading: "まつ", meaning: "to wait" },
      { word: "期待", reading: "きたい", meaning: "expectation, hope" },
      { word: "待合室", reading: "まちあいしつ", meaning: "waiting room" },
    ],
  },
  {
    id: "n4-075",
    character: "台",
    level: "N4",
    setIndex: 3,
    positionInSet: 15,
    onyomi: ["ダイ", "タイ"],
    kunyomi: ["うてな"],
    meanings: ["table", "counter", "platform", "stand"],
    strokeCount: 5,
    exampleWords: [
      { word: "台所", reading: "だいどころ", meaning: "kitchen" },
      { word: "台風", reading: "たいふう", meaning: "typhoon" },
      { word: "舞台", reading: "ぶたい", meaning: "stage, theater" },
    ],
  },
  {
    id: "n4-076",
    character: "代",
    level: "N4",
    setIndex: 3,
    positionInSet: 16,
    onyomi: ["ダイ", "タイ"],
    kunyomi: ["か.わる", "かわ.る", "かわ.り", "か.える", "よ", "しろ"],
    meanings: ["generation", "age", "substitute", "price", "fee"],
    strokeCount: 5,
    exampleWords: [
      { word: "時代", reading: "じだい", meaning: "era, age, period" },
      { word: "代わり", reading: "かわり", meaning: "substitute, replacement" },
      { word: "現代", reading: "げんだい", meaning: "modern times, present age" },
    ],
  },
  {
    id: "n4-077",
    character: "大",
    level: "N4",
    setIndex: 3,
    positionInSet: 17,
    onyomi: ["ダイ", "タイ"],
    kunyomi: ["おお-", "おお.きい", "おお.いに"],
    meanings: ["large", "big", "great"],
    strokeCount: 3,
    exampleWords: [
      { word: "大学", reading: "だいがく", meaning: "university" },
      { word: "大切", reading: "たいせつ", meaning: "important, precious" },
      { word: "大丈夫", reading: "だいじょうぶ", meaning: "all right, okay" },
    ],
  },
  {
    id: "n4-078",
    character: "地",
    level: "N4",
    setIndex: 3,
    positionInSet: 18,
    onyomi: ["チ", "ジ"],
    kunyomi: [],
    meanings: ["ground", "earth", "land", "place"],
    strokeCount: 6,
    exampleWords: [
      { word: "地図", reading: "ちず", meaning: "map" },
      { word: "地下", reading: "ちか", meaning: "underground, basement" },
      { word: "地震", reading: "じしん", meaning: "earthquake" },
    ],
  },
  {
    id: "n4-079",
    character: "知",
    level: "N4",
    setIndex: 3,
    positionInSet: 19,
    onyomi: ["チ"],
    kunyomi: ["し.る", "し.らせる"],
    meanings: ["know", "wisdom"],
    strokeCount: 8,
    exampleWords: [
      { word: "知る", reading: "しる", meaning: "to know, to be aware" },
      { word: "知識", reading: "ちしき", meaning: "knowledge" },
      { word: "通知", reading: "つうち", meaning: "notification, notice" },
    ],
  },
  {
    id: "n4-080",
    character: "昼",
    level: "N4",
    setIndex: 4,
    positionInSet: 0,
    onyomi: ["チュウ"],
    kunyomi: ["ひる"],
    meanings: ["noon", "daytime", "lunch"],
    strokeCount: 9,
    exampleWords: [
      { word: "昼", reading: "ひる", meaning: "noon, daytime" },
      { word: "昼ご飯", reading: "ひるごはん", meaning: "lunch" },
      { word: "昼間", reading: "ひるま", meaning: "daytime" },
    ],
  },
  {
    id: "n4-081",
    character: "長",
    level: "N4",
    setIndex: 4,
    positionInSet: 1,
    onyomi: ["チョウ"],
    kunyomi: ["なが.い", "おさ"],
    meanings: ["long", "leader", "chief", "head"],
    strokeCount: 8,
    exampleWords: [
      { word: "長い", reading: "ながい", meaning: "long" },
      { word: "社長", reading: "しゃちょう", meaning: "company president" },
      { word: "長所", reading: "ちょうしょ", meaning: "strong point, merit" },
    ],
  },
  {
    id: "n4-082",
    character: "通",
    level: "N4",
    setIndex: 4,
    positionInSet: 2,
    onyomi: ["ツウ", "ツ"],
    kunyomi: ["とお.る", "とお.す", "かよ.う"],
    meanings: ["pass through", "commute", "notify"],
    strokeCount: 10,
    exampleWords: [
      { word: "通る", reading: "とおる", meaning: "to pass through" },
      { word: "交通", reading: "こうつう", meaning: "traffic, transportation" },
      { word: "普通", reading: "ふつう", meaning: "ordinary, normal" },
    ],
  },
  {
    id: "n4-083",
    character: "店",
    level: "N4",
    setIndex: 4,
    positionInSet: 3,
    onyomi: ["テン"],
    kunyomi: ["みせ"],
    meanings: ["store", "shop"],
    strokeCount: 8,
    exampleWords: [
      { word: "お店", reading: "おみせ", meaning: "store, shop" },
      { word: "本店", reading: "ほんてん", meaning: "main store, headquarters" },
      { word: "店員", reading: "てんいん", meaning: "store clerk, salesperson" },
    ],
  },
  {
    id: "n4-084",
    character: "天",
    level: "N4",
    setIndex: 4,
    positionInSet: 4,
    onyomi: ["テン"],
    kunyomi: ["あめ", "あま-"],
    meanings: ["heavens", "sky", "god"],
    strokeCount: 4,
    exampleWords: [
      { word: "天気", reading: "てんき", meaning: "weather" },
      { word: "天才", reading: "てんさい", meaning: "genius" },
      { word: "天国", reading: "てんごく", meaning: "heaven, paradise" },
    ],
  },
  {
    id: "n4-085",
    character: "転",
    level: "N4",
    setIndex: 4,
    positionInSet: 5,
    onyomi: ["テン"],
    kunyomi: ["ころ.がる", "ころ.げる", "ころ.がす", "ころ.ぶ"],
    meanings: ["revolve", "turn around", "change", "tumble"],
    strokeCount: 11,
    exampleWords: [
      { word: "運転", reading: "うんてん", meaning: "driving, operation" },
      { word: "転ぶ", reading: "ころぶ", meaning: "to fall down" },
      { word: "回転", reading: "かいてん", meaning: "rotation, revolution" },
    ],
  },
  {
    id: "n4-086",
    character: "動",
    level: "N4",
    setIndex: 4,
    positionInSet: 6,
    onyomi: ["ドウ"],
    kunyomi: ["うご.く", "うご.かす"],
    meanings: ["move", "motion", "action"],
    strokeCount: 11,
    exampleWords: [
      { word: "動く", reading: "うごく", meaning: "to move" },
      { word: "運動", reading: "うんどう", meaning: "exercise, movement" },
      { word: "活動", reading: "かつどう", meaning: "activity, action" },
    ],
  },
  {
    id: "n4-087",
    character: "道",
    level: "N4",
    setIndex: 4,
    positionInSet: 7,
    onyomi: ["ドウ", "トウ"],
    kunyomi: ["みち"],
    meanings: ["road", "way", "path", "street"],
    strokeCount: 12,
    exampleWords: [
      { word: "道", reading: "みち", meaning: "road, path, way" },
      { word: "北海道", reading: "ほっかいどう", meaning: "Hokkaido" },
      { word: "道路", reading: "どうろ", meaning: "road, highway" },
    ],
  },
  {
    id: "n4-088",
    character: "読",
    level: "N4",
    setIndex: 4,
    positionInSet: 8,
    onyomi: ["ドク", "トク", "トウ"],
    kunyomi: ["よ.む"],
    meanings: ["read"],
    strokeCount: 14,
    exampleWords: [
      { word: "読む", reading: "よむ", meaning: "to read" },
      { word: "読書", reading: "どくしょ", meaning: "reading (books)" },
      { word: "読者", reading: "どくしゃ", meaning: "reader" },
    ],
  },
  {
    id: "n4-089",
    character: "肉",
    level: "N4",
    setIndex: 4,
    positionInSet: 9,
    onyomi: ["ニク"],
    kunyomi: [],
    meanings: ["meat", "flesh"],
    strokeCount: 6,
    exampleWords: [
      { word: "肉", reading: "にく", meaning: "meat, flesh" },
      { word: "牛肉", reading: "ぎゅうにく", meaning: "beef" },
      { word: "筋肉", reading: "きんにく", meaning: "muscle" },
    ],
  },
  {
    id: "n4-090",
    character: "入",
    level: "N4",
    setIndex: 4,
    positionInSet: 10,
    onyomi: ["ニュウ"],
    kunyomi: ["い.る", "-い.る", "-い.り", "い.れる", "はい.る"],
    meanings: ["enter", "insert", "join"],
    strokeCount: 2,
    exampleWords: [
      { word: "入る", reading: "はいる", meaning: "to enter, to go in" },
      { word: "入学", reading: "にゅうがく", meaning: "school admission" },
      { word: "輸入", reading: "ゆにゅう", meaning: "import" },
    ],
  },
  {
    id: "n4-091",
    character: "年",
    level: "N4",
    setIndex: 4,
    positionInSet: 11,
    onyomi: ["ネン"],
    kunyomi: ["とし"],
    meanings: ["year", "age"],
    strokeCount: 6,
    exampleWords: [
      { word: "来年", reading: "らいねん", meaning: "next year" },
      { word: "毎年", reading: "まいとし", meaning: "every year" },
      { word: "年齢", reading: "ねんれい", meaning: "age" },
    ],
  },
  {
    id: "n4-092",
    character: "乗",
    level: "N4",
    setIndex: 4,
    positionInSet: 12,
    onyomi: ["ジョウ"],
    kunyomi: ["の.る", "の.せる"],
    meanings: ["ride", "board", "get on", "multiply"],
    strokeCount: 9,
    exampleWords: [
      { word: "乗る", reading: "のる", meaning: "to ride, to board" },
      { word: "乗客", reading: "じょうきゃく", meaning: "passenger" },
      { word: "乗り換え", reading: "のりかえ", meaning: "transfer, change" },
    ],
  },
  {
    id: "n4-093",
    character: "配",
    level: "N4",
    setIndex: 4,
    positionInSet: 13,
    onyomi: ["ハイ"],
    kunyomi: ["くば.る"],
    meanings: ["distribute", "deliver", "spouse", "worry"],
    strokeCount: 10,
    exampleWords: [
      { word: "心配", reading: "しんぱい", meaning: "worry, concern" },
      { word: "配る", reading: "くばる", meaning: "to distribute, to hand out" },
      { word: "宅配", reading: "たくはい", meaning: "home delivery" },
    ],
  },
  {
    id: "n4-094",
    character: "発",
    level: "N4",
    setIndex: 4,
    positionInSet: 14,
    onyomi: ["ハツ", "ホツ"],
    kunyomi: [],
    meanings: ["discharge", "depart", "emit", "start", "publish"],
    strokeCount: 9,
    exampleWords: [
      { word: "発表", reading: "はっぴょう", meaning: "announcement, presentation" },
      { word: "出発", reading: "しゅっぱつ", meaning: "departure" },
      { word: "発音", reading: "はつおん", meaning: "pronunciation" },
    ],
  },
  {
    id: "n4-095",
    character: "花",
    level: "N4",
    setIndex: 4,
    positionInSet: 15,
    onyomi: ["カ"],
    kunyomi: ["はな"],
    meanings: ["flower", "blossom"],
    strokeCount: 7,
    exampleWords: [
      { word: "花", reading: "はな", meaning: "flower, blossom" },
      { word: "花火", reading: "はなび", meaning: "fireworks" },
      { word: "生花", reading: "せいか", meaning: "fresh flowers" },
    ],
  },
  {
    id: "n4-096",
    character: "話",
    level: "N4",
    setIndex: 4,
    positionInSet: 16,
    onyomi: ["ワ"],
    kunyomi: ["はな.す", "はなし"],
    meanings: ["tale", "talk", "speak"],
    strokeCount: 13,
    exampleWords: [
      { word: "話す", reading: "はなす", meaning: "to speak, to talk" },
      { word: "電話", reading: "でんわ", meaning: "telephone" },
      { word: "会話", reading: "かいわ", meaning: "conversation" },
    ],
  },
  {
    id: "n4-097",
    character: "晴",
    level: "N4",
    setIndex: 4,
    positionInSet: 17,
    onyomi: ["セイ"],
    kunyomi: ["は.れる", "は.れ", "は.らす"],
    meanings: ["clear up", "fine weather"],
    strokeCount: 12,
    exampleWords: [
      { word: "晴れ", reading: "はれ", meaning: "fine weather, sunny" },
      { word: "晴れる", reading: "はれる", meaning: "to clear up (weather)" },
      { word: "晴天", reading: "せいてん", meaning: "fine weather, clear sky" },
    ],
  },
  {
    id: "n4-098",
    character: "半",
    level: "N4",
    setIndex: 4,
    positionInSet: 18,
    onyomi: ["ハン"],
    kunyomi: ["なか.ば"],
    meanings: ["half", "middle", "odd number"],
    strokeCount: 5,
    exampleWords: [
      { word: "半分", reading: "はんぶん", meaning: "half" },
      { word: "一時半", reading: "いちじはん", meaning: "one thirty" },
      { word: "前半", reading: "ぜんはん", meaning: "first half" },
    ],
  },
  {
    id: "n4-099",
    character: "番",
    level: "N4",
    setIndex: 4,
    positionInSet: 19,
    onyomi: ["バン"],
    kunyomi: ["つが.い"],
    meanings: ["number", "order", "turn", "watch", "guard"],
    strokeCount: 12,
    exampleWords: [
      { word: "番号", reading: "ばんごう", meaning: "number" },
      { word: "一番", reading: "いちばん", meaning: "number one, best, most" },
      { word: "番組", reading: "ばんぐみ", meaning: "program (TV, radio)" },
    ],
  },
  {
    id: "n4-100",
    character: "病",
    level: "N4",
    setIndex: 5,
    positionInSet: 0,
    onyomi: ["ビョウ", "ヘイ"],
    kunyomi: ["や.む", "やまい"],
    meanings: ["ill", "sick", "disease"],
    strokeCount: 10,
    exampleWords: [
      { word: "病気", reading: "びょうき", meaning: "illness, sickness" },
      { word: "病院", reading: "びょういん", meaning: "hospital" },
      { word: "病人", reading: "びょうにん", meaning: "sick person, patient" },
    ],
  },
  {
    id: "n4-101",
    character: "秒",
    level: "N4",
    setIndex: 5,
    positionInSet: 1,
    onyomi: ["ビョウ"],
    kunyomi: [],
    meanings: ["second (time)"],
    strokeCount: 9,
    exampleWords: [
      { word: "秒", reading: "びょう", meaning: "second (unit of time)" },
      { word: "一秒", reading: "いちびょう", meaning: "one second" },
      { word: "秒針", reading: "びょうしん", meaning: "second hand (clock)" },
    ],
  },
  {
    id: "n4-102",
    character: "不",
    level: "N4",
    setIndex: 5,
    positionInSet: 2,
    onyomi: ["フ", "ブ"],
    kunyomi: [],
    meanings: ["negative", "non-", "bad", "ugly", "clumsy"],
    strokeCount: 4,
    exampleWords: [
      { word: "不便", reading: "ふべん", meaning: "inconvenient" },
      { word: "不安", reading: "ふあん", meaning: "anxiety, unease" },
      { word: "不満", reading: "ふまん", meaning: "dissatisfaction" },
    ],
  },
  {
    id: "n4-103",
    character: "服",
    level: "N4",
    setIndex: 5,
    positionInSet: 3,
    onyomi: ["フク"],
    kunyomi: [],
    meanings: ["clothing", "obey", "serve", "undergo"],
    strokeCount: 8,
    exampleWords: [
      { word: "服", reading: "ふく", meaning: "clothing, garment" },
      { word: "洋服", reading: "ようふく", meaning: "Western clothes" },
      { word: "制服", reading: "せいふく", meaning: "uniform" },
    ],
  },
  {
    id: "n4-104",
    character: "文",
    level: "N4",
    setIndex: 5,
    positionInSet: 4,
    onyomi: ["ブン", "モン"],
    kunyomi: ["ふみ"],
    meanings: ["sentence", "writing", "letter", "literature"],
    strokeCount: 4,
    exampleWords: [
      { word: "文章", reading: "ぶんしょう", meaning: "sentence, writing" },
      { word: "作文", reading: "さくぶん", meaning: "composition, essay" },
      { word: "文化", reading: "ぶんか", meaning: "culture" },
    ],
  },
  {
    id: "n4-105",
    character: "別",
    level: "N4",
    setIndex: 5,
    positionInSet: 5,
    onyomi: ["ベツ"],
    kunyomi: ["わか.れる", "わ.ける"],
    meanings: ["separate", "another", "different"],
    strokeCount: 7,
    exampleWords: [
      { word: "別れる", reading: "わかれる", meaning: "to separate, to part" },
      { word: "特別", reading: "とくべつ", meaning: "special, particular" },
      { word: "性別", reading: "せいべつ", meaning: "sex, gender" },
    ],
  },
  {
    id: "n4-106",
    character: "勉",
    level: "N4",
    setIndex: 5,
    positionInSet: 6,
    onyomi: ["ベン"],
    kunyomi: ["つと.める"],
    meanings: ["exertion", "endeavor", "diligence", "study"],
    strokeCount: 10,
    exampleWords: [
      { word: "勉強", reading: "べんきょう", meaning: "study" },
      { word: "勤勉", reading: "きんべん", meaning: "diligence, hardworking" },
    ],
  },
  {
    id: "n4-107",
    character: "歩",
    level: "N4",
    setIndex: 5,
    positionInSet: 7,
    onyomi: ["ホ", "ブ", "フ"],
    kunyomi: ["ある.く", "あゆ.む"],
    meanings: ["walk", "step", "pace"],
    strokeCount: 8,
    exampleWords: [
      { word: "歩く", reading: "あるく", meaning: "to walk" },
      { word: "散歩", reading: "さんぽ", meaning: "walk, stroll" },
      { word: "進歩", reading: "しんぽ", meaning: "progress, advance" },
    ],
  },
  {
    id: "n4-108",
    character: "方",
    level: "N4",
    setIndex: 5,
    positionInSet: 8,
    onyomi: ["ホウ"],
    kunyomi: ["かた", "-かた", "-がた"],
    meanings: ["direction", "way", "person", "method"],
    strokeCount: 4,
    exampleWords: [
      { word: "方法", reading: "ほうほう", meaning: "method, way" },
      { word: "地方", reading: "ちほう", meaning: "region, area, province" },
      { word: "行き方", reading: "いきかた", meaning: "how to get there" },
    ],
  },
  {
    id: "n4-109",
    character: "北",
    level: "N4",
    setIndex: 5,
    positionInSet: 9,
    onyomi: ["ホク"],
    kunyomi: ["きた"],
    meanings: ["north"],
    strokeCount: 5,
    exampleWords: [
      { word: "北", reading: "きた", meaning: "north" },
      { word: "北海道", reading: "ほっかいどう", meaning: "Hokkaido" },
      { word: "北西", reading: "ほくせい", meaning: "northwest" },
    ],
  },
  {
    id: "n4-110",
    character: "母",
    level: "N4",
    setIndex: 5,
    positionInSet: 10,
    onyomi: ["ボ"],
    kunyomi: ["はは", "かあ"],
    meanings: ["mother"],
    strokeCount: 5,
    exampleWords: [
      { word: "母", reading: "はは", meaning: "mother" },
      { word: "母親", reading: "ははおや", meaning: "mother, maternal" },
      { word: "母国", reading: "ぼこく", meaning: "one's home country" },
    ],
  },
  {
    id: "n4-111",
    character: "毎",
    level: "N4",
    setIndex: 5,
    positionInSet: 11,
    onyomi: ["マイ"],
    kunyomi: [],
    meanings: ["every", "each"],
    strokeCount: 6,
    exampleWords: [
      { word: "毎日", reading: "まいにち", meaning: "every day" },
      { word: "毎週", reading: "まいしゅう", meaning: "every week" },
      { word: "毎朝", reading: "まいあさ", meaning: "every morning" },
    ],
  },
  {
    id: "n4-112",
    character: "万",
    level: "N4",
    setIndex: 5,
    positionInSet: 12,
    onyomi: ["マン", "バン"],
    kunyomi: [],
    meanings: ["ten thousand", "myriad", "all"],
    strokeCount: 3,
    exampleWords: [
      { word: "一万", reading: "いちまん", meaning: "ten thousand" },
      { word: "万年筆", reading: "まんねんひつ", meaning: "fountain pen" },
      { word: "万能", reading: "ばんのう", meaning: "all-purpose, almighty" },
    ],
  },
  {
    id: "n4-113",
    character: "味",
    level: "N4",
    setIndex: 5,
    positionInSet: 13,
    onyomi: ["ミ"],
    kunyomi: ["あじ", "あじ.わう"],
    meanings: ["flavor", "taste", "experience"],
    strokeCount: 8,
    exampleWords: [
      { word: "味", reading: "あじ", meaning: "taste, flavor" },
      { word: "興味", reading: "きょうみ", meaning: "interest, curiosity" },
      { word: "意味", reading: "いみ", meaning: "meaning, significance" },
    ],
  },
  {
    id: "n4-114",
    character: "無",
    level: "N4",
    setIndex: 5,
    positionInSet: 14,
    onyomi: ["ム", "ブ"],
    kunyomi: ["な.い"],
    meanings: ["nothingness", "none", "un-", "not yet", "without"],
    strokeCount: 12,
    exampleWords: [
      { word: "無料", reading: "むりょう", meaning: "free of charge" },
      { word: "無駄", reading: "むだ", meaning: "waste, useless" },
      { word: "無理", reading: "むり", meaning: "unreasonable, impossible" },
    ],
  },
  {
    id: "n4-115",
    character: "目",
    level: "N4",
    setIndex: 5,
    positionInSet: 15,
    onyomi: ["モク", "ボク"],
    kunyomi: ["め", "-め"],
    meanings: ["eye", "look", "item", "ordinal"],
    strokeCount: 5,
    exampleWords: [
      { word: "目", reading: "め", meaning: "eye" },
      { word: "目的", reading: "もくてき", meaning: "purpose, goal, aim" },
      { word: "注目", reading: "ちゅうもく", meaning: "attention, notice" },
    ],
  },
  {
    id: "n4-116",
    character: "門",
    level: "N4",
    setIndex: 5,
    positionInSet: 16,
    onyomi: ["モン"],
    kunyomi: ["かど"],
    meanings: ["gate"],
    strokeCount: 8,
    exampleWords: [
      { word: "門", reading: "もん", meaning: "gate" },
      { word: "専門", reading: "せんもん", meaning: "specialty, expertise" },
      { word: "正門", reading: "せいもん", meaning: "main gate, front gate" },
    ],
  },
  {
    id: "n4-117",
    character: "野",
    level: "N4",
    setIndex: 5,
    positionInSet: 17,
    onyomi: ["ヤ"],
    kunyomi: ["の"],
    meanings: ["plains", "field", "rustic", "civilian life"],
    strokeCount: 11,
    exampleWords: [
      { word: "野菜", reading: "やさい", meaning: "vegetables" },
      { word: "野球", reading: "やきゅう", meaning: "baseball" },
      { word: "分野", reading: "ぶんや", meaning: "field, sphere, domain" },
    ],
  },
  {
    id: "n4-118",
    character: "夜",
    level: "N4",
    setIndex: 5,
    positionInSet: 18,
    onyomi: ["ヤ"],
    kunyomi: ["よる", "よ"],
    meanings: ["night", "evening"],
    strokeCount: 8,
    exampleWords: [
      { word: "夜", reading: "よる", meaning: "night, evening" },
      { word: "今夜", reading: "こんや", meaning: "tonight, this evening" },
      { word: "深夜", reading: "しんや", meaning: "late at night, midnight" },
    ],
  },
  {
    id: "n4-119",
    character: "有",
    level: "N4",
    setIndex: 5,
    positionInSet: 19,
    onyomi: ["ユウ", "ウ"],
    kunyomi: ["あ.る"],
    meanings: ["have", "possess", "exist", "there is"],
    strokeCount: 6,
    exampleWords: [
      { word: "有名", reading: "ゆうめい", meaning: "famous" },
      { word: "有利", reading: "ゆうり", meaning: "advantageous, profitable" },
      { word: "所有", reading: "しょゆう", meaning: "ownership, possession" },
    ],
  },
  {
    id: "n4-120",
    character: "用",
    level: "N4",
    setIndex: 6,
    positionInSet: 0,
    onyomi: ["ヨウ"],
    kunyomi: ["もち.いる"],
    meanings: ["task", "use", "service", "errand", "business"],
    strokeCount: 5,
    exampleWords: [
      { word: "使用", reading: "しよう", meaning: "use, employment" },
      { word: "用意", reading: "ようい", meaning: "preparation, readiness" },
      { word: "費用", reading: "ひよう", meaning: "cost, expense" },
    ],
  },
  {
    id: "n4-121",
    character: "旅",
    level: "N4",
    setIndex: 6,
    positionInSet: 1,
    onyomi: ["リョ"],
    kunyomi: ["たび"],
    meanings: ["travel", "journey", "trip"],
    strokeCount: 10,
    exampleWords: [
      { word: "旅行", reading: "りょこう", meaning: "travel, trip" },
      { word: "旅館", reading: "りょかん", meaning: "Japanese inn" },
      { word: "一人旅", reading: "ひとりたび", meaning: "solo travel" },
    ],
  },
  {
    id: "n4-122",
    character: "料",
    level: "N4",
    setIndex: 6,
    positionInSet: 2,
    onyomi: ["リョウ"],
    kunyomi: [],
    meanings: ["fee", "material", "ingredients", "rate", "charge"],
    strokeCount: 10,
    exampleWords: [
      { word: "料理", reading: "りょうり", meaning: "cooking, cuisine" },
      { word: "無料", reading: "むりょう", meaning: "free of charge" },
      { word: "材料", reading: "ざいりょう", meaning: "ingredients, materials" },
    ],
  },
  {
    id: "n4-123",
    character: "両",
    level: "N4",
    setIndex: 6,
    positionInSet: 3,
    onyomi: ["リョウ"],
    kunyomi: [],
    meanings: ["both", "two", "all"],
    strokeCount: 6,
    exampleWords: [
      { word: "両親", reading: "りょうしん", meaning: "both parents" },
      { word: "両方", reading: "りょうほう", meaning: "both sides, both ways" },
      { word: "両手", reading: "りょうて", meaning: "both hands" },
    ],
  },
  {
    id: "n4-124",
    character: "力",
    level: "N4",
    setIndex: 6,
    positionInSet: 4,
    onyomi: ["リョク", "リキ"],
    kunyomi: ["ちから"],
    meanings: ["power", "strength", "force", "energy"],
    strokeCount: 2,
    exampleWords: [
      { word: "力", reading: "ちから", meaning: "power, strength, force" },
      { word: "努力", reading: "どりょく", meaning: "effort, endeavor" },
      { word: "電力", reading: "でんりょく", meaning: "electric power" },
    ],
  },
  {
    id: "n4-125",
    character: "練",
    level: "N4",
    setIndex: 6,
    positionInSet: 5,
    onyomi: ["レン"],
    kunyomi: ["ね.る"],
    meanings: ["practice", "train", "drill", "refine", "polish"],
    strokeCount: 14,
    exampleWords: [
      { word: "練習", reading: "れんしゅう", meaning: "practice, exercise" },
      { word: "訓練", reading: "くんれん", meaning: "training, drill" },
      { word: "練る", reading: "ねる", meaning: "to train, to refine" },
    ],
  },
  {
    id: "n4-126",
    character: "路",
    level: "N4",
    setIndex: 6,
    positionInSet: 6,
    onyomi: ["ロ"],
    kunyomi: ["じ"],
    meanings: ["road", "path", "route"],
    strokeCount: 13,
    exampleWords: [
      { word: "道路", reading: "どうろ", meaning: "road, highway" },
      { word: "路線", reading: "ろせん", meaning: "route, line" },
      { word: "出口路", reading: "でくちろ", meaning: "exit path" },
    ],
  },
  {
    id: "n4-127",
    character: "私",
    level: "N4",
    setIndex: 6,
    positionInSet: 7,
    onyomi: ["シ"],
    kunyomi: ["わたし", "わたくし"],
    meanings: ["I", "private", "personal", "selfishness"],
    strokeCount: 7,
    exampleWords: [
      { word: "私", reading: "わたし", meaning: "I, me" },
      { word: "私立", reading: "しりつ", meaning: "private (institution)" },
      { word: "私服", reading: "しふく", meaning: "civilian clothes, casual wear" },
    ],
  },
];
